#!/usr/bin/env bash
# mox lib/audio.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── do_vol ──────────────────────────────────────────────────────
do_vol() {
  # Validate input first, before checking daemon
  case "${1:-}" in
    +|-)
      # These are valid, check daemon
      ;;
    '')
      # Show current volume, check daemon
      ;;
    *)
      # Validate numeric input first
      [[ "${1:-}" =~ ^[0-9]+$ ]] || { _err "usage: mox vol [0-150 | + | -]"; return 1; }
      (( $1 > 150 )) && { _err "max volume is 150"; return 1; }
      ;;
  esac
  
  _need
  case "${1:-}" in
    +)
      _silent "{\"command\":[\"add\",\"volume\",${VOLUME_STEP}]}"
      local v; v=$(_get volume | awk '{printf "%.0f",$1}')
      (( v > 150 )) && _silent '{"command":["set_property","volume",150]}'
      ;;
    -)
      _silent "{\"command\":[\"add\",\"volume\",-${VOLUME_STEP}]}"
      local v; v=$(_get volume | awk '{printf "%.0f",$1}')
      (( v < 0 )) && _silent '{"command":["set_property","volume",0]}'
      ;;
    '')
      local v; v=$(_get volume)
      _info "volume: $(echo "$v" | awk '{printf "%.0f%%",$1}')"
      return
      ;;
    *)
      _silent "{\"command\":[\"set_property\",\"volume\",$1]}"
      ;;
  esac
  local v; v=$(_get volume)
  _info "volume: $(echo "$v" | awk '{printf "%.0f%%",$1}')"
}

# ── do_eq ───────────────────────────────────────────────────────
do_eq() {
  local preset="${1:-}"
  case "$preset" in
    flat|off|none)
      _need
      local current; current=$(_af_get_raw)
      local new_af
      if echo "$current" | grep -qF "loudnorm"; then
        new_af=$(echo "$current" | awk -v frag="equalizer" 'BEGIN{FS=OFS=","}{ result=""; for(i=1;i<=NF;i++){if(index($i,frag)==0) result=(result==""?$i:result","$i)} print result }')
        new_af=$(echo "$new_af" | sed 's/lavfi=\[,/lavfi=[/g; s/,\]/]/g; s/lavfi=\[\]//g')
        _af_set "${new_af:-}"
      else
        _af_set ""
      fi
      _ok "🎚  equalizer: flat (off)"
      ;;
    bass)   _need; _af_set "$_EQ_BASS";   _ok "🎚  equalizer: bass boost" ;;
    treble) _need; _af_set "$_EQ_TREBLE"; _ok "🎚  equalizer: treble boost" ;;
    vocal)  _need; _af_set "$_EQ_VOCAL";  _ok "🎚  equalizer: vocal" ;;
    loud|loudness) _need; _af_set "$_EQ_LOUD"; _ok "🎚  equalizer: loudness" ;;
    '')
      # Show usage - no daemon needed
      _info "current af filter: flat/off"
      echo ""
      echo "  presets: flat  bass  treble  vocal  loud"
      echo "  usage:   mox eq <preset>"
      echo ""
      ;;
    *)
      _err "unknown preset: $preset  (flat | bass | treble | vocal | loud)"
      return 1
      ;;
  esac
}

# ── do_norm ─────────────────────────────────────────────────────
do_norm() {
  _need
  local current; current=$(_af_get_raw)
  if echo "$current" | grep -qF "loudnorm"; then
    local new_af; new_af=$(echo "$current" | awk 'BEGIN{FS=OFS=","}{result=""; for(i=1;i<=NF;i++){if(index($i,"acompressor")==0 && index($i,"loudnorm")==0) result=(result==""?$i:result","$i)} print result }')
    _af_set "${new_af:-}"
    rm -f "$NORM_STATE_FILE"
    _ok "🔇 loudness normalisation: OFF"
  else
    local new_af="${current:+${current},}acompressor,loudnorm"
    _af_set "$new_af"
    touch "$NORM_STATE_FILE"
    _ok "🔊 loudness normalisation: ON  (levels balanced across tracks)"
  fi
}

# ── do_devices ──────────────────────────────────────────────────
do_devices() {
  echo ""; echo "  ${C}audio devices:${X}"
  "$MPV" --audio-device=help 2>&1 | grep "'" | sed 's/^/  /'
  echo ""
  echo "  current:     ${W}$(_get audio-device)${X}"
  echo "  speakers:    ${W}${AUDIO_DEVICE_SPEAKERS:-not configured}${X}"
  echo "  headphones:  ${W}${AUDIO_DEVICE_HEADPHONES:-not configured}${X}"
  echo "  (set in: $CONFIG_FILE)"; echo ""
}
