#!/usr/bin/env bash
# mox lib/core.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── _load_config ────────────────────────────────────────────────
_load_config() {
  [[ -f "$CONFIG_FILE" ]] || return 0

  local -a allowed_keys
  allowed_keys=(
    CACHE_TTL HISTORY_MAX DEFAULT_VOLUME VOLUME_STEP SEARCH_RESULTS
    AUDIO_DEVICE_SPEAKERS AUDIO_DEVICE_HEADPHONES SCROBBLE_URL
    YTDLP_MAX_AGE_DAYS LASTFM_API_KEY YOUTUBE_API_KEY INVIDIOUS_HOST
    LOCAL_MUSIC_DIR AUTODJ_ENABLED LYRICS_ENABLED AUTO_RESTART_DAEMON
    NOTIFY_ENABLED CROSSFADE_SECS BAR_REFRESH_MS M_UPDATE_URL M_UPDATE_SHA256
    UXI_AUTH YTDLP MPV FZF SOCAT JQ CURL CHAFA FFPROBE
  )

  local line key value allowed allowed_key
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" || "$line" == \#* ]] && continue

    if [[ ! "$line" =~ '^[A-Z_][A-Z0-9_]*=[^;&|`$<>(){}[\]\\]*$' ]]; then
      printf 'mox config: ignoring unsafe line: %s\n' "$line" >&2
      continue
    fi

    key="${line%%=*}"
    value="${line#*=}"
    allowed=0
    for allowed_key in "${allowed_keys[@]}"; do
      [[ "$key" == "$allowed_key" ]] && { allowed=1; break; }
    done
    if [[ $allowed -ne 1 ]]; then
      printf 'mox config: ignoring unknown key: %s\n' "$key" >&2
      continue
    fi

    if [[ "$value" == \"*\" && "$value" == *\" ]]; then
      value="${value[2,-2]}"
    elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
      value="${value[2,-2]}"
    fi
    typeset -g "$key=$value"
  done < "$CONFIG_FILE"
}

# ── _validate_config ────────────────────────────────────────────
_validate_config() {
  local -a _cfg_checks
  _cfg_checks=(
    "CACHE_TTL:${CACHE_TTL}:1:86400:3600"
    "HISTORY_MAX:${HISTORY_MAX}:10:100000:500"
    "DEFAULT_VOLUME:${DEFAULT_VOLUME}:0:150:80"
    "VOLUME_STEP:${VOLUME_STEP}:1:50:5"
    "SEARCH_RESULTS:${SEARCH_RESULTS}:1:50:20"
    "YTDLP_MAX_AGE_DAYS:${YTDLP_MAX_AGE_DAYS}:1:365:30"
  )
  local entry var val min max default
  for entry in "${_cfg_checks[@]}"; do
    var="${entry%%:*}"; local _rest="${entry#*:}"
    val="${_rest%%:*}"; _rest="${_rest#*:}"
    min="${_rest%%:*}"; max="${_rest#*:}"
    default="${max#*:}"; max="${max%%:*}"
    if [[ ! "$val" =~ ^[0-9]+$ ]] || (( val < min || val > max )); then
      echo "${Y}⚠ config: ${var}=${val} is invalid (expected integer ${min}–${max}), using default${X}" >&2
      typeset -g "$var=$default"
    fi
  done
}

# ── colours ──────────────────────────────────────────────────
R=$'\e[0;31m'; G=$'\e[0;32m'; Y=$'\e[0;33m'
C=$'\e[0;36m'; W=$'\e[1;37m'; M=$'\e[0;35m'; X=$'\e[0m'
DIM=$'\e[2m'; BOLD=$'\e[1m'

# ── _os ─────────────────────────────────────────────────────────
_os() {
  case "$(uname -s)" in
    Darwin) echo "mac" ;;
    Linux)  echo "linux" ;;
    *)      echo "unknown" ;;
  esac
}
OS=$(_os)

# ── _mtime ──────────────────────────────────────────────────────
_mtime() {
  local f="$1"
  if [[ "$OS" == "mac" ]]; then stat -f%m "$f" 2>/dev/null || echo 0
  else stat -c%Y "$f" 2>/dev/null || echo 0
  fi
}

# ── _tac ────────────────────────────────────────────────────────
_tac() {
  if command -v tac &>/dev/null; then tac "$@"
  else tail -r "$@"
  fi
}

# ── _resolve_bin ────────────────────────────────────────────────
_resolve_bin() {
  local name="$1"
  local found; found=$(command -v "$name" 2>/dev/null)
  [ -n "$found" ] && { echo "$found"; return 0; }
  for prefix in /opt/homebrew/bin /usr/local/bin /home/linuxbrew/.linuxbrew/bin; do
    [ -x "$prefix/$name" ] && { echo "$prefix/$name"; return 0; }
  done
  echo ""; return 1
}

# ── _ensure_bin ─────────────────────────────────────────────────
_ensure_bin() {
  local varname="$1" binary="$2"
  # Already resolved (non-empty)?
  [[ -n "${(P)varname}" ]] && return 0
  local path; path=$(_resolve_bin "$binary")
  if [[ -n "$path" ]]; then
    eval "${varname}=${(q)path}"
  fi
}

# ── _bootstrap ──────────────────────────────────────────────────
_bootstrap() {
  mkdir -p "$SOCKET_DIR" "$CACHE_DIR" "$PLAYLIST_DIR" \
           "$TXTS_DIR" "$DOWNLOADS_DIR" "$DATA_DIR" "$LOCK_DIR" "$PLUGINS_DIR" \
           "$SHARE_DIR" "$SCHEDULE_DIR"
  [[ ! -f "$LIKES_FILE" ]]   && touch "$LIKES_FILE"
  [[ ! -f "$HISTORY_FILE" ]] && touch "$HISTORY_FILE"
  [[ ! -f "$BOOKMARKS_FILE" ]] && touch "$BOOKMARKS_FILE"
  [[ ! -f "$PINS_FILE" ]] && touch "$PINS_FILE"
  if [[ ! -f "$STATIONS_FILE" ]]; then
    printf '# genre\tname\turl\n# rock\tBBC Radio 1\thttps://stream.example.com/radio1\n' > "$STATIONS_FILE"
  fi
  if [[ ! -f "$CONFIG_FILE" ]]; then
    cat > "$CONFIG_FILE" <<'EOF'
# mox — user config  (uncomment + edit to override defaults)
# CACHE_TTL=3600
# HISTORY_MAX=500
# DEFAULT_VOLUME=80
# VOLUME_STEP=5
# SEARCH_RESULTS=20
# YTDLP_MAX_AGE_DAYS=30
# YTDLP=/usr/local/bin/yt-dlp
# MPV=/usr/local/bin/mpv
# AUDIO_DEVICE_SPEAKERS=coreaudio/BuiltInSpeakerDevice
# AUDIO_DEVICE_HEADPHONES=coreaudio/BuiltInHeadphoneOutputDevice
# SCROBBLE_URL=https://api.listenbrainz.org/1/submit-listens
# LASTFM_API_KEY=your_key_here      # enables real similar-track recommendations
# YOUTUBE_API_KEY=your_key_here     # v5: enables fast YouTube Data API search (ms vs s)
# INVIDIOUS_HOST=https://invidious.snopyta.org  # v5: privacy-friendly search alternative
# LOCAL_MUSIC_DIR=$HOME/Music       # v5: local library root for mox index
# AUTODJ_ENABLED=0                  # v5: 1 = auto-refill queue from Last.fm when empty
# LYRICS_ENABLED=1                  # v5: 0 = disable real-time lyrics
# AUTO_RESTART_DAEMON=true          # v6: false = disable auto-restart when daemon unresponsive
# NOTIFY_ENABLED=0                  # 1 = desktop notification on track change
# CROSSFADE_SECS=0                  # crossfade duration between tracks (0=off)
# BAR_REFRESH_MS=500                # progress bar refresh interval
# M_UPDATE_URL=                     # self-update URL (empty=disabled)
# M_UPDATE_SHA256=                  # expected SHA256 for self-update
# UXI_AUTH=0                        # 1 = require a startup PIN for web UI
EOF
  fi
}

# ── _die ────────────────────────────────────────────────────────
_die() {
  local code=1
  if [[ "${1:-}" =~ ^[0-9]+$ ]]; then code="$1"; shift; fi
  echo "${R}✖ $*${X}" >&2
  exit "$code"
}

# ── _err ────────────────────────────────────────────────────────
_err() {
  local code=1
  if [[ "${1:-}" =~ ^[0-9]+$ ]]; then code="$1"; shift; fi
  echo "${R}✖ $*${X}" >&2
  return "$code"
}

# ── _ok ─────────────────────────────────────────────────────────
_ok()   { echo "${G}✔ $*${X}"; }
_info() { echo "${C}→ $*${X}"; }

# ── _warn ───────────────────────────────────────────────────────
_warn() { echo "${Y}⚠ $*${X}"; }


# ── _check_deps ─────────────────────────────────────────────────
_check_deps() {
  # Resolve required binaries on first use
  _ensure_bin MPV    mpv
  _ensure_bin SOCAT  socat
  _ensure_bin JQ     jq
  _ensure_bin CURL   curl
  _ensure_bin YTDLP  yt-dlp
  _ensure_bin FZF    fzf
  _ensure_bin CHAFA  chafa
  _ensure_bin FFPROBE ffprobe

  local missing=0
  for bin in "$MPV" "$SOCAT" "$JQ"; do
    if [[ -z "$bin" || ! -x "$bin" ]]; then
      _warn "missing binary: ${bin:-<unresolved>}"
      missing=1
    fi
  done
  if [[ $missing -eq 1 ]]; then
    _die 2 "install missing deps:\n  macOS: brew install mpv socat jq\n  Linux: sudo apt install mpv socat jq"
  fi
  # Optional deps are checked by the specific commands that need them.
}

# ── _check_ytdlp_age ────────────────────────────────────────────
_check_ytdlp_age() {
  [[ -x "$YTDLP" ]] || return
  local ver_file="$CACHE_DIR/.ytdlp_version_check"
  local age; age=$(_cache_age "$ver_file" 2>/dev/null || echo 99999)
  (( age < 86400 )) && return
  touch "$ver_file"
  local ver_str; ver_str=$("$YTDLP" --version 2>/dev/null | head -1)
  local ver_date; ver_date=$(echo "$ver_str" | grep -oE '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}')
  [[ -z "$ver_date" ]] && return
  local ver_epoch
  if [[ "$OS" == "mac" ]]; then
    ver_epoch=$(date -j -f "%Y.%m.%d" "$ver_date" "+%s" 2>/dev/null || echo 0)
  else
    ver_epoch=$(date -d "${ver_date//./-}" "+%s" 2>/dev/null || echo 0)
  fi
  local now; now=$(date +%s)
  local days_old=$(( (now - ver_epoch) / 86400 ))
  if (( days_old > YTDLP_MAX_AGE_DAYS )); then
    _warn "yt-dlp is ${days_old} days old (${ver_str}) — run: mox update"
  fi
}

# ── _detect_audio_devices ───────────────────────────────────────
_detect_audio_devices() {
  [[ "$OS" != "mac" ]] && return
  [[ -z "$AUDIO_DEVICE_SPEAKERS"   ]] && AUDIO_DEVICE_SPEAKERS="coreaudio/BuiltInSpeakerDevice"
  [[ -z "$AUDIO_DEVICE_HEADPHONES" ]] && AUDIO_DEVICE_HEADPHONES="coreaudio/BuiltInHeadphoneOutputDevice"
}

# ── _start ──────────────────────────────────────────────────────
_start() {
  _check_deps
  [ -S "$SOCKET" ] && return 0
  if ! _lock "$LOCK_FILE" 5; then
    _info "waiting for daemon to start..."
    for i in $(seq 1 30); do
      sleep 0.3
      [ -S "$SOCKET" ] && return 0
    done
    _die 3 "daemon failed to start (lock timeout)"
  fi
  if [ -S "$SOCKET" ]; then
    _unlock "$LOCK_FILE"; return 0
  fi
  _info "starting daemon..."
  # Remove any stale socket left by a previously crashed mpv.
  # Without this, _start() sees [ -S "$SOCKET" ] = true on next call and returns
  # early thinking the daemon is running, causing all IPC to silently fail.
  rm -f "$SOCKET" 2>/dev/null

  local device_flag=""
  [[ -n "$AUDIO_DEVICE_SPEAKERS" ]] && device_flag="--audio-device=$AUDIO_DEVICE_SPEAKERS"
  local gapless_flag=""
  [[ "${CROSSFADE_SECS:-0}" != "0" ]] && gapless_flag="--gapless-audio=yes"
  "$MPV" --no-video --idle=yes \
    --input-ipc-server="$SOCKET" \
    --script-opts=ytdl_hook-ytdl_path="$YTDLP" \
    ${device_flag:+"$device_flag"} \
    ${gapless_flag:+"$gapless_flag"} \
    --volume="$DEFAULT_VOLUME" \
    --quiet --really-quiet \
    --ytdl-format="bestaudio/best" \
    --cache=yes --cache-secs=20 \
    --demuxer-max-bytes=50MiB \
    --prefetch-playlist=yes \
    --save-position-on-quit=no \
    2>>"$MPV_LOG" &
  local mpv_pid=$!
  disown $mpv_pid 2>/dev/null || true
  echo $mpv_pid > "$MPV_PID_FILE"
  for i in $(seq 1 30); do
    sleep 0.3
    if [ -S "$SOCKET" ]; then
      # Restore volume/speed from last session
      if [[ -f "$VOLUME_SPEED_STATE" ]]; then
        sleep 0.3
        local v s
        v=$(awk -F= '$1=="volume"{print $2; exit}' "$VOLUME_SPEED_STATE")
        s=$(awk -F= '$1=="speed"{print $2; exit}' "$VOLUME_SPEED_STATE")
        [[ -n "$v" ]] && echo "{\"command\":[\"set_property\",\"volume\",$v]}" | "$SOCAT" - "$SOCKET" >/dev/null 2>&1
        [[ -n "$s" ]] && echo "{\"command\":[\"set_property\",\"speed\",$s]}" | "$SOCAT" - "$SOCKET" >/dev/null 2>&1
      fi
      if [[ -f "$NORM_STATE_FILE" ]]; then
        echo '{"command":["set_property","af","acompressor,loudnorm"]}' | "$SOCAT" - "$SOCKET" >/dev/null 2>&1
      fi
      _unlock "$LOCK_FILE"; return 0
    fi
  done
  _unlock "$LOCK_FILE"
  rm -f "$MPV_PID_FILE"
  _die 3 "mpv daemon failed to start — check: $MPV_LOG"
}

# ── _need ───────────────────────────────────────────────────────
_need() {
  _check_deps
  if [ ! -S "$SOCKET" ]; then
    _die 3 "daemon not running — run: mox start"
  fi
  if ! echo '{"command":["get_version"]}' \
        | "$SOCAT" -t 2 - "$SOCKET" >/dev/null 2>&1; then
    # Check if auto-restart is enabled
    if [[ "${AUTO_RESTART_DAEMON:-true}" == "true" ]]; then
      _info "daemon unresponsive, attempting auto-restart..."
      do_stop >/dev/null 2>&1
      _start
      if echo '{"command":["get_version"]}' | "$SOCAT" -t 2 - "$SOCKET" >/dev/null 2>&1; then
        _ok "daemon auto-restarted successfully"
        return 0
      else
        _die 3 "daemon auto-restart failed — please try: mox stop && mox start"
      fi
    else
      _die 3 "daemon socket exists but mpv is unresponsive — run: mox stop && mox start"
    fi
  fi
}

# ── _notify_track ───────────────────────────────────────────────
_notify_track() {
  [[ "${NOTIFY_ENABLED:-0}" != "1" ]] && return
  local title="${1:-unknown}"
  if [[ "$OS" == "mac" ]]; then
    command -v osascript &>/dev/null && osascript -e "display notification \"${title}\" with title \"m\" sound name \"default\"" 2>/dev/null
  else
    command -v notify-send &>/dev/null && notify-send "mox" "$title" 2>/dev/null
  fi
}

# ── _scrobble ───────────────────────────────────────────────────
_scrobble() {
  [[ -z "${SCROBBLE_URL:-}" ]] && return 0
  local title="$1" url="$2"
  command -v curl >/dev/null 2>&1 || return 0
  local payload
  payload=$("$JQ" -cn \
    --arg title "$title" --arg url "$url" --arg ts "$(date +%s)" \
    '{listen_type:"single",payload:[{listened_at:($ts|tonumber),track_metadata:{track_name:$title,additional_info:{media_player:"m-cli",origin_url:$url}}}]}')
  curl -s --max-time 5 -X POST "$SCROBBLE_URL" \
    -H "Content-Type: application/json" \
    -d "$payload" >/dev/null 2>&1 || true
}

# ── _is_local_file ──────────────────────────────────────────────
_is_local_file() {
  local arg="$1"
  [[ -f "$arg" || "$arg" == /* || "$arg" == ./* || "$arg" == ../* ]] && return 0
  return 1
}
