#!/usr/bin/env bash
# mox lib/history.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── _log_history ────────────────────────────────────────────────
_log_history() {
  local title="$1" url="$2"
  [ -z "$url" ] && return
  local norm_url; norm_url=$(printf '%s' "$url" | tr '[:upper:]' '[:lower:]')

  _notify_track "$title"

  if _lock "$HISTORY_LOCK" 3; then
    # Dedup: check last 50 entries for this URL
    local recent_count
    recent_count=$(tail -50 "$HISTORY_FILE" 2>/dev/null | tr '[:upper:]' '[:lower:]' | grep -cF "$norm_url" 2>/dev/null)
    recent_count="${recent_count:-0}"
    recent_count=$(echo "$recent_count" | tr -cd '0-9')
    recent_count="${recent_count:-0}"
    if [[ "$recent_count" -eq 0 ]]; then
      printf '%s\t%s\t%s\n' "$(date '+%Y-%m-%d %H:%M')" "$title" "$url" >> "$HISTORY_FILE"
      local lines; lines=$(wc -l < "$HISTORY_FILE" | tr -d ' ')
      if [ "$lines" -gt "$HISTORY_MAX" ]; then
        local tmpf; tmpf=$(mktemp "$HISTORY_FILE.XXXXXX")
        tail -n "$HISTORY_MAX" "$HISTORY_FILE" > "$tmpf" \
          && mv "$tmpf" "$HISTORY_FILE" \
          || rm -f "$tmpf"
      fi
    fi
    _unlock "$HISTORY_LOCK"
  else
    # Lock timeout — append without dedup/trim
    printf '%s\t%s\t%s\n' "$(date '+%Y-%m-%d %H:%M')" "$title" "$url" >> "$HISTORY_FILE"
  fi

  _scrobble "$title" "$url" &
  disown $! 2>/dev/null
}

# ── do_like ─────────────────────────────────────────────────────
do_like() {
  _need
  local title url clean
  title=$(_get media-title)
  url=$(_get path)
  [ -z "$url" ] && { _warn "nothing playing"; return; }
  clean=$(_clean_url "$url")
  if grep -qF "$clean" "$LIKES_FILE" 2>/dev/null; then
    _warn "already liked: $title"
    return
  fi
  printf '%s\t%s\t%s\n' "$(date '+%Y-%m-%d %H:%M')" "$title" "$clean" >> "$LIKES_FILE"
  _ok "❤  liked: ${title}"
}

# ── do_unlike ───────────────────────────────────────────────────
do_unlike() {
  _check_deps
  [ -s "$LIKES_FILE" ] || { _warn "no likes yet"; return; }
  local line
  line=$("$FZF" \
    --height 50% --reverse \
    --prompt "💔 unlike > " \
    --header "ENTER to remove · ESC cancel" \
    --with-nth=2 --delimiter=$'\t' < "$LIKES_FILE")
  [ -z "$line" ] && { _warn "cancelled"; return; }
  local tmpf; tmpf=$(mktemp "$LIKES_FILE.XXXXXX")
  grep -vF "$line" "$LIKES_FILE" > "$tmpf" && mv "$tmpf" "$LIKES_FILE" || rm -f "$tmpf"
  _ok "removed from likes"
}

# ── do_likes ────────────────────────────────────────────────────
do_likes() {
  [ -s "$LIKES_FILE" ] || { _warn "no likes yet — use: mox like"; return; }
  echo ""
  echo "  ${M}❤  liked tracks${X}"
  echo ""
  awk -F'\t' '{print NR". "$2}' "$LIKES_FILE" | sed 's/^/  /'
  echo ""
}

# ── do_love ─────────────────────────────────────────────────────
do_love() {
  _need
  [ -s "$LIKES_FILE" ] || { _warn "no likes yet — use: mox like while playing"; return; }
  local line; line=$(_shuf1 "$LIKES_FILE")
  [ -z "$line" ] && { _warn "likes file empty"; return; }
  local url title
  url=$(printf '%s' "$line" | awk -F'\t' '{print $3}')
  title=$(printf '%s' "$line" | awk -F'\t' '{print $2}')
  _start
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$url" "replace"
  local actual_title; actual_title=$(_wait_title "$url" 30)
  _ok "❤  ▶  ${actual_title:-$title}"
}

# ── do_likes_play ───────────────────────────────────────────────
do_likes_play() {
  _need
  _check_deps
  [ -s "$LIKES_FILE" ] || { _warn "no likes yet"; return; }
  local line
  line=$("$FZF" \
    --height 50% --reverse \
    --prompt "❤ play liked > " \
    --header "ENTER play · ESC cancel" \
    --with-nth=2 --delimiter=$'\t' < "$LIKES_FILE")
  [ -z "$line" ] && { _warn "cancelled"; return; }
  local url; url=$(printf '%s' "$line" | awk -F'\t' '{print $3}')
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$url" "replace"
  local actual_title; actual_title=$(_wait_title "$url" 30)
  _ok "▶  ${actual_title:-playing}"
}

# ── do_history ──────────────────────────────────────────────────
do_history() {
  _check_deps
  [ -s "$HISTORY_FILE" ] || { _warn "no history yet"; return; }
  
  # In test mode, just show the history list
  if [[ -n "${MOX_TEST_MODE:-}" ]]; then
    _tac "$HISTORY_FILE" | awk -F'\t' '{printf "%-20s %s\n", $1, $2}'
    return 0
  fi
  
  local line url
  line=$(_tac "$HISTORY_FILE" | "$FZF" \
    --height 60% --reverse \
    --prompt "🕑 history > " \
    --header "ENTER replay · ESC cancel" \
    --with-nth=1,2 --delimiter=$'\t' \
    --preview 'echo {} | awk -F"\t" "{printf \"Date:  %s\nTitle: %s\nURL:   %s\n\",\$1,\$2,\$3}"' \
    --preview-window=down:3:wrap)
  [ -z "$line" ] && { _warn "cancelled"; return; }
  url=$(printf '%s' "$line" | awk -F'\t' '{print $3}')
  [ -z "$url" ] && { _err "could not extract URL from history entry"; return 1; }
  _start
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$url" "replace"
  local title; title=$(_wait_title "$url" 30)
  _ok "▶  ${title:-playing}"
}

# ── do_history_clear ────────────────────────────────────────────
do_history_clear() {
  # In test mode, clear without prompting
  if [[ -n "${MOX_TEST_MODE:-}" ]]; then
    echo "" > "$HISTORY_FILE"
    _ok "history cleared"
    return 0
  fi
  
  printf "${Y}Clear all history? [y/N] ${X}"
  read -r ans
  [[ "$ans" =~ ^[Yy]$ ]] || { _warn "cancelled"; return; }
  echo "" > "$HISTORY_FILE"
  _ok "history cleared"
}
