#!/usr/bin/env bash
# mox lib/ipc.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── _cmd ────────────────────────────────────────────────────────
_cmd() {
  echo "$1" | "$SOCAT" - "$SOCKET" 2>/dev/null
}

# ── _silent ─────────────────────────────────────────────────────
_silent() {
  echo "$1" | "$SOCAT" - "$SOCKET" >/dev/null 2>&1
}

# ── _silent_retry ───────────────────────────────────────────────
_silent_retry() {
  local json="$1" attempts="${2:-3}" i
  for i in $(seq 1 $attempts); do
    if echo "$json" | "$SOCAT" - "$SOCKET" >/dev/null 2>&1; then return 0; fi
    sleep 0.1
  done
  return 1
}

# ── _get ────────────────────────────────────────────────────────
_get() {
  local raw
  raw=$(_cmd "{\"command\":[\"get_property\",\"$1\"]}")
  echo "$raw" | "$JQ" -r '.data // empty' 2>/dev/null
}

# ── _get_checked ────────────────────────────────────────────────
_get_checked() {
  _GET_ERROR=""
  local raw; raw=$(_cmd "{\"command\":[\"get_property\",\"$1\"]}")
  local err; err=$(echo "$raw" | "$JQ" -r '.error // empty' 2>/dev/null)
  if [[ "$err" == "property unavailable" || "$err" == "invalid parameter" ]]; then
    _GET_ERROR="unavailable"
    echo ""
    return 1
  fi
  echo "$raw" | "$JQ" -r '.data // empty' 2>/dev/null
}

# ── _get_multi ──────────────────────────────────────────────────
_get_multi() {
  local props_json
  props_json=$(printf '%s\n' "$@" | "$JQ" -R . | "$JQ" -s . 2>/dev/null) || return 1
  "$JQ" -cn --argjson props "$props_json" '
    $props | to_entries[] |
    {command:["get_property", .value], request_id:(.key + 1)}
  ' 2>/dev/null | "$SOCAT" - "$SOCKET" 2>/dev/null | "$JQ" -cn --argjson props "$props_json" '
    reduce inputs as $resp
      ({};
       if ($resp.request_id and $props[$resp.request_id - 1]) then
         .[$props[$resp.request_id - 1]] =
           (if (($resp.error // "success") == "success") then ($resp.data // "") else "" end)
       else . end)
  ' 2>/dev/null
}

# ── _wait_prop ──────────────────────────────────────────────────
_wait_prop() {
  local prop="$1" max="${2:-60}" val
  local -a spinner
  spinner=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
  local si=0 sleep_ms=100 _is_url=0 sp=""

  # v5-A: brief initial yield so mpv can start the load before we poll
  sleep 0.3

  for i in $(seq 1 "$max"); do
    val=$(_get_checked "$prop")

    # v5-D: hard error → stop spinning immediately
    if [[ "$_GET_ERROR" == "unavailable" ]]; then
      printf '\r\e[2K' >&2
      echo ""
      return 1
    fi

    # v5-A: reject if value looks like a raw URL or URL fragment (title not resolved yet)
    _is_url=0
    [[ "$val" == http* ]] && _is_url=1
    [[ "$val" == *"watch?v="* ]] && _is_url=1
    [[ "$val" == *"?v="* ]] && _is_url=1
    [[ "$val" == youtu* ]] && _is_url=1
    [[ "$val" == "null" ]] && _is_url=1
    if [[ -n "$val" && $_is_url -eq 0 ]]; then
      printf '\r\e[2K' >&2
      echo "$val"
      return 0
    fi

    sp="${spinner[$(( (si % ${#spinner[@]}) + 1 ))]}"
    printf '\r\e[2K  %s buffering...' "$sp" >&2
    si=$(( si + 1 ))
    (( i % 10 == 0 && sleep_ms < 800 )) && sleep_ms=$(( sleep_ms * 2 ))
    sleep "0.${(l:3::0:)sleep_ms}"
  done

  printf '\r\e[2K' >&2

  # v5-A: one final retry with a longer wait if we timed out
  sleep 1
  val=$(_get media-title)
  if [[ -n "$val" && "$val" != http* && "$val" != *"watch?v="* && "$val" != "null" && "$val" != youtu* ]]; then
    echo "$val"; return 0
  fi

  echo ""
}

# ── _wait_title ─────────────────────────────────────────────────
_wait_title() {
  local url="$1" max="${2:-60}"
  local initial_wait=0.3
  [[ "$url" == http* || "$url" == *youtu* || "$url" == *youtube* ]] && initial_wait=1.5
  sleep "$initial_wait"
  _wait_prop media-title "$max"
}

# ── _ipc_cmd ────────────────────────────────────────────────────
_ipc_cmd() {
  local cmd_json
  cmd_json=$("$JQ" -cn --args '{"command":$ARGS.positional}' -- "$@")
  _silent_retry "$cmd_json"
}

# ── _ipc_loadfile ───────────────────────────────────────────────
_ipc_loadfile() {
  local url="$1" mode="${2:-append-play}"
  local json
  json=$("$JQ" -cn --arg url "$url" --arg mode "$mode" \
    '{"command":["loadfile",$url,$mode]}')
  _silent_retry "$json"
}
