#!/usr/bin/env bash
# mox lib/lock.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── _lock ───────────────────────────────────────────────────────
_lock() {
  local lf="$1" timeout="${2:-5}"
  local deadline=$(( $(date +%s) + timeout ))
  local steal_count=0 MAX_STEALS=3

  if [[ "$OS" == "linux" ]] && command -v flock >/dev/null 2>&1; then
    local fd
    exec {fd}> "${lf}.flock" || return 1
    if flock -w "$timeout" "$fd" 2>/dev/null; then
      echo $$ > "$lf"
      typeset -gA _MOX_LOCK_FDS
      _MOX_LOCK_FDS[$lf]="$fd"
      return 0
    fi
    eval "exec ${fd}>&-" 2>/dev/null
    return 1
  fi

  while true; do
    # Try atomic acquire
    if mkdir "${lf}.d" 2>/dev/null; then
      echo $$ > "$lf"
      return 0
    fi

    # Lock held — check if stale
    if [[ $(date +%s) -gt $deadline ]]; then
      if [[ $steal_count -lt $MAX_STEALS && -f "$lf" ]]; then
        local dead_pid; dead_pid=$(cat "$lf" 2>/dev/null)
        if [[ -n "$dead_pid" ]] && ! kill -0 "$dead_pid" 2>/dev/null; then
          # PID is dead. Two-phase steal: rename PID file first (atomic claim),
          # then rmdir only if rename succeeded — avoids TOCTOU race.
          local steal_src="${lf}.steal.$$"
          local steal_claim="${lf}.steal"
          printf '%s:%s\n' "$$" "$(date +%s)" > "$steal_src" 2>/dev/null || return 1
          if ln "$steal_src" "$steal_claim" 2>/dev/null; then
            rmdir "${lf}.d" 2>/dev/null
            rm -f "$lf" "$steal_claim"
            rm -f "$steal_src"
            steal_count=$(( steal_count + 1 ))
            deadline=$(( $(date +%s) + timeout ))
            continue  # immediately retry mkdir
          fi
          rm -f "$steal_src"
        fi
      fi
      return 1  # live lock or max steals exceeded
    fi
    sleep 0.05
  done
}

# ── _unlock ─────────────────────────────────────────────────────
_unlock() {
  local lf="$1"
  if [[ -n "${_MOX_LOCK_FDS[$lf]:-}" ]]; then
    local fd="${_MOX_LOCK_FDS[$lf]}"
    rm -f "$lf"
    flock -u "$fd" 2>/dev/null
    eval "exec ${fd}>&-" 2>/dev/null
    unset "_MOX_LOCK_FDS[$lf]"
    return
  fi
  local stored_pid; stored_pid=$(cat "$lf" 2>/dev/null)
  if [[ "$stored_pid" == "$$" ]]; then
    rm -f "$lf"
    rmdir "${lf}.d" 2>/dev/null
  fi
}
