#!/usr/bin/env bash
# mox lib/lyrics.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── do_lyrics ───────────────────────────────────────────────────
do_lyrics() {
  _need
  [[ -z "$CURL" || ! -x "$CURL" ]] && { _err "curl required for lyrics"; return 1; }
  [[ "$LYRICS_ENABLED" != "1" ]] && { _warn "lyrics disabled — set LYRICS_ENABLED=1 in config"; return; }

  local title; title=$(_get media-title)
  [ -z "$title" ] && { _warn "nothing playing"; return; }

  _info "fetching lyrics for: $title"

  # Clean the title aggressively for lyrics search
  local cleaned; cleaned=$(_lyrics_clean_title "$title")

  # Try to split "Artist - Title" format
  local artist="" track="$cleaned"
  if echo "$cleaned" | grep -q ' - '; then
    artist=$(echo "$cleaned" | cut -d'-' -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    track=$(echo "$cleaned"  | cut -d'-' -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  fi

  # Multi-attempt search using global _LYRICS_LRC / _LYRICS_HAS_SYNC
  # (avoids calling functions inside $() which causes zsh local-leak)
  local lrc="" has_sync=0 found=0

  # Attempt 1: cleaned track + artist
  if _lyrics_try_fetch "$track" "$artist"; then
    found=1
  fi
  # Attempt 2: full cleaned title (no artist split)
  if [[ $found -eq 0 ]]; then
    if _lyrics_try_fetch "$cleaned" ""; then found=1; fi
  fi
  # Attempt 3: first few words only (strip trailing metadata)
  if [[ $found -eq 0 ]]; then
    local short; short=$(printf '%s' "$cleaned" | awk '{for(i=1;i<=NF&&i<=8;i++) printf "%s ", $i}' | sed 's/ *$//')
    if [[ "$short" != "$cleaned" && -n "$short" ]]; then
      _info "retrying with: $short"
      if _lyrics_try_fetch "$short" ""; then found=1; fi
    fi
  fi
  # Attempt 4: original title as last resort
  if [[ $found -eq 0 && "$cleaned" != "$title" ]]; then
    if _lyrics_try_fetch "$title" ""; then found=1; fi
  fi

  if [[ $found -eq 0 ]]; then
    _warn "no lyrics found for: $cleaned"
    _info "tip: YouTube titles with heavy metadata may not match lyrics databases"
    return
  fi

  lrc="$_LYRICS_LRC"
  has_sync=$_LYRICS_HAS_SYNC

  if [[ "$has_sync" -eq 0 ]]; then
    # Plain lyrics — just display with pager
    echo ""
    echo "  ${C}Lyrics: ${title}${X}  ${DIM}(plain — no sync)${X}"
    echo ""
    echo "$lrc" | sed 's/^/  /'
    echo ""
    return
  fi

  # Synced lyrics: parse LRC format [MM:SS.xx] line
  # Display with real-time highlighting based on mpv time-pos
  tput civis 2>/dev/null
  local cleanup_done=0
  _lyrics_cleanup() {
    [[ $cleanup_done -eq 0 ]] && { cleanup_done=1; tput cnorm 2>/dev/null; printf '\n'; }
  }
  trap '_lyrics_cleanup' INT TERM EXIT

  echo ""
  echo "  ${C}♪ ${title}${X}  ${DIM}(synced — q to exit)${X}"
  echo ""

  # Parse LRC into arrays: timestamps (seconds) and lines
  local -a lrc_times lrc_lines
  local prev_line
  while IFS= read -r line; do
    if echo "$line" | grep -qE '^\[[0-9]+:[0-9]+\.[0-9]+\]'; then
      local ts; ts=$(echo "$line" | grep -oE '^\[[0-9]+:[0-9]+\.[0-9]+\]' | tr -d '[]')
      local mm ss
      mm=$(echo "$ts" | cut -d: -f1 | sed 's/^0*//' ); mm=${mm:-0}
      ss=$(echo "$ts" | cut -d: -f2)
      local total_s; total_s=$(awk "BEGIN{printf \"%d\", $mm*60+$ss}")
      local ltext; ltext=$(echo "$line" | sed 's/^\[[^]]*\]//' | sed 's/^[[:space:]]*//')
      lrc_times+=("$total_s")
      lrc_lines+=("$ltext")
    fi
  done <<< "$lrc"

  local total=${#lrc_times[@]}
  (( total == 0 )) && { _warn "could not parse synced lyrics"; tput cnorm 2>/dev/null; return; }

  local last_idx=-1
  local tw; tw=$(tput cols 2>/dev/null || echo 80)

  while true; do
    local pos; pos=$(_get time-pos 2>/dev/null)
    [[ -z "$pos" ]] && break
    local pos_i; pos_i=$(printf '%.0f' "$pos" 2>/dev/null || echo 0)

    # Find current lyric line
    local cur_idx=0
    local i=1
    while [[ $i -le $total ]]; do
      if (( lrc_times[$i] <= pos_i )); then
        cur_idx=$i
      fi
      i=$(( i + 1 ))
    done

    if (( cur_idx != last_idx )); then
      last_idx=$cur_idx
      clear 2>/dev/null || printf '\033[2J\033[H'
      echo ""
      echo "  ${C}♪ ${title}${X}  ${DIM}(synced — q to exit)${X}"
      echo ""

      # Show context: 3 before, current, 3 after
      local ctx_start=$(( cur_idx - 3 ))
      local ctx_end=$(( cur_idx + 4 ))
      (( ctx_start < 1 )) && ctx_start=1
      (( ctx_end > total )) && ctx_end=$total

      local j=$ctx_start
      while (( j <= ctx_end )); do
        local lyric_line="${lrc_lines[$j]}"
        if (( j == cur_idx )); then
          printf "  ${G}${BOLD}▶ %-${tw}s${X}\n" "$lyric_line"
        else
          printf "  ${DIM}  %-${tw}s${X}\n" "$lyric_line"
        fi
        j=$(( j + 1 ))
      done
      echo ""
      printf "  ${DIM}[%d:%02d]  q=quit  bar=back to progress bar${X}\n" \
        "$(( pos_i / 60 ))" "$(( pos_i % 60 ))"
    fi

    local key
    if read -r -s -k1 -t 0.3 key 2>/dev/null; then
      [[ "$key" == "q" || "$key" == "Q" || "$key" == $'\e' ]] && break
    fi
  done

  _lyrics_cleanup
  trap - INT TERM EXIT
}
