#!/usr/bin/env bash
# mox lib/playback.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── do_play ─────────────────────────────────────────────────────
do_play() {
  _start
  _check_deps
  local url

  if _is_local_file "${1:-}"; then
    url="$1"
    [[ -f "$url" ]] || { _err "file not found: $url"; return 1; }
    _info "loading local file..."
  elif [[ "${1:-}" =~ ^https?:// ]]; then
    # Direct URL - skip interactive picker (needed for UXI)
    url="$1"
    _info "loading URL..."
  else
    url=$(_pick "${1:-}") || return 1
  fi

  [ -z "$url" ] && { _warn "cancelled"; return; }

  _silent '{"command":["playlist-clear"]}'
  _info "buffering..."
  _ipc_loadfile "$url" "replace"

  # v5-A: _wait_title gives extra time for YouTube URLs (yt-dlp metadata resolution)
  local title; title=$(_wait_title "$url" 60)
  _ok "▶  ${title:-unknown}"
  _log_history "${title:-unknown}" "$(_clean_url "$url")"
  _queue_snapshot
  # v5-R: auto-DJ check after play (background, non-blocking)
  (_autodj_check) &
  disown $! 2>/dev/null
}

# ── do_replay ───────────────────────────────────────────────────
do_replay() {
  [ -s "$HISTORY_FILE" ] || { _warn "history is empty — nothing to replay"; return 1; }

  # Last entry is the most recent: grab its URL (3rd tab-field)
  local last_url last_title
  last_url=$(tail -1 "$HISTORY_FILE" | awk -F'\t' '{print $3}')
  last_title=$(tail -1 "$HISTORY_FILE" | awk -F'\t' '{print $2}')

  [ -z "$last_url" ] && { _warn "could not read last history entry"; return 1; }

  _start
  _silent '{"command":["playlist-clear"]}'
  _info "replaying: ${last_title:-$last_url}..."
  _ipc_loadfile "$last_url" "replace"

  local title; title=$(_wait_title "$last_url" 60)
  _ok "▶  ${title:-${last_title:-unknown}}"
  _log_history "${title:-${last_title:-unknown}}" "$(_clean_url "$last_url")"
  _queue_snapshot
}

# ── do_add_next ─────────────────────────────────────────────────
do_add_next() {
  _start
  _check_deps
  local url

  if _is_local_file "${1:-}"; then
    url="$1"
    [[ -f "$url" ]] || { _err "file not found: $url"; return 1; }
  elif [[ "${1:-}" =~ ^https?:// ]]; then
    # Direct URL - skip interactive picker (needed for UXI)
    url="$1"
  else
    url=$(_pick "${1:-}") || return 1
  fi

  [ -z "$url" ] && { _warn "cancelled"; return; }

  # Get current playing index (0-based), insert at current+1
  local cur_idx; cur_idx=$(_get playlist-playing-pos)
  cur_idx=$(printf '%s' "${cur_idx:-0}" | tr -cd '0-9')
  cur_idx="${cur_idx:-0}"
  local insert_pos=$(( cur_idx + 1 ))

  _ipc_loadfile "$url" "append"
  # Move newly appended track to insert_pos
  local pl_count
  pl_count=$(_cmd '{"command":["get_property","playlist"]}' | "$JQ" '.data|length' 2>/dev/null)
  pl_count=$(printf '%s' "${pl_count:-0}" | tr -cd '0-9')
  pl_count="${pl_count:-0}"
  local last_idx=$(( pl_count - 1 ))
  if [[ "$last_idx" -gt "$insert_pos" ]] 2>/dev/null; then
    _silent "{\"command\":[\"playlist-move\",${last_idx},${insert_pos}]}"
  fi
  _ok "➕ added to play next (position $((insert_pos + 1)))"
  _queue_snapshot
}

# ── do_add ──────────────────────────────────────────────────────
do_add() {
  _start
  _check_deps
  local url

  if _is_local_file "${1:-}"; then
    url="$1"
    [[ -f "$url" ]] || { _err "file not found: $url"; return 1; }
  elif [[ "${1:-}" =~ ^https?:// ]]; then
    # Direct URL - skip interactive picker (needed for UXI)
    url="$1"
  else
    url=$(_pick "${1:-}") || return 1
  fi

  [ -z "$url" ] && { _warn "cancelled"; return; }

  local existing
  existing=$(_cmd '{"command":["get_property","playlist"]}' \
    | "$JQ" -r '.data[].filename' 2>/dev/null | grep -cF "$url" 2>/dev/null)
  # Sanitize: strip non-digits, default to 0 if empty or non-numeric
  existing=$(printf '%s' "${existing:-0}" | tr -cd '0-9')
  existing="${existing:-0}"
  if [[ "$existing" -gt 0 ]] 2>/dev/null; then
    _warn "already in queue — use -f to force add"
    return
  fi

  _ipc_loadfile "$url" "append-play"
  _ok "➕ added to queue"
  _queue_snapshot
}

# ── do_add_force ────────────────────────────────────────────────
do_add_force() {
  _start
  _check_deps
  local url

  if _is_local_file "${1:-}"; then
    url="$1"
    [[ -f "$url" ]] || { _err "file not found: $url"; return 1; }
  else
    url=$(_pick "${1:-}") || return 1
  fi

  [ -z "$url" ] && { _warn "cancelled"; return; }
  _ipc_loadfile "$url" "append-play"
  _ok "➕ force-added to queue"
  _queue_snapshot
}

# ── do_pause ────────────────────────────────────────────────────
do_pause() {
  _need
  _silent '{"command":["cycle","pause"]}'
  local p; p=$(_get pause)
  [ "$p" = "true" ] && _info "⏸  paused" || _info "▶  resumed"
}

# ── do_next ─────────────────────────────────────────────────────
do_next() {
  _need
  _silent '{"command":["playlist-next"]}'
  local title; title=$(_wait_prop media-title 20)
  [[ -z "$title" || "$title" == *"watch?v="* ]] && { sleep 1; title=$(_get media-title); }
  [[ -n "$title" ]] && _notify_track "$title"
  _ok "⏭  ${title:-end of queue}"
  (_autodj_check) &
  disown $! 2>/dev/null
}

# ── do_prev ─────────────────────────────────────────────────────
do_prev() {
  _need
  _silent '{"command":["playlist-prev"]}'
  local title; title=$(_wait_prop media-title 20)
  [[ -n "$title" ]] && _notify_track "$title"
  _ok "⏮  ${title:-beginning of queue}"
}

# ── do_stop ─────────────────────────────────────────────────────
do_stop() {
  _txt_kill_bg_job
  _sleep_timer_cancel

  # Persist volume/speed before killing
  if [[ -S "$SOCKET" ]]; then
    # Ensure JQ is initialized
    _ensure_bin JQ jq
    if [[ -n "$JQ" ]]; then
      local v s
      v=$(_cmd '{"command":["get_property","volume"]}' 2>/dev/null | "$JQ" -r '.data // empty')
      s=$(_cmd '{"command":["get_property","speed"]}' 2>/dev/null | "$JQ" -r '.data // empty')
      [[ -n "$v" && -n "$s" ]] && printf 'volume=%s\nspeed=%s\n' "$v" "$s" > "$VOLUME_SPEED_STATE" 2>/dev/null
    fi
  fi

  if [[ -f "$MPV_PID_FILE" ]]; then
    local pid; pid=$(cat "$MPV_PID_FILE" 2>/dev/null)
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null
      for i in $(seq 1 20); do
        sleep 0.1
        kill -0 "$pid" 2>/dev/null || break
      done
      kill -9 "$pid" 2>/dev/null
    fi
    rm -f "$MPV_PID_FILE"
  else
    _warn "mpv PID file missing; not killing by process pattern"
  fi
  rm -f "$SOCKET"
  # Only remove lock if we own it or no lock exists
  if [[ -f "$LOCK_FILE" ]]; then
    local lock_pid; lock_pid=$(cat "$LOCK_FILE" 2>/dev/null)
    [[ "$lock_pid" = "$$" || -z "$lock_pid" ]] && { rm -f "$LOCK_FILE"; rmdir "$LOCK_FILE_D" 2>/dev/null; }
  else
    rmdir "$LOCK_FILE_D" 2>/dev/null
  fi
  _ok "stopped"
}

# ── do_start ────────────────────────────────────────────────────
do_start() {
  _start && _ok "daemon ready"
}

# ── do_auto_restart_toggle ──────────────────────────────────────
do_auto_restart_toggle() {
  local current_value="${AUTO_RESTART_DAEMON:-true}"
  
  if [[ "$current_value" == "true" ]]; then
    # Disable auto-restart
    if grep -q "^AUTO_RESTART_DAEMON=" "$CONFIG_FILE" 2>/dev/null; then
      if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' 's/^AUTO_RESTART_DAEMON=.*/AUTO_RESTART_DAEMON=false/' "$CONFIG_FILE"
      else
        sed -i 's/^AUTO_RESTART_DAEMON=.*/AUTO_RESTART_DAEMON=false/' "$CONFIG_FILE"
      fi
    else
      echo "AUTO_RESTART_DAEMON=false" >> "$CONFIG_FILE"
    fi
    _ok "auto-restart disabled — daemon will show error message when unresponsive"
  else
    # Enable auto-restart
    if grep -q "^AUTO_RESTART_DAEMON=" "$CONFIG_FILE" 2>/dev/null; then
      if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' 's/^AUTO_RESTART_DAEMON=.*/AUTO_RESTART_DAEMON=true/' "$CONFIG_FILE"
      else
        sed -i 's/^AUTO_RESTART_DAEMON=.*/AUTO_RESTART_DAEMON=true/' "$CONFIG_FILE"
      fi
    else
      echo "AUTO_RESTART_DAEMON=true" >> "$CONFIG_FILE"
    fi
    _ok "auto-restart enabled — daemon will automatically restart when unresponsive"
  fi
  
  
  # Reload configuration (through sandbox — never source directly)
  _load_config
}

# ── do_seek ─────────────────────────────────────────────────────
do_seek() {
  # Validate input first
  [ -z "${1:-}" ] && { _err "usage: mox seek [+N | -N | N | MM:SS]"; return 1; }
  
  local input="$1"
  local secs="$input"

  # Validate time format first
  if echo "$input" | grep -qE '^[+-]?[0-9]+:[0-9]{2}$'; then
    local sign="" ts="$input"
    [[ "$input" == +* ]] && { sign="+"; ts="${input#+}"; }
    [[ "$input" == -* ]] && { sign="-"; ts="${input#-}"; }
    local m s
    m=$(echo "$ts" | cut -d: -f1 | sed 's/^0*//'); m=${m:-0}
    s=$(echo "$ts" | cut -d: -f2 | sed 's/^0*//'); s=${s:-0}
    # Validate time values
    (( s >= 60 )) && { _err "invalid seek value: $input"; return 1; }
    secs="${sign}$(( m * 60 + s ))"
  fi

  # Validate the final value format
  case "$secs" in
    +*)
      local n="${secs#+}"
      [[ "$n" =~ ^[0-9]+$ ]] || { _err "invalid seek value: $input"; return 1; }
      ;;
    -*)
      local n="${secs#-}"
      [[ "$n" =~ ^[0-9]+$ ]] || { _err "invalid seek value: $input"; return 1; }
      ;;
    *)
      [[ "$secs" =~ ^[0-9]+$ ]] || { _err "invalid seek value: $input"; return 1; }
      ;;
  esac

  _need
  case "$secs" in
    +*)
      local n="${secs#+}"
      _silent "{\"command\":[\"seek\",\"${n}\",\"relative\"]}"
      ;;
    -*)
      local n="${secs#-}"
      _silent "{\"command\":[\"seek\",\"-${n}\",\"relative\"]}"
      ;;
    *)
      [[ "$secs" =~ ^[0-9]+$ ]] || { _err "invalid seek value: $input"; return 1; }
      _silent "{\"command\":[\"seek\",\"$secs\",\"absolute\"]}"
      ;;
  esac

  sleep 0.1
  local pos; pos=$(_get time-pos)
  local dur; dur=$(_get duration)
  pos=$(echo "$pos" | awk '{printf "%d:%02d",$1/60,$1%60}' 2>/dev/null)
  dur=$(echo "$dur" | awk '{printf "%d:%02d",$1/60,$1%60}' 2>/dev/null)

  # v5: mini progress bar after seek
  local pos_i dur_i pct bar_fill bar_empty
  pos_i=$(echo "$pos" | awk -F: '{print $1*60+$2}' 2>/dev/null || echo 0)
  pos_i=$(printf '%s' "${pos_i:-0}" | tr -cd '0-9'); pos_i="${pos_i:-0}"
  dur_i=$(echo "$dur" | awk -F: '{print $1*60+$2}' 2>/dev/null || echo 1)
  dur_i=$(printf '%s' "${dur_i:-1}" | tr -cd '0-9'); dur_i="${dur_i:-1}"
  [[ "$dur_i" -lt 1 ]] 2>/dev/null && dur_i=1
  pct=$(( pos_i * 100 / dur_i ))
  bar_fill=$(printf '%*s' "$(( pct * 20 / 100 ))" '' | tr ' ' '━')
  bar_empty=$(printf '%*s' "$(( 20 - pct * 20 / 100 ))" '' | tr ' ' '─')
  _info "⏩ ${pos} / ${dur}  [${bar_fill}${bar_empty}] ${pct}%"
}

# ── do_speed ────────────────────────────────────────────────────
do_speed() {
  # Validate input first
  case "${1:-}" in
    +|-|r)
      # These are valid, check daemon later
      ;;
    '')  
      { _err "usage: mox speed [0.25-4.0 | + | - | r]"; return 1; } 
      ;;
    *)
      [[ "${1:-}" =~ ^[0-9]+(\.[0-9]+)?$ ]] || { _err "usage: mox speed [0.25-4.0 | + | - | r]"; return 1; }
      (( $(echo "$1 < 0.25" | awk '{print ($1<0.25)?1:0}') )) && { _err "min speed is 0.25"; return 1; }
      (( $(echo "$1 > 4.0"  | awk '{print ($1>4.0)?1:0}') )) && { _err "max speed is 4.0"; return 1; }
      ;;
  esac
  
  _need
  case "${1:-}" in
    +)  _silent '{"command":["multiply","speed",1.1]}' ;;
    -)  _silent '{"command":["multiply","speed",0.909090909]}' ;;
    r)  _silent '{"command":["set_property","speed",1.0]}'; _info "speed: 1.0x"; return ;;
    *)
      _silent "{\"command\":[\"set_property\",\"speed\",$1]}"
      ;;
  esac
  local sp; sp=$(_get speed)
  _info "speed: $(echo "$sp" | awk '{printf "%.3fx",$1}')"
}

# ── do_hp ───────────────────────────────────────────────────────
do_hp() {
  _need
  [[ -z "${AUDIO_DEVICE_HEADPHONES:-}" ]] && { _err "headphone device not configured — set AUDIO_DEVICE_HEADPHONES in $CONFIG_FILE"; return 1; }
  _silent "{\"command\":[\"set_property\",\"audio-device\",\"$AUDIO_DEVICE_HEADPHONES\"]}"
  _ok "🎧 headphones"
}

# ── do_sp ───────────────────────────────────────────────────────
do_sp() {
  _need
  [[ -z "${AUDIO_DEVICE_SPEAKERS:-}" ]] && { _err "speaker device not configured — set AUDIO_DEVICE_SPEAKERS in $CONFIG_FILE"; return 1; }
  _silent "{\"command\":[\"set_property\",\"audio-device\",\"$AUDIO_DEVICE_SPEAKERS\"]}"
  _ok "🔊 speakers"
}

# ── do_shuffle ──────────────────────────────────────────────────
do_shuffle() { _need; _silent '{"command":["playlist-shuffle"]}'; _ok "🔀 shuffled"; }


# ── do_repeat ───────────────────────────────────────────────────
do_repeat() {
  _need
  _silent '{"command":["cycle","loop-playlist"]}'
  local state; state=$(_get loop-playlist)
  _info "🔁 repeat: ${state}"
}

# ── do_repeat_one ───────────────────────────────────────────────
do_repeat_one() {
  _need
  _silent '{"command":["cycle","loop-file"]}'
  local state; state=$(_get loop-file)
  _info "🔂 repeat-one: ${state}"
}

# ── do_clear ────────────────────────────────────────────────────
do_clear() { _need; _silent '{"command":["playlist-clear"]}'; _ok "🗑  queue cleared"; }


# ── do_cast ─────────────────────────────────────────────────────
do_cast() {
  _need
  local url; url=$(_get path)
  [[ -z "$url" ]] && url=$(_get filename)
  [[ -z "$url" ]] && { _err "nothing to cast"; return 1; }

  if command -v castnow >/dev/null 2>&1; then
    _info "casting with castnow..."
    castnow "$url"
    return $?
  fi

  if command -v mkchromecast >/dev/null 2>&1; then
    _info "casting with mkchromecast..."
    mkchromecast --source-url "$url"
    return $?
  fi

  if [[ "$OS" == "mac" ]] && command -v open >/dev/null 2>&1; then
    _info "opening current media in QuickTime Player; use macOS AirPlay from there."
    open -a "QuickTime Player" "$url" 2>/dev/null && return 0
  fi

  if [[ "$OS" == "mac" ]] && command -v pbcopy >/dev/null 2>&1; then
    printf '%s' "$url" | pbcopy
    _ok "copied media URL to clipboard; install castnow for direct Chromecast support"
    return 0
  elif command -v xclip >/dev/null 2>&1; then
    printf '%s' "$url" | xclip -selection clipboard
    _ok "copied media URL to clipboard; install castnow or mkchromecast for direct casting"
    return 0
  fi

  _warn "install castnow or mkchromecast for direct casting"
  echo "$url"
}

# ── do_smart ────────────────────────────────────────────────────
do_smart() {
  _need
  local title; title=$(_get media-title)
  [[ -z "$title" ]] && { _err "nothing playing — start a track first"; return 1; }
  _info "building smart queue from: $title"
  local results
  results=$(_do_search "${title} similar songs" 8) || { _err "smart search failed"; return 1; }
  local added=0
  echo "$results" | awk -F ' \| ' '{print $NF}' | while IFS= read -r url; do
    [[ -z "$url" ]] && continue
    _ipc_loadfile "$url" "append-play"
    added=$(( added + 1 ))
    (( added >= 3 )) && break
  done
  _queue_snapshot
  _ok "smart queue added up to 3 related tracks"
}
