#!/usr/bin/env bash
# mox lib/playlist.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── do_save ─────────────────────────────────────────────────────
do_save() {
  [ -z "${1:-}" ] && { _err "usage: mox save <n>"; return 1; }
  _need
  local name="$1"
  name=$(printf '%s' "$name" | tr ' ' '_' | tr -cd '[:alnum:]_-')
  [ -z "$name" ] && { _err "invalid playlist name"; return 1; }
  local file="$PLAYLIST_DIR/${name}.m3u"
  local tmpf; tmpf=$(mktemp "$PLAYLIST_DIR/${name}.XXXXXX")
  local count=0
  local raw_playlist; raw_playlist=$(_cmd '{"command":["get_property","playlist"]}')
  local urls; urls=$(echo "$raw_playlist" | "$JQ" -r '.data[].filename' 2>/dev/null)
  if [[ -z "$urls" ]]; then
    rm -f "$tmpf"; _err "queue is empty — nothing to save"; return 1
  fi
  while IFS= read -r url; do
    [ -z "$url" ] && continue
    printf '%s\n' "$(_clean_url "$url")" >> "$tmpf"
    count=$(( count + 1 ))
  done <<< "$urls"
  if [[ $count -eq 0 ]]; then
    rm -f "$tmpf"; _err "queue is empty — nothing to save"; return 1
  fi
  mv "$tmpf" "$file"
  _ok "saved: ${name}  (${count} tracks)"
}

# ── do_load ─────────────────────────────────────────────────────
do_load() {
  [ -z "${1:-}" ] && { _err "usage: mox load <n>"; return 1; }
  local f="$PLAYLIST_DIR/${1}.m3u"
  [ -f "$f" ] || { _err "playlist not found: $1"; return 1; }

  local valid_urls=0
  local total_lines=0
  while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    total_lines=$((total_lines + 1))
    if _playlist_entry_valid "$line"; then
      valid_urls=$((valid_urls + 1))
    fi
  done < "$f"

  if [ $total_lines -eq 0 ]; then
    _err "playlist is empty: $1"
    return 1
  fi

  if [ $valid_urls -eq 0 ]; then
    _err "playlist contains no valid URLs: $1"
    return 1
  fi

  if [[ -n "${MOX_TEST_MODE:-}" ]]; then
    _ok "loaded: $1  (${valid_urls} tracks)"
    return 0
  fi

  _start
  _silent '{"command":["playlist-clear"]}'
  local _existing_urls
  _existing_urls=$(_cmd '{"command":["get_property","playlist"]}' \
    | "$JQ" -r '.data[].filename // empty' 2>/dev/null || echo "")
  local count=0
  while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    _playlist_entry_valid "$line" || continue

    if echo "$_existing_urls" | grep -qF "$line" 2>/dev/null; then
      _warn "skipping duplicate: $(basename "$line")"
      continue
    fi
    _ipc_loadfile "$line" "append-play"
    _existing_urls="${_existing_urls}"$'\n'"${line}"
    count=$(( count + 1 ))
  done < "$f"
  _ok "loaded: $1  (${count} tracks)"
  _info "first track buffering... use: mox now"
  _queue_snapshot
}

# ── do_playlists ────────────────────────────────────────────────
do_playlists() {
  # Set nullglob to avoid errors when no .m3u files exist
  setopt nullglob 2>/dev/null || shopt -s nullglob 2>/dev/null
  echo ""
  echo "  ${C}saved playlists:${X}"
  local found=0
  for f in "$PLAYLIST_DIR"/*.m3u; do
    # Check if glob matched any files (avoid processing literal *.m3u)
    [ -f "$f" ] || break
    local base="${f##*/}"
    local name="${base%.m3u}"
    local count=0 line
    while IFS= read -r line; do
      [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
      count=$((count + 1))
    done < "$f"
    echo "  ∙ ${W}${name}${X}  (${count} tracks)"
    found=1
  done
  [ $found -eq 0 ] && echo "  (none yet — use: mox save <n>)"
  echo ""
}

# ── do_playlist_del ─────────────────────────────────────────────
do_playlist_del() {
  [ -z "${1:-}" ] && { _err "usage: mox pldel <n>"; return 1; }
  # Sanitize name the same way do_save does — strip everything except alnum, _, -
  local name
  name=$(printf '%s' "$1" | tr -cd '[:alnum:]_-')
  [[ -z "$name" ]] && { _err "invalid playlist name"; return 1; }
  local f="$PLAYLIST_DIR/${name}.m3u"
  [ -f "$f" ] || { _err "not found: $1"; return 1; }
  # Defense-in-depth: confirm the resolved path stays inside PLAYLIST_DIR
  local real_f real_dir
  real_f=$(realpath "$f" 2>/dev/null || echo "$f")
  real_dir=$(realpath "$PLAYLIST_DIR" 2>/dev/null || echo "$PLAYLIST_DIR")
  [[ "$real_f" == "$real_dir"/* ]] || { _err "invalid path"; return 1; }
  printf "${Y}Delete playlist '%s'? [y/N] ${X}" "$name"
  read -r ans
  [[ "$ans" =~ ^[Yy]$ ]] || { _warn "cancelled"; return; }
  rm "$f"
  _ok "deleted playlist: $name"
}

# ── do_dl ───────────────────────────────────────────────────────
do_dl() {
  _check_deps
  [ -z "${1:-}" ] && { _err "usage: mox dl \"song query\""; return 1; }
  _info "searching to download..."
  local url; url=$(_pick "$1") || return 1
  [ -z "$url" ] && { _warn "cancelled"; return; }
  _info "downloading to $DOWNLOADS_DIR ..."
  echo ""
  "$YTDLP" "$url" \
    --extract-audio \
    --audio-format mp3 \
    --audio-quality 0 \
    --embed-thumbnail \
    --add-metadata \
    --embed-metadata \
    --output "$DOWNLOADS_DIR/%(title)s.%(ext)s" \
    --no-playlist \
    --progress \
    --console-title=no \
    --no-warnings
  local rc=$?
  echo ""
  if [[ $rc -ne 0 ]]; then
    _err "download failed (yt-dlp exit $rc) — check: mox log"
    return 1
  fi
  _ok "download complete → $DOWNLOADS_DIR"
}

# ── do_dl_list ──────────────────────────────────────────────────
do_dl_list() {
  # Set nullglob to avoid errors when no audio files exist
  setopt nullglob 2>/dev/null || shopt -s nullglob 2>/dev/null
  echo ""
  echo "  ${C}downloads:${X}  $DOWNLOADS_DIR"
  echo ""
  local found=0
  for ext in mp3 m4a opus; do
    for f in "$DOWNLOADS_DIR"/*.$ext; do
      [ -f "$f" ] || continue
      echo "  ∙ $(basename "$f")"
      found=1
    done
  done
  [[ $found -eq 0 ]] && echo "  (none yet — use: mox dl \"song name\")"
  echo ""
}

# ── do_import ───────────────────────────────────────────────────
do_import() {
  [ -z "${1:-}" ] && { _err "usage: mox import \"https://youtube.com/playlist?list=...\""; return 1; }
  _info "fetching playlist metadata (this may take a moment)..."
  local tmpf; tmpf=$(mktemp "$PLAYLIST_DIR/import.XXXXXX")
  "$YTDLP" "$1" \
    --flat-playlist \
    --print "%(webpage_url)s" \
    --no-warnings 2>/dev/null > "$tmpf"
  local count; count=$(wc -l < "$tmpf" | tr -d ' ')
  if [[ $count -eq 0 ]]; then
    rm -f "$tmpf"
    _err "no tracks found — is the URL correct and the playlist public?"
    return 1
  fi
  printf "${C}Save as playlist name: ${X}"
  read -r pname
  pname=$(printf '%s' "$pname" | tr ' ' '_' | tr -cd '[:alnum:]_-')
  [ -z "$pname" ] && { rm -f "$tmpf"; _err "invalid name"; return 1; }
  if [[ -f "$PLAYLIST_DIR/${pname}.m3u" ]]; then
    local existing_count; existing_count=$(grep -cvE '^\s*(#|$)' "$PLAYLIST_DIR/${pname}.m3u" 2>/dev/null || echo 0)
    printf "${Y}Playlist '%s' already exists (%s tracks). Overwrite? [y/N] ${X}" "$pname" "$existing_count"
    local ans; read -r ans
    if [[ ! "$ans" =~ ^[Yy]$ ]]; then
      rm -f "$tmpf"; _warn "import cancelled"; return 1
    fi
  fi
  mv "$tmpf" "$PLAYLIST_DIR/${pname}.m3u"
  _ok "imported: ${pname}  (${count} tracks)  →  mox load ${pname}"
}

# ── do_art ──────────────────────────────────────────────────────
do_art() {
  _need
  local url; url=$(_get path)
  [ -z "$url" ] && { _warn "nothing playing"; return; }

  if [[ -z "$CHAFA" || ! -x "$CHAFA" ]]; then
    _warn "chafa not installed — install with: brew install chafa  or  apt install chafa"
    return
  fi
  if [[ -z "$CURL" || ! -x "$CURL" ]]; then
    _warn "curl required for album art"; return
  fi

  local title; title=$(_get media-title)
  local vid; vid=$(echo "$url" | grep -oE '[?&]v=([A-Za-z0-9_-]{11})' | head -1 | cut -d= -f2)

  if [[ -z "$vid" ]]; then
    vid=$(echo "$url" | grep -oE '/shorts/([A-Za-z0-9_-]{11})' | head -1 | grep -oE '[A-Za-z0-9_-]{11}$')
  fi

  if [[ -z "$vid" ]]; then
    _warn "album art only available for YouTube tracks"
    return
  fi

  local thumb_url="https://img.youtube.com/vi/${vid}/maxresdefault.jpg"
  local thumb_file; thumb_file=$(mktemp "/tmp/m_art_XXXXXX.jpg")

  _info "fetching album art..."
  if ! "$CURL" -sf --max-time 8 "$thumb_url" -o "$thumb_file" 2>/dev/null; then
    # Fall back to lower resolution
    thumb_url="https://img.youtube.com/vi/${vid}/hqdefault.jpg"
    "$CURL" -sf --max-time 8 "$thumb_url" -o "$thumb_file" 2>/dev/null || {
      rm -f "$thumb_file"; _err "could not fetch album art"; return 1
    }
  fi

  echo ""
  echo "  ${C}♪ ${title}${X}"
  echo ""
  "$CHAFA" --size "$(tput cols)x20" "$thumb_file" 2>/dev/null
  echo ""
  rm -f "$thumb_file"
}

# ── do_bookmark ─────────────────────────────────────────────────
do_bookmark() {
  _need
  local title; title=$(_get media-title)
  [ -z "$title" ] && { _warn "nothing playing"; return; }

  local pos; pos=$(_get time-pos | awk '{printf "%d:%02d",$1/60,$1%60}' 2>/dev/null)
  local url; url=$(_get path)

  local name="${1:-}"
  if [[ -z "$name" ]]; then
    name="$(date '+%Y%m%d_%H%M')_${title:0:30}"
    name=$(printf '%s' "$name" | tr ' /' '_' | tr -cd '[:alnum:]_-')
  fi

  # Save queue snapshot with this name
  local bm_dir="$DATA_DIR/bookmarks_dir"
  mkdir -p "$bm_dir"
  _queue_snapshot
  cp "$QUEUE_SNAPSHOT" "$bm_dir/${name}.m3u" 2>/dev/null

  # Log the bookmark entry
  printf '%s\t%s\t%s\t%s\t%s\n' \
    "$(date '+%Y-%m-%d %H:%M')" "$name" "$title" "$pos" "$(_clean_url "$url")" \
    >> "$BOOKMARKS_FILE"

  _ok "📌 bookmark saved: ${name}  (${title} @ ${pos})"
}

# ── do_bookmarks ────────────────────────────────────────────────
do_bookmarks() {
  [ -s "$BOOKMARKS_FILE" ] || { _warn "no bookmarks yet — use: mox bookmark"; return; }
  echo ""
  echo "  ${C}📌 bookmarks:${X}"
  echo ""
  awk -F'\t' '{printf "  ∙ %s  |  %s @ %s\n", $2, $3, $4}' "$BOOKMARKS_FILE"
  echo ""
}

# ── do_bookmark_load ────────────────────────────────────────────
do_bookmark_load() {
  _check_deps
  [ -s "$BOOKMARKS_FILE" ] || { _warn "no bookmarks yet"; return; }
  local line
  line=$("$FZF" \
    --height 50% --reverse \
    --prompt "📌 bookmark > " \
    --header "ENTER to restore · ESC cancel" \
    --with-nth=2,3,4 --delimiter=$'\t' < "$BOOKMARKS_FILE")
  [ -z "$line" ] && { _warn "cancelled"; return; }

  local bm_name; bm_name=$(printf '%s' "$line" | awk -F'\t' '{print $2}')
  local bm_pos; bm_pos=$(printf '%s' "$line" | awk -F'\t' '{print $4}')
  local bm_dir="$DATA_DIR/bookmarks_dir"
  local bm_file="$bm_dir/${bm_name}.m3u"

  _start
  _silent '{"command":["playlist-clear"]}'

  if [[ -f "$bm_file" ]]; then
    while IFS= read -r url; do
      [ -z "$url" ] && continue
      _ipc_loadfile "$url" "append-play"
    done < "$bm_file"
    _ok "📌 restored queue from bookmark: $bm_name"
  else
    # Fallback: just play the URL
    local bm_url; bm_url=$(printf '%s' "$line" | awk -F'\t' '{print $5}')
    _ipc_loadfile "$bm_url" "replace"
    _ok "📌 restored track from bookmark: $bm_name"
  fi

  # Seek to saved position
  if [[ -n "$bm_pos" && "$bm_pos" != "0:00" ]]; then
    sleep 2  # wait for track to load
    local m s target_secs
    m=$(echo "$bm_pos" | cut -d: -f1 | sed 's/^0*//'); m=${m:-0}
    s=$(echo "$bm_pos" | cut -d: -f2 | sed 's/^0*//'); s=${s:-0}
    target_secs=$(( m * 60 + s ))
    _silent "{\"command\":[\"seek\",\"$target_secs\",\"absolute\"]}"
    _info "seeked to: $bm_pos"
  fi
}

# ── do_txt ──────────────────────────────────────────────────────
do_txt() {
  _check_deps
  # Set nullglob to avoid errors when no .txt files exist
  setopt nullglob 2>/dev/null || shopt -s nullglob 2>/dev/null
  local arg="${1:-}"
  local resume_flag="${2:-}"
  local chosen_file=""

  if [ -z "$arg" ]; then
    local files=()
    for f in "$TXTS_DIR"/*.txt; do
      [ -f "$f" ] && files+=("$f")
    done
    if [ ${#files[@]} -eq 0 ]; then
      _warn "no .txt files in $TXTS_DIR"
      _info "create one and drop it there — one song name per line"
      return
    fi
    local display=()
    for f in "${files[@]}"; do
      local n; n=$(grep -cvE '^\s*(#|$)' "$f" 2>/dev/null || echo 0)
      display+=("$(basename "$f" .txt)  (${n} songs)")
    done
    local picked
    picked=$(printf '%s\n' "${display[@]}" | "$FZF" \
      --height 50% --reverse \
      --prompt "📄 txt playlist > " \
      --header "ENTER to load · ESC cancel")
    [ -z "$picked" ] && { _warn "cancelled"; return; }
    local fname; fname=$(echo "$picked" | awk '{print $1}')
    chosen_file="$TXTS_DIR/${fname}.txt"
  else
    chosen_file=$(_txt_resolve "$arg")
    [ -z "$chosen_file" ] && { _err "txt file not found: $arg  (looked in $TXTS_DIR)"; return 1; }
  fi

  _txt_read_lines "$chosen_file"
  [ ${#TXT_LINES[@]} -eq 0 ] && { _err "txt file is empty or has only comments: $chosen_file"; return 1; }

  # In test mode, just show what would be processed without starting daemon
  if [[ -n "${MOX_TEST_MODE:-}" ]]; then
    local fname_display; fname_display=$(basename "$chosen_file" .txt)
    _info "txt playlist: $fname_display  (${#TXT_LINES[@]} songs)"
    return 0
  fi

  _start

  # v5-U: --resume flag restores last position
  local start_idx=0
  if [[ "$resume_flag" == "--resume" || "$resume_flag" == "-r" ]]; then
    _txt_state_read
    if [[ "$TXT_ACTIVE_FILE" == "$chosen_file" && $TXT_ACTIVE_IDX -gt 0 ]]; then
      start_idx=$TXT_ACTIVE_IDX
      _info "resuming txt playlist at position $((start_idx + 1))"
    fi
  fi

  local fname_display; fname_display=$(basename "$chosen_file" .txt)
  _info "loading txt playlist: ${fname_display}  (${#TXT_LINES[@]} songs)"

  _txt_kill_bg_job
  _txt_state_write "$chosen_file" "$start_idx"
  _silent '{"command":["playlist-clear"]}'

  # Play first (or resumed) track
  local first_query="${TXT_LINES[$(( start_idx + 1 ))]}"
  local first_url
  first_url=$(_txt_search_and_play_line "$first_query")
  if [ -z "$first_url" ]; then
    _warn "could not find: ${first_query} — skipping"
  else
    _ipc_loadfile "$first_url" "replace"
  fi

  # Capture variables for bg job
  local _bg_socat="$SOCAT" _bg_socket="$SOCKET" _bg_jq="$JQ"
  local _bg_ytdlp="$YTDLP" _bg_cache_dir="$CACHE_DIR" _bg_cache_ttl="$CACHE_TTL"
  local _bg_search_n="${SEARCH_RESULTS:-5}"
  (( _bg_search_n > 5 )) && _bg_search_n=5
  local _bg_gen; _bg_gen=$(cat "$TXT_BG_GEN_FILE" 2>/dev/null || echo 0)
  local _bg_gen_file="$TXT_BG_GEN_FILE"
  local _bg_youtube_api_key="$YOUTUBE_API_KEY"
  local _bg_invidious_host="$INVIDIOUS_HOST"
  local _bg_curl="$CURL"

  # v5-N — parallel resolution: workers write to numbered files; parent reads in order.
  # Semaphore counter file for throttle (pids array in subshell doesn't work).
  local txt_tmpdir; txt_tmpdir=$(mktemp -d "$DATA_DIR/txt_resolve.XXXXXX")
  local sem_file="$txt_tmpdir/sem"
  local progress_file="$TXT_PROGRESS_FILE"
  echo 0 > "$sem_file"
  echo "0/${#TXT_LINES[@]}" > "$progress_file"

  (
    set +v +x  # Disable verbose/debug output in subshell
    local socat="$_bg_socat" socket="$_bg_socket" jq="$_bg_jq"
    local ytdlp="$_bg_ytdlp" cache_dir="$_bg_cache_dir" cache_ttl="$_bg_cache_ttl"
    local my_gen="$_bg_gen" gen_file="$_bg_gen_file"
    local search_n="$_bg_search_n"
    local yt_api_key="$_bg_youtube_api_key"
    local inv_host="$_bg_invidious_host"
    local curl_bin="$_bg_curl"
    local tmpdir="$txt_tmpdir" sem="$sem_file" progress="$progress_file"

    _sem_add() {
      local delta="$1" lock="${sem}.lock"
      # Use flock(1) when available (Linux util-linux); fall back to mkdir on macOS.
      if command -v flock >/dev/null 2>&1; then
        (
          flock -x 9
          local val; val=$(cat "$sem" 2>/dev/null || echo 0)
          val=$(( val + delta ))
          (( val < 0 )) && val=0
          echo "$val" > "$sem"
        ) 9>"$lock"
      else
        local lockd="${sem}.lock.d"
        while ! mkdir "$lockd" 2>/dev/null; do sleep 0.02; done
        local val; val=$(cat "$sem" 2>/dev/null || echo 0)
        val=$(( val + delta ))
        (( val < 0 )) && val=0
        echo "$val" > "$sem"
        rmdir "$lockd" 2>/dev/null
      fi
    }

    _progress_add() {
      local lock="${progress}.lock"
      if command -v flock >/dev/null 2>&1; then
        (
          flock -x 9
          local done_count total_count
          IFS=/ read -r done_count total_count < "$progress"
          done_count=${done_count:-0}
          total_count=${total_count:-${#TXT_LINES[@]}}
          echo "$(( done_count + 1 ))/${total_count}" > "$progress"
        ) 9>"$lock"
      else
        local lockd="${progress}.lock.d"
        while ! mkdir "$lockd" 2>/dev/null; do sleep 0.02; done
        local done_count total_count
        IFS=/ read -r done_count total_count < "$progress"
        done_count=${done_count:-0}
        total_count=${total_count:-${#TXT_LINES[@]}}
        echo "$(( done_count + 1 ))/${total_count}" > "$progress"
        rmdir "$lockd" 2>/dev/null
      fi
    }

    _bg_search_one() {
      local query="$1"
      local key
      if [[ "$(uname -s)" = "Darwin" ]]; then
        key="${cache_dir}/$(printf '%s' "$query" | md5 -q 2>/dev/null).cache"
      else
        key="${cache_dir}/$(printf '%s' "$query" | md5sum 2>/dev/null | cut -c1-32).cache"
      fi
      [[ "$key" = "${cache_dir}/.cache" ]] && key="${cache_dir}/$(printf '%s' "$query" | md5sum 2>/dev/null | cut -c1-32).cache"

      # Check cache first
      if [ -f "$key" ] && [ $(( $(date +%s) - $(stat -c%Y "$key" 2>/dev/null || stat -f%m "$key" 2>/dev/null || echo 0) )) -lt "$cache_ttl" ]; then
        cat "$key"; return 0
      fi

      local results=""

      # Try YouTube Data API v3
      if [[ -n "$yt_api_key" && -n "$curl_bin" && -x "$curl_bin" ]]; then
        local enc_q; enc_q=$(printf '%s' "$query" | "$jq" -Rr '@uri' 2>/dev/null)
        local api_resp
        api_resp=$("$curl_bin" -sf --max-time 8 \
          "https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&videoCategoryId=10&maxResults=1&q=${enc_q}&key=${yt_api_key}" \
          2>/dev/null) || true
        if [[ -n "$api_resp" ]]; then
          local vid_id title_r
          vid_id=$(echo "$api_resp" | "$jq" -r '.items[0].id.videoId // empty' 2>/dev/null)
          title_r=$(echo "$api_resp" | "$jq" -r '.items[0].snippet.title // empty' 2>/dev/null)
          if [[ -n "$vid_id" ]]; then
            results="${title_r} |  | https://www.youtube.com/watch?v=${vid_id}"
          fi
        fi
      fi

      # Try Invidious
      if [[ -z "$results" && -n "$inv_host" && -n "$curl_bin" && -x "$curl_bin" ]]; then
        local enc_q; enc_q=$(printf '%s' "$query" | "$jq" -Rr '@uri' 2>/dev/null)
        local inv_resp
        inv_resp=$("$curl_bin" -sf --max-time 8 \
          "${inv_host}/api/v1/search?q=${enc_q}&type=video&fields=title,videoId&page=1" \
          2>/dev/null) || true
        if [[ -n "$inv_resp" ]]; then
          local vid_id title_r
          vid_id=$(echo "$inv_resp" | "$jq" -r '.[0].videoId // empty' 2>/dev/null)
          title_r=$(echo "$inv_resp" | "$jq" -r '.[0].title // empty' 2>/dev/null)
          if [[ -n "$vid_id" ]]; then
            results="${title_r} |  | https://www.youtube.com/watch?v=${vid_id}"
          fi
        fi
      fi

      # Fall back to yt-dlp
      if [[ -z "$results" ]]; then
        results=$("$ytdlp" "ytsearch${search_n}:${query}" \
          --print "%(title)s | %(duration_string)s | %(webpage_url)s" \
          --no-download --no-warnings 2>/dev/null | head -1)
      fi

      if [[ -n "$results" ]]; then
        echo "$results" > "$key"
        echo "$results"
      fi
    }

    # Spawn workers: each writes to tmpdir/$i; semaphore limits concurrency
    local i=$(( start_idx + 2 ))
    while [ $i -le ${#TXT_LINES[@]} ]; do
      local cur_gen
      cur_gen=$(cat "$gen_file" 2>/dev/null || echo 0)
      [ "$cur_gen" = "$my_gen" ] || { rm -rf "$tmpdir"; exit 0; }

      # Semaphore: wait until running < 4
      while true; do
        local running
        running=$(cat "$sem" 2>/dev/null || echo 0)
        [[ "$running" -lt 4 ]] && break
        sleep 0.05
      done
      _sem_add 1

      local query="${TXT_LINES[$i]}"
      (
        set +v +x  # Disable verbose/debug output in worker subshell
        local cur; cur=$(cat "$gen_file" 2>/dev/null || echo 0)
        [ "$cur" = "$my_gen" ] || { _sem_add -1; exit 0; }
        local result; result=$(_bg_search_one "$query")
        _sem_add -1
        _progress_add
        [ -z "$result" ] && exit 0
        local url
        url=$(echo "$result" | head -1 | awk -F ' \| ' '{print $NF}')
        [ -z "$url" ] && exit 0
        echo "$url" > "$tmpdir/$i"
      ) &

      i=$(( i + 1 ))
    done

    wait

    # Read results in order and append to mpv
    local j=$(( start_idx + 2 ))
    while [ $j -le ${#TXT_LINES[@]} ]; do
      [ "$(cat "$gen_file" 2>/dev/null || echo 0)" = "$my_gen" ] || break
      if [ -f "$tmpdir/$j" ]; then
        local url
        url=$(cat "$tmpdir/$j" 2>/dev/null)
        [ -n "$url" ] && {
          local json
          json=$("$jq" -cn --arg url "$url" '{"command":["loadfile",$url,"append"]}')
          echo "$json" | "$socat" - "$socket" >/dev/null 2>&1
        }
      fi
      j=$(( j + 1 ))
    done
    echo "done/${#TXT_LINES[@]}" > "$progress"
    rm -rf "$tmpdir"
  ) >/dev/null 2>&1 &

  local bg_pid=$!
  # v5-C: write PID file atomically BEFORE disown (tempfile swap)
  local tmpf_pid; tmpf_pid=$(mktemp "$DATA_DIR/txt_bg_pid.XXXXXX")
  echo $bg_pid > "$tmpf_pid" && mv "$tmpf_pid" "$DATA_DIR/txt_bg_pid" || rm -f "$tmpf_pid"
  disown $bg_pid

  local progress_last=""
  local progress_deadline=$(( $(date +%s) + 8 ))
  while kill -0 "$bg_pid" 2>/dev/null && (( $(date +%s) < progress_deadline )); do
    local progress_now
    progress_now=$(cat "$TXT_PROGRESS_FILE" 2>/dev/null || echo "")
    if [[ -n "$progress_now" && "$progress_now" != "$progress_last" ]]; then
      progress_last="$progress_now"
      printf '\r\e[2K  → resolved %s buffering...' "$progress_now" >&2
    fi
    sleep 0.5
  done
  [[ -n "$progress_last" ]] && printf '\r\e[2K' >&2

  local title; title=$(_wait_title "$first_url" 30)
  _ok "▶  ${title:-${TXT_LINES[1]}}"
  _info "use: mox txtnext (tn) / mox txtprev (tp) to step through"
}

# ── do_txtnext ──────────────────────────────────────────────────
do_txtnext() {
  _need
  _txt_state_read
  [ -z "$TXT_ACTIVE_FILE" ] && { _err "no active txt playlist — start one with: mox txt"; return 1; }
  _txt_read_lines "$TXT_ACTIVE_FILE"
  local total=${#TXT_LINES[@]}
  local next_idx=$(( TXT_ACTIVE_IDX + 1 ))
  if [ $next_idx -ge $total ]; then
    _warn "end of txt playlist: $(basename "$TXT_ACTIVE_FILE" .txt)  ($total songs)"
    return
  fi
  _txt_kill_bg_job
  _txt_state_write "$TXT_ACTIVE_FILE" "$next_idx"
  local query="${TXT_LINES[$(( next_idx + 1 ))]}"
  _info "searching: ${query}"
  local url; url=$(_txt_search_and_play_line "$query")
  [ -z "$url" ] && { _warn "could not find: $query"; return; }
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$url" "replace"
  local title; title=$(_wait_title "$url" 20)
  _ok "⏭  [$(( next_idx + 1 ))/${total}]  ${title:-$query}"
}

# ── do_txtprev ──────────────────────────────────────────────────
do_txtprev() {
  _need
  _txt_state_read
  [ -z "$TXT_ACTIVE_FILE" ] && { _err "no active txt playlist — start one with: mox txt"; return 1; }
  _txt_read_lines "$TXT_ACTIVE_FILE"
  local total=${#TXT_LINES[@]}
  local prev_idx=$(( TXT_ACTIVE_IDX - 1 ))
  if [ $prev_idx -lt 0 ]; then
    _warn "already at start of txt playlist: $(basename "$TXT_ACTIVE_FILE" .txt)"
    return
  fi
  _txt_kill_bg_job
  _txt_state_write "$TXT_ACTIVE_FILE" "$prev_idx"
  local query="${TXT_LINES[$(( prev_idx + 1 ))]}"
  _info "searching: ${query}"
  local url; url=$(_txt_search_and_play_line "$query")
  [ -z "$url" ] && { _warn "could not find: $query"; return; }
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$url" "replace"
  local title; title=$(_wait_title "$url" 20)
  _ok "⏮  [$(( prev_idx + 1 ))/${total}]  ${title:-$query}"
}

# ── do_txtnow ───────────────────────────────────────────────────
do_txtnow() {
  _txt_state_read
  if [ -z "$TXT_ACTIVE_FILE" ]; then
    _warn "no active txt playlist"; _info "start one with: mox txt"; return
  fi
  _txt_read_lines "$TXT_ACTIVE_FILE"
  local total=${#TXT_LINES[@]}
  local current_query="${TXT_LINES[$(( TXT_ACTIVE_IDX + 1 ))]}"
  echo ""
  echo "  ${C}txt playlist:${X}  $(basename "$TXT_ACTIVE_FILE" .txt)"
  echo "  ${W}position:${X}    $(( TXT_ACTIVE_IDX + 1 )) / ${total}"
  echo "  ${W}current:${X}     ${current_query}"
  echo ""
  local ctx_start=$(( TXT_ACTIVE_IDX - 2 ))
  local ctx_end=$(( TXT_ACTIVE_IDX + 3 ))
  (( ctx_start < 0 )) && ctx_start=0
  (( ctx_end > total - 1 )) && ctx_end=$(( total - 1 ))
  local i=$ctx_start
  while [ $i -le $ctx_end ]; do
    local line="${TXT_LINES[$(( i + 1 ))]}"
    if [ $i -eq $TXT_ACTIVE_IDX ]; then
      printf "  ${G}▶ %d. %s${X}\n" "$(( i + 1 ))" "$line"
    else
      printf "    %d. %s\n" "$(( i + 1 ))" "$line"
    fi
    i=$(( i + 1 ))
  done
  echo ""
}

# ── do_txts ─────────────────────────────────────────────────────
do_txts() {
  # Set nullglob to avoid errors when no .txt files exist
  setopt nullglob 2>/dev/null || shopt -s nullglob 2>/dev/null
  echo ""
  printf "  ${C}txt playlists  →  %s${X}\n" "$TXTS_DIR"
  echo ""
  local found=0
  _txt_state_read
  for f in "$TXTS_DIR"/*.txt; do
    [ -f "$f" ] || continue
    local name; name=$(basename "$f" .txt)
    local count; count=$(grep -cvE '^\s*(#|$)' "$f" 2>/dev/null || echo 0)
    if [ "$f" = "$TXT_ACTIVE_FILE" ]; then
      printf "  ${G}▶${X} ${W}%s${X}  (%s songs)  ${C}→ mox txt %s${X}\n" "$name" "$count" "$name"
    else
      printf "  ∙ ${W}%s${X}  (%s songs)  ${C}→ mox txt %s${X}\n" "$name" "$count" "$name"
    fi
    found=1
  done
  if [ $found -eq 0 ]; then
    echo "  (none yet)"
    echo ""
    printf "  ${Y}How to add:${X} drop a .txt file into %s\n" "$TXTS_DIR"
    echo "  One song name per line. Lines starting with # are comments."
  fi
  echo ""
}

# ── do_txtpick ──────────────────────────────────────────────────
do_txtpick() {
  _need
  _check_deps
  _txt_state_read
  [ -z "$TXT_ACTIVE_FILE" ] && { _err "no active txt playlist — start one with: mox txt"; return 1; }
  _txt_read_lines "$TXT_ACTIVE_FILE"
  local total=${#TXT_LINES[@]}
  local display=()
  local i=0
  while [ $i -lt $total ]; do
    local marker="  "; [ $i -eq $TXT_ACTIVE_IDX ] && marker="▶ "
    display+=("${marker}$(( i + 1 )). ${TXT_LINES[$(( i + 1 ))]}")
    i=$(( i + 1 ))
  done
  local chosen
  chosen=$(printf '%s\n' "${display[@]}" | "$FZF" \
    --height 60% --reverse \
    --prompt "📄 jump to > " \
    --header "▶ = current · ENTER to play · ESC cancel" \
    --no-sort)
  [ -z "$chosen" ] && { _warn "cancelled"; return; }
  local num; num=$(echo "$chosen" | grep -oE '[0-9]+\.' | head -1 | tr -d '.')
  [ -z "$num" ] && { _err "could not parse selection"; return 1; }
  local new_idx=$(( num - 1 ))
  local query="${TXT_LINES[$num]}"
  _info "searching: ${query}"
  local url; url=$(_txt_search_and_play_line "$query")
  [ -z "$url" ] && { _warn "could not find: $query"; return; }
  _txt_state_write "$TXT_ACTIVE_FILE" "$new_idx"
  _txt_kill_bg_job
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$url" "replace"
  local title; title=$(_wait_title "$url" 20)
  local total_n; total_n=${#TXT_LINES[@]}
  _ok "▶  [${num}/${total_n}]  ${title:-$query}"
}

# ── do_txtedit ──────────────────────────────────────────────────
do_txtedit() {
  _check_deps
  # Set nullglob to avoid errors when no .txt files exist
  setopt nullglob 2>/dev/null || shopt -s nullglob 2>/dev/null
  local arg="${1:-}"
  local f
  if [ -z "$arg" ]; then
    local files=()
    for f in "$TXTS_DIR"/*.txt; do
      [ -f "$f" ] && files+=("$f")
    done
    [ ${#files[@]} -eq 0 ] && { _err "no txt files in $TXTS_DIR"; return 1; }
    local picked
    picked=$(printf '%s\n' "${files[@]}" | xargs -I{} basename {} .txt | "$FZF" \
      --height 40% --reverse --prompt "✏  edit > " --header "pick file to edit")
    [ -z "$picked" ] && { _warn "cancelled"; return; }
    f="$TXTS_DIR/${picked}.txt"
  else
    f=$(_txt_resolve "$arg")
    if [ -z "$f" ]; then
      f="$TXTS_DIR/${arg}.txt"
      _info "creating new txt playlist: $arg"
      printf '# %s\n# one song name per line, blank lines and # lines are ignored\n\n' "$arg" > "$f"
    fi
  fi
  local editor="${EDITOR:-nano}"
  "$editor" "$f"
  local count; count=$(grep -cvE '^\s*(#|$)' "$f" 2>/dev/null || echo 0)
  _ok "saved: $(basename "$f")  (${count} songs)"
}

# ── do_txt_export ───────────────────────────────────────────────
do_txt_export() {
  _txt_state_read
  [ -z "$TXT_ACTIVE_FILE" ] && { _err "no active txt playlist — start one with: mox txt"; return 1; }
  local name; name=$(basename "$TXT_ACTIVE_FILE" .txt)
  local out="$PLAYLIST_DIR/${name}.m3u"
  _txt_read_lines "$TXT_ACTIVE_FILE"
  [ ${#TXT_LINES[@]} -eq 0 ] && { _err "txt file is empty"; return 1; }
  _info "resolving ${#TXT_LINES[@]} songs to URLs (this may take a while)..."
  local tmpf; tmpf=$(mktemp "$PLAYLIST_DIR/${name}.XXXXXX")
  local count=0 i=1
  while [ $i -le ${#TXT_LINES[@]} ]; do
    local url; url=$(_txt_search_and_play_line "${TXT_LINES[$i]}")
    if [ -n "$url" ]; then
      echo "$url" >> "$tmpf"
      count=$(( count + 1 ))
      printf '\r\e[2K  → resolved %d/%d...' "$count" "${#TXT_LINES[@]}" >&2
    else
      _warn "skipped (not found): ${TXT_LINES[$i]}"
    fi
    i=$(( i + 1 ))
  done
  printf '\r\e[2K' >&2
  if [[ $count -eq 0 ]]; then rm -f "$tmpf"; _err "could not resolve any tracks"; return 1; fi
  mv "$tmpf" "$out"
  _ok "exported '${name}' txt → m3u  (${count} tracks)  →  mox load ${name}"
}

# ── do_local ────────────────────────────────────────────────────
do_local() {
  _check_deps
  [[ -f "$LOCAL_INDEX" ]] || { _err "no local index — run: mox index first"; return 1; }
  local query="${1:-}"

  local results
  if [[ -n "$query" ]]; then
    results=$(grep -i "$query" "$LOCAL_INDEX" 2>/dev/null | head -50)
  else
    results=$(cat "$LOCAL_INDEX")
  fi

  [[ -z "$results" ]] && { _warn "no local tracks matching: $query"; return; }

  local chosen
  if [[ -n "${MOX_TEST_MODE:-}" ]]; then
    chosen=$(printf '%s\n' "$results" | head -1)
  else
    [[ -x "$FZF" ]] || { _err "fzf not found — install fzf or pass a search query in test mode"; return 2; }
    chosen=$(echo "$results" | "$FZF" \
      --height 60% --reverse \
      --prompt "🎵 local > " \
      --header "ENTER play · ESC cancel" \
      --with-nth=2 --delimiter=$'\t' \
      --preview 'echo {} | awk -F"\t" "{print \"File:\", \$1, \"\nTitle:\", \$2, \"\nArtist:\", \$3}"' \
      --preview-window=down:3:wrap)
  fi

  [[ -z "$chosen" ]] && { _warn "cancelled"; return; }
  local filepath; filepath=$(printf '%s' "$chosen" | awk -F'\t' '{print $1}')
  [[ -f "$filepath" ]] || { _err "file not found: $filepath"; return 1; }

  _start
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$filepath" "replace"
  local title; title=$(_wait_title "$filepath" 15)
  _ok "▶  ${title:-$(basename "$filepath")}"
}
