#!/usr/bin/env bash
# mox lib/queue.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── _queue_snapshot ─────────────────────────────────────────────
_queue_snapshot() {
  [ ! -S "$SOCKET" ] && return
  local raw; raw=$(_cmd '{"command":["get_property","playlist"]}' 2>/dev/null)
  [ -z "$raw" ] && return
  local urls; urls=$(echo "$raw" | "$JQ" -r '.data[].filename // empty' 2>/dev/null)
  [ -z "$urls" ] && return
  local tmpf; tmpf=$(mktemp "$DATA_DIR/snap.XXXXXX")
  echo "$urls" > "$tmpf" && mv "$tmpf" "$QUEUE_SNAPSHOT" || rm -f "$tmpf"
  # Phase 2.5: auto-save to autosave_queue.m3u when enabled
  [[ -f "$QUEUE_SAVE_AUTO_FILE" ]] && cp "$QUEUE_SNAPSHOT" "$AUTOSAVE_QUEUE_FILE" 2>/dev/null
}

# ── _autodj_check ───────────────────────────────────────────────
_autodj_check() {
  [[ "$AUTODJ_ENABLED" != "1" ]] && return
  [[ ! -f "$AUTODJ_FILE" ]] && return
  [ ! -S "$SOCKET" ] && return

  local pl_count
  pl_count=$(_cmd '{"command":["get_property","playlist"]}' | "$JQ" '.data|length' 2>/dev/null || echo 0)
  (( pl_count > 2 )) && return  # queue still has tracks, don't refill

  [ -s "$HISTORY_FILE" ] || return
  local seed_title; seed_title=$(_tac "$HISTORY_FILE" | awk -F'\t' '!seen[$2]++ {print $2; exit}')
  [ -z "$seed_title" ] && return

  _info "Auto-DJ: refilling queue based on: $seed_title" >&2

  local similar_title=""
  if [[ -n "${LASTFM_API_KEY:-}" ]] && command -v curl >/dev/null 2>&1; then
    local artist track
    if echo "$seed_title" | grep -q ' - '; then
      artist=$(echo "$seed_title" | cut -d'-' -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
      track=$(echo "$seed_title"  | cut -d'-' -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    else
      artist=""; track="$seed_title"
    fi
    local enc_artist enc_track
    enc_artist=$(printf '%s' "$artist" | "$JQ" -Rr '@uri' 2>/dev/null)
    enc_track=$(printf '%s' "$track" | "$JQ" -Rr '@uri' 2>/dev/null)
    local lastfm_resp
    lastfm_resp=$(curl -s --max-time 8 \
      "https://ws.audioscrobbler.com/2.0/?method=track.getsimilar&artist=${enc_artist}&track=${enc_track}&api_key=${LASTFM_API_KEY}&format=json&limit=10" \
      2>/dev/null)
    similar_title=$(echo "$lastfm_resp" | "$JQ" -r \
      '.similartracks.track[] | "\(.artist.name) - \(.name)"' 2>/dev/null \
      | grep -v "^null" | head -5 \
      | awk 'BEGIN{srand()} {a[NR]=$0} END{if(NR>0) print a[int(rand()*NR)+1]}')
  fi

  local query="${similar_title:-$seed_title}"
  local results; results=$(_do_search "$query" 3) || return
  local url; url=$(echo "$results" | head -1 | awk -F ' \| ' '{print $NF}')
  [ -z "$url" ] && return
  _ipc_loadfile "$url" "append-play"
  _info "Auto-DJ: added $(echo "$results" | head -1 | awk -F ' \| ' '{print $1}')" >&2
}

# ── do_queue_restore ────────────────────────────────────────────
do_queue_restore() {
  [ -f "$QUEUE_SNAPSHOT" ] || { _warn "no queue snapshot found — nothing to restore"; return; }
  local count; count=$(grep -c . "$QUEUE_SNAPSHOT" 2>/dev/null || echo 0)
  [ "$count" -eq 0 ] && { _warn "queue snapshot is empty"; return; }
  _start
  _silent '{"command":["playlist-clear"]}'
  local loaded=0
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    _ipc_loadfile "$line" "append-play"
    loaded=$(( loaded + 1 ))
  done < "$QUEUE_SNAPSHOT"
  _ok "restored queue: ${loaded} tracks  (use: mox now)"
}

# ── do_queue ────────────────────────────────────────────────────
do_queue() {
  _need
  local pl current_idx n
  pl=$(_cmd '{"command":["get_property","playlist"]}')
  n=$(echo "$pl" | "$JQ" '.data|length' 2>/dev/null)
  current_idx=$(_get playlist-playing-pos)
  [ -z "$n" ] || [ "$n" = "0" ] && { _warn "queue empty"; return; }
  echo ""
  echo "  ${C}queue — ${n} tracks${X}"
  echo ""
  echo "$pl" | "$JQ" -r '.data | to_entries[] | [(.key|tostring), (.value.title // .value.filename)] | @tsv' 2>/dev/null \
    | while IFS=$'\t' read -r idx title; do
        if [ "$idx" = "$current_idx" ]; then
          echo "  ${G}▶ $((idx+1)). ${title}${X}"
        else
          echo "    $((idx+1)). ${title}"
        fi
      done
  echo ""
}

# ── do_queue_move ───────────────────────────────────────────────
do_queue_move() {
  [[ -z "${1:-}" || -z "${2:-}" ]] && { _err "usage: mox qmove <from_pos> <to_pos>  (1-based)"; return 1; }
  [[ "$1" == <-> && "$2" == <-> ]] || { _err "qmove positions must be positive integers"; return 1; }
  (( $1 > 0 && $2 > 0 )) || { _err "qmove positions must be positive integers"; return 1; }
  _need
  local from=$(( $1 - 1 )) to=$(( $2 - 1 ))
  _silent "{\"command\":[\"playlist-move\",${from},${to}]}"
  _ok "moved track $1 → position $2"
}

# ── do_queue_remove ─────────────────────────────────────────────
do_queue_remove() {
  [[ -z "${1:-}" ]] && { _err "usage: mox qrm <pos>  (1-based)"; return 1; }
  [[ "$1" == <-> ]] || { _err "qrm position must be a positive integer"; return 1; }
  (( $1 > 0 )) || { _err "qrm position must be a positive integer"; return 1; }
  _need
  local pos=$(( $1 - 1 ))
  _silent "{\"command\":[\"playlist-remove\",${pos}]}"
  _ok "removed track $1 from queue"
}

# ── do_autodj ───────────────────────────────────────────────────
do_autodj() {
  if [[ -f "$AUTODJ_FILE" ]]; then
    rm -f "$AUTODJ_FILE"
    AUTODJ_ENABLED=0
    _ok "🤖 Auto-DJ: OFF"
  else
    touch "$AUTODJ_FILE"
    AUTODJ_ENABLED=1
    _ok "🤖 Auto-DJ: ON  (queue will auto-refill from Last.fm/YouTube when empty)"
    [[ -z "$LASTFM_API_KEY" ]] && _warn "tip: set LASTFM_API_KEY in config for better recommendations"
  fi
}
