#!/usr/bin/env bash
# mox lib/schedule.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── do_sleep ────────────────────────────────────────────────────
do_sleep() {
  _need
  if [[ "${1:-}" == "cancel" || "${1:-}" == "off" ]]; then
    _sleep_timer_cancel; _ok "sleep timer cancelled"; return
  fi
  [[ -z "${1:-}" ]] && { _err "usage: mox sleep <minutes> | cancel"; return 1; }
  [[ "${1:-}" =~ ^[0-9]+$ ]] || { _err "usage: mox sleep <minutes>  (integer)"; return 1; }
  local mins="$1" secs=$(( $1 * 60 ))
  _sleep_timer_cancel
  local timer_file="$DATA_DIR/sleep_timer_pid"
  (
    sleep "$secs"
    echo '{"command":["set_property","pause",true]}' | "$SOCAT" - "$SOCKET" >/dev/null 2>&1
    sleep 2
    if [[ -f "$MPV_PID_FILE" ]]; then
      local pid; pid=$(cat "$MPV_PID_FILE" 2>/dev/null)
      [[ -n "$pid" ]] && kill "$pid" 2>/dev/null
    fi
    rm -f "$timer_file"
  ) &
  local tpid=$!
  echo $tpid > "$timer_file"
  disown $tpid
  _ok "⏲  sleep timer set: ${mins} minute(s)  (m sleep cancel to abort)"
}

# ── do_schedule ─────────────────────────────────────────────────
do_schedule() {
  local when="${1:-}" query="${2:-}"
  [[ -z "$when" || -z "$query" ]] && { _err "usage: mox schedule \"HH:MM [tomorrow]\" \"query or playlist\""; return 1; }
  mkdir -p "$SCHEDULE_DIR"
  local hour minute day_offset=0
  if [[ "$when" =~ '([0-9]{1,2}):([0-9]{2})' ]]; then
    hour="${match[1]}"; minute="${match[2]}"
  else
    _err "schedule time must include HH:MM"
    return 1
  fi
  [[ "$when" == *tomorrow* ]] && day_offset=1
  local stamp label script
  stamp=$(date +%Y%m%d%H%M%S)
  label="mox.schedule.${stamp}"
  script="$SCHEDULE_DIR/${label}.sh"
  local mox_bin; mox_bin=$(command -v mox 2>/dev/null || printf '%s' "${0:a}")
  cat > "$script" <<EOF
#!/bin/sh
exec "$mox_bin" "$query"
EOF
  chmod +x "$script"

  if [[ "$OS" == "mac" ]]; then
    local plist="$SCHEDULE_DIR/${label}.plist"
    local y m d
    y=$(date -v+"${day_offset}"d +%Y 2>/dev/null || date +%Y)
    m=$(date -v+"${day_offset}"d +%m 2>/dev/null || date +%m)
    d=$(date -v+"${day_offset}"d +%d 2>/dev/null || date +%d)
    cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>Label</key><string>$label</string>
<key>ProgramArguments</key><array><string>$script</string></array>
<key>StartCalendarInterval</key><dict>
<key>Year</key><integer>$y</integer><key>Month</key><integer>$m</integer><key>Day</key><integer>$d</integer>
<key>Hour</key><integer>$hour</integer><key>Minute</key><integer>$minute</integer>
</dict>
<key>StandardOutPath</key><string>$DATA_DIR/schedule.log</string>
<key>StandardErrorPath</key><string>$DATA_DIR/schedule.log</string>
</dict></plist>
EOF
    if [[ -n "${MOX_TEST_MODE:-}" ]]; then
      _ok "created launchd plist: $plist"
    else
      launchctl load "$plist" 2>/dev/null && _ok "scheduled via launchd: $when → $query" || _warn "created launchd plist: $plist"
    fi
  elif command -v at >/dev/null 2>&1; then
    printf '%s\n' "$script" | at "$when"
    _ok "scheduled via at: $when → $query"
  else
    _warn "created runnable schedule script; install at/launchd support to auto-run it"
    echo "$script"
  fi
}
