#!/usr/bin/env bash
# mox lib/search.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── _cache_key ──────────────────────────────────────────────────
_cache_key() {
  printf '%s' "$1" | _md5 | tr -d ' \n'
}

# ── _cache_age ──────────────────────────────────────────────────
_cache_age() {
  local f="$1"
  [ -f "$f" ] || { echo 9999; return; }
  echo $(( $(date +%s) - $(_mtime "$f") ))
}

# ── _search_youtube_api ─────────────────────────────────────────
_search_youtube_api() {
  local query="$1" n="${2:-$SEARCH_RESULTS}"
  [[ -z "$YOUTUBE_API_KEY" || -z "$CURL" || ! -x "$CURL" ]] && return 1

  local encoded_q; encoded_q=$(printf '%s' "$query" | "$JQ" -Rr '@uri' 2>/dev/null)
  [[ -z "$encoded_q" ]] && return 1

  local resp
  resp=$("$CURL" -sf --max-time 8 \
    "https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&videoCategoryId=10&maxResults=${n}&q=${encoded_q}&key=${YOUTUBE_API_KEY}" \
    2>/dev/null) || return 1

  # Extract video IDs, then fetch durations in one batch call
  local ids; ids=$(echo "$resp" | "$JQ" -r '.items[].id.videoId' 2>/dev/null | tr '\n' ',' | sed 's/,$//')
  [[ -z "$ids" ]] && return 1

  local details
  details=$("$CURL" -sf --max-time 8 \
    "https://www.googleapis.com/youtube/v3/videos?part=contentDetails,snippet&id=${ids}&key=${YOUTUBE_API_KEY}" \
    2>/dev/null) || return 1

  # Format output: "Title | Duration | URL"
  echo "$details" | "$JQ" -r '
    .items[] |
    .id as $id |
    .snippet.title as $title |
    (.contentDetails.duration |
      ltrimstr("PT") |
      # parse ISO 8601 duration PT#H#M#S (// 0 guards null capture groups)
      (capture("(?:(?<h>[0-9]+)H)?(?:(?<m>[0-9]+)M)?(?:(?<s>[0-9]+)S)?") |
       (((.h | tonumber?) // 0) * 3600 +
        ((.m | tonumber?) // 0) * 60 +
        ((.s | tonumber?) // 0))) |
      . as $total |
      "\(if $total >= 3600 then "\($total/3600|floor):" else "" end)\(($total%3600)/60|floor|tostring|if length<2 then "0"+. else . end):\($total%60|floor|tostring|if length<2 then "0"+. else . end)"
    ) as $dur |
    "\($title) | \($dur) | https://www.youtube.com/watch?v=\($id)"
  ' 2>/dev/null
}

# ── _search_invidious ───────────────────────────────────────────
_search_invidious() {
  local query="$1" n="${2:-$SEARCH_RESULTS}"
  [[ -z "$INVIDIOUS_HOST" || -z "$CURL" || ! -x "$CURL" ]] && return 1

  local encoded_q; encoded_q=$(printf '%s' "$query" | "$JQ" -Rr '@uri' 2>/dev/null)
  [[ -z "$encoded_q" ]] && return 1

  local resp
  resp=$("$CURL" -sf --max-time 8 \
    "${INVIDIOUS_HOST}/api/v1/search?q=${encoded_q}&type=video&fields=title,videoId,lengthSeconds&page=1" \
    2>/dev/null) || return 1

  echo "$resp" | "$JQ" -r --argjson n "$n" '
    .[:$n][] |
    .title as $t |
    .videoId as $id |
    (.lengthSeconds |
      . as $total |
      "\(if $total >= 3600 then "\($total/3600|floor):" else "" end)\(($total%3600)/60|floor|tostring|if length<2 then "0"+. else . end):\($total%60|floor|tostring|if length<2 then "0"+. else . end)"
    ) as $dur |
    "\($t) | \($dur) | https://www.youtube.com/watch?v=\($id)"
  ' 2>/dev/null
}

# ── _search_ytdlp_stream ────────────────────────────────────────
_search_ytdlp_stream() {
  local query="$1" n="${2:-$SEARCH_RESULTS}"
  # BUG FIX: was `return ${PIPESTATUS[0]:-$?}` — PIPESTATUS is only set after
  # a pipeline; this is a plain command so PIPESTATUS is unset → crash under
  # set -u. Just use $? which correctly holds yt-dlp's exit code.
  "$YTDLP" "ytsearch${n}:${query}" \
    --print "%(title)s | %(duration_string)s | %(webpage_url)s" \
    --no-download --no-warnings 2>/dev/null
  return $?
}

# ── _do_search ──────────────────────────────────────────────────
_do_search() {
  _check_ytdlp_age
  local query="$1" n="${2:-$SEARCH_RESULTS}"
  local key="$CACHE_DIR/$(_cache_key "$query").cache"

  # Cache hit: instant
  if [ -f "$key" ] && [ "$(_cache_age "$key")" -lt "$CACHE_TTL" ]; then
    cat "$key"; return 0
  fi

  # Fast API paths (buffered — already near-instant, no need to stream)
  local results=""
  if [[ -n "$YOUTUBE_API_KEY" ]]; then
    results=$(_search_youtube_api "$query" "$n")
  fi
  if [[ -z "$results" && -n "$INVIDIOUS_HOST" ]]; then
    results=$(_search_invidious "$query" "$n")
  fi

  # API succeeded → cache + emit
  if [[ -n "$results" ]]; then
    local valid_count; valid_count=$(echo "$results" | grep -cE 'https?://' 2>/dev/null || echo 0)
    if (( valid_count >= 1 )); then
      echo "$results" > "$key"
      echo "$results"
      return 0
    fi
  fi

  # ── Streaming yt-dlp path ─────────────────────────────────
  # Stream yt-dlp stdout through a named pipe so fzf sees results
  # line-by-line. We do NOT tee into the cache here because fzf closing
  # its stdin (on ESC or ENTER) would send SIGPIPE to tee mid-stream,
  # truncating the tmpfile. Instead we write the cache file separately
  # after yt-dlp finishes (in the background), keyed to the same query.
  _info "searching (yt-dlp — streaming)..." >&2

  # Write to tmpfile in background while also streaming to stdout via fifo
  local tmpfile; tmpfile=$(mktemp "$CACHE_DIR/.search_tmp.XXXXXX")
  local fifo; fifo=$(mktemp -u "$CACHE_DIR/.fifo.XXXXXX")
  mkfifo "$fifo" || { rm -f "$tmpfile"; _search_ytdlp_stream "$query" "$n"; return $?; }

  # yt-dlp writes to both the fifo (→ stdout for fzf) and tmpfile (→ cache)
  # The subshell runs yt-dlp, tees to tmpfile, and feeds the fifo.
  # We use a background process so the fifo reader (cat below) can start.
  {
    _search_ytdlp_stream "$query" "$n" | tee "$tmpfile" > "$fifo"
    # After yt-dlp finishes (fifo closed), validate and promote cache
    local valid; valid=$(grep -cE 'https?://' "$tmpfile" 2>/dev/null || echo 0)
    if (( valid >= 1 )); then
      mv "$tmpfile" "$key" 2>/dev/null || rm -f "$tmpfile"
    else
      rm -f "$tmpfile"
    fi
    rm -f "$fifo"
  } &
  local bg_pid=$!

  # Stream fifo to our stdout (fzf reads this)
  cat "$fifo" 2>/dev/null
  local rc=$?

  # Clean up: if fzf exited early (ESC), the bg job may still be running.
  # Kill it so yt-dlp doesn't linger, and clean up tmpfile.
  kill "$bg_pid" 2>/dev/null
  wait "$bg_pid" 2>/dev/null
  rm -f "$fifo" "$tmpfile" 2>/dev/null

  return $rc
}

# ── _pick_async ─────────────────────────────────────────────────
_pick_async() {
  # Build the reload command — uses the same search priority
  local search_cmd
  if [[ -n "$YOUTUBE_API_KEY" ]]; then
    # Fast path: API search inline (no yt-dlp spawn)
    search_cmd="$0 _internal_search_api {q}"
  else
    # Slower but works without API key
    search_cmd="\"$YTDLP\" \"ytsearch${SEARCH_RESULTS}:{q}\" --print '%(title)s | %(duration_string)s | %(webpage_url)s' --no-download --no-warnings 2>/dev/null || echo 'no results'"
  fi

  local result
  result=$(FZF_DEFAULT_COMMAND="" "$FZF" \
    --height 60% --reverse \
    --prompt "🎵 " \
    --header "Type to search YouTube · ENTER select · ESC cancel" \
    --preview 'echo {} | sed "s/ | /\n/g"' \
    --preview-window=down:3:wrap \
    --ansi \
    --disabled \
    --query "" \
    --bind "change:reload:$search_cmd 2>/dev/null || echo ''" \
    --bind "start:reload:echo ''" \
    2>/dev/null) || return 1

  echo "$result" | awk -F ' \| ' '{print $NF}'
}

# ── _fzf_common ─────────────────────────────────────────────────
_fzf_common() {
  local header="$1"
  "$FZF" \
    --height 55% --reverse \
    --prompt "🎵 " \
    --header "$header" \
    --preview 'echo {} | sed "s/ | /\n/g"' \
    --preview-window=down:3:wrap \
    --ansi
}

# ── _pick ───────────────────────────────────────────────────────
_pick() {
  local query="$1"
  local key="$CACHE_DIR/$(_cache_key "$query").cache"
  local fzf_out url fzf_rc

  # Cache hit — instant
  if [ -f "$key" ] && [ "$(_cache_age "$key")" -lt "$CACHE_TTL" ]; then
    _info "instant results (cached)" >&2
    fzf_out=$(cat "$key" | _fzf_common "ENTER select · ESC cancel (cached)")
    fzf_rc=$?
    # BUG FIX: was `return ${PIPESTATUS[0]}` which returned cat's rc (always 0),
    # not fzf's. ESC → fzf exits 130, but cat exits 0, so _pick wrongly
    # returned 0 with empty output and do_play would proceed with empty URL.
    (( fzf_rc != 0 )) && return 1
    url=$(echo "$fzf_out" | awk -F ' \| ' '{print $NF}')
    echo "$url"
    return 0
  fi

  # Live path — _do_search announces itself, don't double-print
  # BUG FIX: removed the duplicate _info "searching..." here; _do_search
  # already prints "searching (yt-dlp — streaming)..." so we were getting
  # two "searching..." messages on every non-cached yt-dlp search.
  [[ -n "$YOUTUBE_API_KEY" || -n "$INVIDIOUS_HOST" ]] \
    && _info "searching (API)..." >&2

  fzf_out=$(_do_search "$query" | _fzf_common "ENTER select · ESC cancel  (loading...)")
  fzf_rc=$?
  # BUG FIX: pipeline `_do_search | fzf | awk` meant awk's rc (always 0) was
  # returned. Now we capture fzf's rc directly before awk runs.
  (( fzf_rc != 0 )) && return 1
  url=$(echo "$fzf_out" | awk -F ' \| ' '{print $NF}')
  echo "$url"
  return 0
}

# ── do_similar ──────────────────────────────────────────────────
do_similar() {
  _need
  [ -s "$HISTORY_FILE" ] || { _warn "no history yet — play some tracks first"; return; }
  local seeds; seeds=$(_tac "$HISTORY_FILE" | awk -F'\t' '!seen[$2]++ {print $2}' | head -3)
  [ -z "$seeds" ] && { _warn "not enough history"; return; }
  local seed_title; seed_title=$(echo "$seeds" | head -1)

  if [[ -n "${LASTFM_API_KEY:-}" ]] && command -v curl >/dev/null 2>&1; then
    _info "querying Last.fm for tracks similar to: ${seed_title}"
    local artist track
    if echo "$seed_title" | grep -q ' - '; then
      artist=$(echo "$seed_title" | cut -d'-' -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
      track=$(echo "$seed_title"  | cut -d'-' -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    else
      artist=""; track="$seed_title"
    fi

    # v5-G: use jq @uri instead of python3
    local enc_artist; enc_artist=$(printf '%s' "$artist" | "$JQ" -Rr '@uri' 2>/dev/null)
    local enc_track; enc_track=$(printf '%s' "$track" | "$JQ" -Rr '@uri' 2>/dev/null)

    local lastfm_resp
    lastfm_resp=$(curl -s --max-time 8 \
      "https://ws.audioscrobbler.com/2.0/?method=track.getsimilar&artist=${enc_artist}&track=${enc_track}&api_key=${LASTFM_API_KEY}&format=json&limit=10" \
      2>/dev/null)

    local similar_title
    similar_title=$(echo "$lastfm_resp" | "$JQ" -r \
      '.similartracks.track[] | "\(.artist.name) - \(.name)"' 2>/dev/null \
      | grep -v "^null" | head -5 \
      | awk 'BEGIN{srand()} {a[NR]=$0} END{if(NR>0) print a[int(rand()*NR)+1]}')

    if [[ -n "$similar_title" ]]; then
      _info "Last.fm recommends: ${similar_title}"
      local url; url=$(_pick "$similar_title") || return 1
      [ -z "$url" ] && { _warn "cancelled"; return; }
      _ipc_loadfile "$url" "append-play"
      _ok "➕ added Last.fm similar track: ${similar_title}"
      _queue_snapshot
      return
    fi
    _warn "Last.fm returned no similar tracks — falling back to YouTube search"
  fi

  _info "YouTube keyword search for: ${seed_title}  (set LASTFM_API_KEY for real recommendations)"
  local url; url=$(_pick "$seed_title") || return 1
  [ -z "$url" ] && { _warn "cancelled"; return; }
  _ipc_loadfile "$url" "append-play"
  _ok "➕ added to queue (YouTube keyword match — not semantic similarity)"
  _queue_snapshot
}
