#!/usr/bin/env bash
# mox lib/ui.sh — sourced by mox.sh at startup
# AUTO-GENERATED by modularize.py — do not edit manually
# shellcheck shell=bash


# ── _md5 ────────────────────────────────────────────────────────
_md5() {
  if [[ "$OS" == "mac" ]]; then md5
  else md5sum | cut -c1-32
  fi
}

# ── _shuf1 ──────────────────────────────────────────────────────
_shuf1() {
  local f="$1"
  [[ -s "$f" ]] || return 1
  awk 'BEGIN{srand()} {if(rand()<1/NR) r=$0} END{if(NR>0) print r}' "$f"
}

# ── _clean_url ──────────────────────────────────────────────────
_clean_url() {
  local url="$1"

  # Don't mangle local file paths
  [[ "$url" == /* || "$url" == ./* || "$url" == ../* ]] && { echo "$url"; return; }
  [[ -f "$url" ]] && { echo "$url"; return; }

  local vid=""

  # Standard YouTube watch URL: ?v= or &v=
  vid=$(printf '%s' "$url" | grep -oE '[?&]v=([A-Za-z0-9_-]{11})' | head -1 | cut -d= -f2)

  # YouTube Shorts: /shorts/ID (v5-E)
  if [ -z "$vid" ]; then
    vid=$(printf '%s' "$url" | grep -oE '/shorts/([A-Za-z0-9_-]{11})' | head -1 | grep -oE '[A-Za-z0-9_-]{11}$')
  fi

  # youtu.be short links
  if [ -z "$vid" ]; then
    vid=$(printf '%s' "$url" | grep -oE 'youtu\.be/([A-Za-z0-9_-]{11})' | head -1 \
          | grep -oE '[A-Za-z0-9_-]{11}$')
  fi

  # YouTube live streams: /live/ID
  if [ -z "$vid" ]; then
    vid=$(printf '%s' "$url" | grep -oE '/live/([A-Za-z0-9_-]{11})' | head -1 | grep -oE '[A-Za-z0-9_-]{11}$')
  fi

  # If we got a YouTube video ID, normalise to canonical URL
  [ -n "$vid" ] && { echo "https://www.youtube.com/watch?v=$vid"; return; }

  # Non-YouTube (SoundCloud, Bandcamp, etc.) — return as-is (v5-E)
  echo "$url"
}

# ── do_version ──────────────────────────────────────────────────
do_version() {
  local script_dir version=""

  # Get the directory containing this script (compatible with both bash and zsh)
  if [[ -n "${BASH_SOURCE:-}" ]]; then
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  else
    script_dir="$(cd "$(dirname "$0")" && pwd)"
  fi

  # Priority 1: Check MOX_PACKAGE_DIR (set by npm wrapper script)
  if [[ -n "$MOX_PACKAGE_DIR" ]]; then
    if [[ -f "$MOX_PACKAGE_DIR/package.json" ]] && command -v jq >/dev/null 2>&1; then
      version=$(jq -r '.version // empty' "$MOX_PACKAGE_DIR/package.json" 2>/dev/null)
    fi
    if [[ -z "$version" && -f "$MOX_PACKAGE_DIR/VERSION" ]]; then
      version=$(cat "$MOX_PACKAGE_DIR/VERSION" 2>/dev/null | tr -d '\n\r')
    fi
  fi

  # Priority 2: Try package.json if we're in a development environment
  if [[ -z "$version" ]]; then
    local package_json_paths=(
      "${MOX_LIBEXEC_DIR:-}/package.json"
      "$script_dir/../package.json"
      "$script_dir/../../package.json"
    )

    for package_file in "${package_json_paths[@]}"; do
      if [[ -f "$package_file" ]] && command -v jq >/dev/null 2>&1; then
        version=$(jq -r '.version // empty' "$package_file" 2>/dev/null)
        [[ -n "$version" && "$version" != "null" ]] && break
      fi
    done
  fi

  # Priority 3: Try VERSION file
  if [[ -z "$version" ]]; then
    local version_paths=(
      "${MOX_LIBEXEC_DIR:-}/VERSION"
      "$script_dir/../VERSION"
      "$script_dir/../../VERSION"
    )

    for version_file in "${version_paths[@]}"; do
      if [[ -f "$version_file" ]]; then
        version=$(cat "$version_file" 2>/dev/null | tr -d '\n\r')
        [[ -n "$version" ]] && break
      fi
    done
  fi

  # Priority 4: Try git tag (development environment)
  if [[ -z "$version" ]] && command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
    version=$(git describe --tags --exact-match 2>/dev/null || git describe --tags 2>/dev/null)
  fi

  # Fallback
  [[ -z "$version" ]] && version="unknown"

  echo "mox ${version}"
  echo "Terminal music CLI with web UI and extensive features"
  echo "Homepage: https://github.com/KrishnaGupta653/mox"
}

# ── do_now ──────────────────────────────────────────────────────
do_now() {
  _need
  local title pos dur paused speed
  title=$(_get media-title)
  [ -z "$title" ] && { _warn "nothing playing"; return; }
  pos=$(_get time-pos | awk '{printf "%d:%02d",$1/60,$1%60}' 2>/dev/null)
  dur=$(_get duration   | awk '{printf "%d:%02d",$1/60,$1%60}' 2>/dev/null)
  paused=$(_get pause)
  speed=$(_get speed | awk '{printf "%.2f",$1}')
  local icon="▶"; [ "$paused" = "true" ] && icon="⏸"
  local pl_pos; pl_pos=$(_get playlist-playing-pos)
  local pl_count; pl_count=$(_cmd '{"command":["get_property","playlist"]}' | "$JQ" '.data|length' 2>/dev/null)
  echo ""
  echo "  ${icon}  ${Y}${title}${X}"
  echo "  ${W}${pos}${X} / ${W}${dur}${X}   speed: ${speed}x   queue: $((pl_pos+1))/${pl_count:-?}"
  echo ""
}

# ── do_bar ──────────────────────────────────────────────────────
do_bar() {
  _need
  local title; title=$(_get media-title)
  [ -z "$title" ] && { _warn "nothing playing"; return; }

  tput civis 2>/dev/null

  local _m_bar_cleanup_done=0
  _m_bar_cleanup() {
    if [[ $_m_bar_cleanup_done -eq 0 ]]; then
      _m_bar_cleanup_done=1
      printf '\n\n\n'
      tput cnorm 2>/dev/null
    fi
  }
  trap '_m_bar_cleanup' INT TERM EXIT

  local tw; tw=$(tput cols 2>/dev/null || echo 80)
  local bar_w=$(( tw - 24 ))
  (( bar_w < 10 )) && bar_w=10

  while true; do
    # v5-K — _get_multi uses individual _get calls (get_property_list is invalid mpv IPC)
    local raw_props
    raw_props=$(_get_multi time-pos duration pause speed media-title loop-playlist loop-file volume playlist-playing-pos demuxer-cache-state 2>/dev/null)

    local pos dur paused speed title2 repeat loop_one vol pl_pos cache_state
    if echo "$raw_props" | "$JQ" -e 'type == "object"' >/dev/null 2>&1; then
      local parsed
      parsed=$(echo "$raw_props" | "$JQ" -r '
        [
          (.["time-pos"]          // ""),
          (.["duration"]          // ""),
          (.["pause"]             // "false"),
          (.["speed"]             // "1"),
          (.["media-title"]       // ""),
          (.["loop-playlist"]     // "no"),
          (.["loop-file"]         // "no"),
          (.["volume"]            // "80"),
          (.["playlist-playing-pos"] // "0"),
          (.["demuxer-cache-state"] // "")
        ] | @tsv' 2>/dev/null)
      IFS=$'\t' read -r pos dur paused speed title2 repeat loop_one vol pl_pos cache_state <<< "$parsed"
    else
      pos=$(_get time-pos); dur=$(_get duration); paused=$(_get pause)
      speed=$(_get speed); title2=$(_get media-title); repeat=$(_get loop-playlist)
      loop_one=$(_get loop-file); vol=$(_get volume)
    fi

    # v5-F: break on empty pos/dur, but cleanup runs after loop (not just trap)
    [ -z "$pos" ] || [ -z "$dur" ] && break

    local pos_i dur_i
    pos_i=$(printf '%.0f' "$pos" 2>/dev/null || echo 0)
    pos_i=$(printf '%s' "${pos_i:-0}" | tr -cd '0-9'); pos_i="${pos_i:-0}"
    dur_i=$(printf '%.0f' "$dur" 2>/dev/null || echo 1)
    dur_i=$(printf '%s' "${dur_i:-1}" | tr -cd '0-9'); dur_i="${dur_i:-1}"
    [[ "$dur_i" -lt 1 ]] 2>/dev/null && dur_i=1
    local speed_fmt vol_i
    printf -v speed_fmt '%.2f' "${speed:-1}" 2>/dev/null || speed_fmt="1.00"
    printf -v vol_i '%.0f' "${vol:-80}" 2>/dev/null || vol_i=80

    local pct=$(( pos_i * 100 / dur_i ))
    local buf_pct=""
    if [[ -n "$cache_state" && "$cache_state" != "null" ]]; then
      local cache_end
      cache_end=$(printf '%s' "$cache_state" | "$JQ" -r '."seekable-ranges"[-1].end // empty' 2>/dev/null)
      if [[ -n "$cache_end" ]]; then
        local cache_i; cache_i=$(printf '%.0f' "$cache_end" 2>/dev/null)
        cache_i=$(printf '%s' "${cache_i:-0}" | tr -cd '0-9'); cache_i="${cache_i:-0}"
        [[ "$cache_i" -gt "$dur_i" ]] 2>/dev/null && cache_i=$dur_i
        buf_pct=$(( cache_i * 100 / dur_i ))
      fi
    fi
    local filled=$(( pos_i * bar_w / dur_i ))
    local empty=$(( bar_w - filled ))
    (( filled < 0 )) && filled=0
    (( empty  < 0 )) && empty=0

    local pos_fmt; printf -v pos_fmt '%d:%02d' $(( pos_i / 60 )) $(( pos_i % 60 ))
    local dur_fmt; printf -v dur_fmt '%d:%02d' $(( dur_i / 60 )) $(( dur_i % 60 ))
    local rem_i=$(( dur_i - pos_i ))
    (( rem_i < 0 )) && rem_i=0
    local rem_fmt; printf -v rem_fmt '-%d:%02d' $(( rem_i / 60 )) $(( rem_i % 60 ))

    local icon="▶"; [ "$paused" = "true" ] && icon="⏸"
    local rep_icon=""
    [[ "$loop_one" != "no" && -n "$loop_one" ]] && rep_icon=" 🔂"
    [[ "$repeat"   != "no" && -n "$repeat"   ]] && rep_icon=" 🔁"

    local bar_filled bar_empty
    bar_filled=$(printf '%*s' "$filled" '' | tr ' ' '━')
    bar_empty=$(printf '%*s'  "$empty"  '' | tr ' ' '─')

    printf '\r\e[2K'
    printf "\e[0;36m  ${icon}  \e[1;37m%.${tw}s\e[0m" "${title2}${rep_icon}"
    printf '\n\r\e[2K'
    printf "  \e[0;36m%s\e[0m\e[2m%s\e[0m  \e[0;33m%s\e[0m / \e[0;37m%s\e[0m  \e[2m(%s)\e[0m" \
      "$bar_filled" "$bar_empty" "$pos_fmt" "$dur_fmt" "$rem_fmt"
    printf '\n\r\e[2K'
    printf "  \e[2mspd:%sx  vol:%s%%  %d%%%s  p=pause  n/b=skip  ,/.=seek  +/-=vol  r=rpt  l=lyrics  q=quit\e[0m" \
      "$speed_fmt" "$vol_i" "$pct" "${buf_pct:+  buf:${buf_pct}%}"
    printf '\e[2A'

    local key
    if read -r -s -k1 -t 0.5 key 2>/dev/null; then
      case "$key" in
        q|Q|$'\e') break ;;
        p) _silent '{"command":["cycle","pause"]}' ;;
        n) _silent '{"command":["playlist-next"]}'; sleep 0.4; (_autodj_check) & disown $! 2>/dev/null ;;
        b) _silent '{"command":["playlist-prev"]}'; sleep 0.4 ;;
        .) _silent '{"command":["seek","10","relative"]}' ;;
        ,) _silent '{"command":["seek","-10","relative"]}' ;;
        +) _silent "{\"command\":[\"add\",\"volume\",${VOLUME_STEP}]}" ;;
        -) _silent "{\"command\":[\"add\",\"volume\",-${VOLUME_STEP}]}" ;;
        r) _silent '{"command":["cycle","loop-playlist"]}' ;;
        1) _silent '{"command":["cycle","loop-file"]}' ;;
        l) printf '\n\n\n'; tput cnorm 2>/dev/null; _m_bar_cleanup_done=1; do_lyrics; return ;;
      esac
    fi
  done

  # v5-F: always cleanup after loop exit, not just on signal
  _m_bar_cleanup
  trap - INT TERM EXIT
}

# ── do_scrub ────────────────────────────────────────────────────
do_scrub() {
  _need
  _check_deps
  local title pos dur
  title=$(_get media-title)
  [ -z "$title" ] && { _warn "nothing playing"; return; }
  dur=$(_get duration)
  pos=$(_get time-pos)
  [ -z "$dur" ] && { _warn "duration unavailable (still buffering?)"; return; }

  local dur_i; dur_i=$(printf '%.0f' "$dur")
  local pos_i; pos_i=$(printf '%.0f' "${pos:-0}")
  (( dur_i < 1 )) && { _warn "track too short to scrub"; return; }

  local step=5
  (( dur_i / step > 500 )) && step=$(( dur_i / 500 + 1 ))

  local lines=()
  local t=0
  while (( t <= dur_i )); do
    local mm ss pct bar_fill bar_empty filled_w empty_w
    mm=$(( t / 60 )); ss=$(( t % 60 ))
    pct=$(( t * 100 / dur_i ))
    filled_w=$(( pct * 30 / 100 ))
    empty_w=$(( 30 - filled_w ))
    bar_fill=$(printf '%*s' "$filled_w" '' | tr ' ' '█')
    bar_empty=$(printf '%*s' "$empty_w" '' | tr ' ' '░')
    local marker="  "
    (( t >= pos_i - step/2 && t <= pos_i + step/2 )) && marker="▶ "
    lines+=("$(printf '%s%02d:%02d  [%s%s]  %3d%%' "$marker" "$mm" "$ss" "$bar_fill" "$bar_empty" "$pct")")
    t=$(( t + step ))
  done

  local chosen
  chosen=$(printf '%s\n' "${lines[@]}" | "$FZF" \
    --height 70% --reverse \
    --prompt "⏱  scrub > " \
    --header "▶ marks current pos · ENTER to jump · ESC cancel" \
    --no-sort)

  [ -z "$chosen" ] && { _warn "cancelled"; return; }

  local ts; ts=$(echo "$chosen" | grep -oE '[0-9]+:[0-9]{2}' | head -1)
  [ -z "$ts" ] && { _err "could not parse timestamp"; return 1; }

  local m s target_secs
  m=$(echo "$ts" | cut -d: -f1 | sed 's/^0*//'); m=${m:-0}
  s=$(echo "$ts" | cut -d: -f2 | sed 's/^0*//'); s=${s:-0}
  target_secs=$(( m * 60 + s ))

  _silent "{\"command\":[\"seek\",\"$target_secs\",\"absolute\"]}"
  sleep 0.1
  local new_pos; new_pos=$(_get time-pos | awk '{printf "%d:%02d",$1/60,$1%60}')
  _ok "jumped to ${new_pos}  /  $(awk "BEGIN{printf \"%d:%02d\",$dur_i/60,$dur_i%60}")"
}

# ── do_status ───────────────────────────────────────────────────
do_status() {
  # Ensure required binaries are initialized
  _ensure_bin SOCAT socat
  _ensure_bin JQ jq

  if [ ! -S "$SOCKET" ]; then
    echo ""
    echo "  ┌─────────────────────────────────────┐"
    echo "  │  ${R}● stopped${X}                        │"
    echo "  │  run: mox start                        │"
    echo "  └─────────────────────────────────────┘"
    echo ""
    return
  fi
  local title paused vol speed
  title=$(_get media-title)
  paused=$(_get pause)
  vol=$(_get volume | awk '{printf "%.0f",$1}')
  speed=$(_get speed | awk '{printf "%.2f",$1}')
  local pl_count
  pl_count=$(_cmd '{"command":["get_property","playlist"]}' | "$JQ" '.data|length' 2>/dev/null)
  local repeat; repeat=$(_get loop-playlist)
  local loop_one; loop_one=$(_get loop-file)
  echo ""
  echo "  ┌─────────────────────────────────────────────────────────────┐"
  printf "  │  ${G}● running${X}   vol: %3s%%   speed: %sx   queue: %s tracks      │\n" "$vol" "$speed" "${pl_count:-0}"
  echo "  ├─────────────────────────────────────────────────────────────┤"

  _txt_state_read
  if [ -n "$TXT_ACTIVE_FILE" ]; then
    _txt_read_lines "$TXT_ACTIVE_FILE"
    printf "  │  ${C}txt:${X} %-20s  [%s/%s]                      │\n" "$(basename "$TXT_ACTIVE_FILE" .txt)" \
      "$(( TXT_ACTIVE_IDX + 1))" "${#TXT_LINES[@]}"
  fi

  local timer_file="$DATA_DIR/sleep_timer_pid"
  if [[ -f "$timer_file" ]]; then
    local tpid; tpid=$(cat "$timer_file" 2>/dev/null)
    [[ -n "$tpid" ]] && kill -0 "$tpid" 2>/dev/null && printf "  │  ${Y}⏲  sleep timer active${X}                                  │\n"
  fi

  [[ -f "$AUTODJ_FILE" ]] && printf "  │  ${M}🤖 Auto-DJ active${X}                                        │\n"
  [[ "$repeat"   != "no" && -n "$repeat"   ]] && printf "  │  ${Y}🔁 repeat-playlist${X}                                    │\n"
  [[ "$loop_one" != "no" && -n "$loop_one" ]] && printf "  │  ${Y}🔂 repeat-one${X}                                         │\n"
  echo "  ├─────────────────────────────────────────────────────────────┤"
  if [ -n "$title" ]; then
    local pos dur
    pos=$(_get time-pos | awk '{printf "%d:%02d",$1/60,$1%60}' 2>/dev/null)
    dur=$(_get duration   | awk '{printf "%d:%02d",$1/60,$1%60}' 2>/dev/null)
    local icon="▶"; [ "$paused" = "true" ] && icon="⏸"
    local t="${title:0:45}"
    printf "  │  %s %-45s %s/%s │\n" "$icon" "$t" "$pos" "$dur"
  else
    printf "  │  ${W}idle — mox \"song name\" to play${X}                          │\n"
  fi
  echo "  └─────────────────────────────────────────────────────────────┘"
  echo ""
}

# ── _playlist_entry_valid ───────────────────────────────────────
_playlist_entry_valid() {
  local line="$1"
  [[ -z "$line" || "$line" == \#* ]] && return 1
  [[ ${#line} -le 500 ]] || return 1

  if [[ "$line" =~ ^https?://[^[:space:]]+\.[^[:space:]]+(/.*)?$ ]]; then
    [[ "$line" == *\"* || "$line" == *\'* || "$line" == *\<* || "$line" == *\>* ]] && return 1
    [[ "$line" == *\|* || "$line" == *\;* || "$line" == *\$* || "$line" == *\`* ]] && return 1
    [[ "$line" == *\&* || "$line" == *\ * ]] && return 1
    return 0
  fi

  if [[ "$line" =~ ^file:///.+ ]]; then
    local file_path="${line#file://}"
    [[ -f "$file_path" ]]
    return
  fi

  [[ -f "$line" ]]
}

# ── _lyrics_clean_title ─────────────────────────────────────────
_lyrics_clean_title() {
  local t="$1"
  # Strip common YouTube suffixes (parenthetical and bracketed)
  t=$(printf '%s' "$t" | sed -E '
    s/\(Official[^)]*\)//gi
    s/\(Lyrics[^)]*\)//gi
    s/\(Audio[^)]*\)//gi
    s/\(Video[^)]*\)//gi
    s/\(Visuali[sz]er[^)]*\)//gi
    s/\(Full Song[^)]*\)//gi
    s/\(HD[^)]*\)//gi
    s/\(HQ[^)]*\)//gi
    s/\[Official[^]]*\]//gi
    s/\[Lyrics[^]]*\]//gi
    s/\[Audio[^]]*\]//gi
    s/\[Video[^]]*\]//gi
    s/\[HD[^]]*\]//gi
    s/\[HQ[^]]*\]//gi
  ')
  # Replace underscores with spaces (common in Bollywood YouTube titles)
  t=$(printf '%s' "$t" | tr '_' ' ')
  # Remove year patterns like (1971) or standalone 4-digit years
  t=$(printf '%s' "$t" | sed -E 's/\([0-9]{4}\)//g; s/\b(19|20)[0-9]{2}\b//g')
  # Remove common metadata markers: &-separated names, pipe-separated info
  t=$(printf '%s' "$t" | sed -E 's/\|.*//; s/\#[^ ]*//g')
  # Remove "a trib..." (tribute) or "full movie" trailers
  t=$(printf '%s' "$t" | sed -E 's/\ba trib[a-z]*\b.*//i; s/\bfull movie\b.*//i; s/\bfull song\b.*//i')
  # Collapse multiple spaces, trim
  t=$(printf '%s' "$t" | sed -E 's/  +/ /g; s/^ +//; s/ +$//')
  printf '%s' "$t"
}

# ── _lyrics_try_fetch ───────────────────────────────────────────
_lyrics_try_fetch() {
  # Sets _LYRICS_LRC and _LYRICS_HAS_SYNC on success, returns 0.
  # Does NOT use $() capture — avoids zsh local-leak bug.
  _LYRICS_LRC=""
  _LYRICS_HAS_SYNC=0
  local _ltf_query="$1" _ltf_artist="${2:-}"
  local _ltf_enc_q _ltf_enc_a _ltf_url _ltf_resp _ltf_synced _ltf_plain

  _ltf_enc_q=$(printf '%s' "$_ltf_query" | "$JQ" -Rr '@uri' 2>/dev/null)
  [[ -z "$_ltf_enc_q" ]] && return 1

  _ltf_url="https://lrclib.net/api/search?q=${_ltf_enc_q}"
  if [[ -n "$_ltf_artist" ]]; then
    _ltf_enc_a=$(printf '%s' "$_ltf_artist" | "$JQ" -Rr '@uri' 2>/dev/null)
    _ltf_url="${_ltf_url}&artist_name=${_ltf_enc_a}"
  fi

  _ltf_resp=$("$CURL" -sf --max-time 8 "$_ltf_url" 2>/dev/null) || return 1
  [[ -z "$_ltf_resp" ]] && return 1

  _ltf_synced=$(printf '%s' "$_ltf_resp" | "$JQ" -r '.[0].syncedLyrics // empty' 2>/dev/null)
  if [[ -n "$_ltf_synced" ]]; then
    _LYRICS_LRC="$_ltf_synced"
    _LYRICS_HAS_SYNC=1
    return 0
  fi

  _ltf_plain=$(printf '%s' "$_ltf_resp" | "$JQ" -r '.[0].plainLyrics // empty' 2>/dev/null)
  if [[ -n "$_ltf_plain" ]]; then
    _LYRICS_LRC="$_ltf_plain"
    _LYRICS_HAS_SYNC=0
    return 0
  fi

  # Also try lrclib direct-get endpoint (exact match, more reliable)
  if [[ -n "$_ltf_artist" ]]; then
    _ltf_enc_a=$(printf '%s' "$_ltf_artist" | "$JQ" -Rr '@uri' 2>/dev/null)
    local _ltf_get_url="https://lrclib.net/api/get?artist_name=${_ltf_enc_a}&track_name=${_ltf_enc_q}"
    _ltf_resp=$("$CURL" -sf --max-time 8 "$_ltf_get_url" 2>/dev/null) || return 1
    [[ -z "$_ltf_resp" ]] && return 1

    _ltf_synced=$(printf '%s' "$_ltf_resp" | "$JQ" -r '.syncedLyrics // empty' 2>/dev/null)
    if [[ -n "$_ltf_synced" ]]; then
      _LYRICS_LRC="$_ltf_synced"
      _LYRICS_HAS_SYNC=1
      return 0
    fi
    _ltf_plain=$(printf '%s' "$_ltf_resp" | "$JQ" -r '.plainLyrics // empty' 2>/dev/null)
    if [[ -n "$_ltf_plain" ]]; then
      _LYRICS_LRC="$_ltf_plain"
      _LYRICS_HAS_SYNC=0
      return 0
    fi
  fi

  return 1
}

# ── do_ui ───────────────────────────────────────────────────────
do_ui() {
  if ! command -v tmux >/dev/null 2>&1; then
    _warn "tmux not installed — unified UI requires tmux"
    _info "falling back to mox bar..."
    do_bar
    return
  fi

  _need

  local session="m_ui_$$"
  local script_path="$0"

  tmux new-session -d -s "$session" -x "$(tput cols)" -y "$(tput lines)" 2>/dev/null || {
    _warn "could not create tmux session"; do_bar; return
  }

  # Layout: left=queue (30%), right-top=art (if chafa), right-bottom=bar
  tmux split-window -h -l "30%" -t "$session"
  tmux split-window -v -t "${session}:0.1"

  # Pane 0 (left): queue — auto-refresh every 3s
  tmux send-keys -t "${session}:0.0" \
    "watch -n 3 '\"$script_path\" queue 2>/dev/null'" Enter

  # Pane 1 (top-right): album art
  if [[ -n "$CHAFA" && -x "$CHAFA" ]]; then
    tmux send-keys -t "${session}:0.1" \
      "while true; do \"$script_path\" art 2>/dev/null; sleep 10; done" Enter
  else
    tmux send-keys -t "${session}:0.1" \
      "\"$script_path\" now" Enter
  fi

  # Pane 2 (bottom-right): live progress bar
  tmux send-keys -t "${session}:0.2" "\"$script_path\" bar" Enter

  tmux attach-session -t "$session"

  # Cleanup on exit
  tmux kill-session -t "$session" 2>/dev/null
}

# ── do_uxi ──────────────────────────────────────────────────────
do_uxi() {
  # Resolve CURL binary
  local CURL; CURL=$(command -v curl 2>/dev/null || echo "")
  [[ -z "$CURL" ]] && CURL="/opt/homebrew/bin/curl"
  [[ ! -x "$CURL" ]] && CURL="/usr/local/bin/curl"
  [[ ! -x "$CURL" ]] && { _err "curl not found"; return 1; }

  # Get script directory - handle both bash and zsh
  local script_dir
  if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  else
    script_dir="$(cd "$(dirname "$0")" && pwd)"
  fi

  # Locate music_ui_server.py
  local server_path=""
  local candidates=(
    "$script_dir/music_ui_server.py"
    "$MUSIC_ROOT/music_ui_server.py"
  )

  # If MOX_PACKAGE_DIR is set (from wrapper), use that for npm/package installations
  if [[ -n "${MOX_PACKAGE_DIR:-}" ]]; then
    candidates=("$MOX_PACKAGE_DIR/src/music_ui_server.py" "${candidates[@]}")
  fi

  # Handle Homebrew installation path
  if [[ -n "${MOX_LIBEXEC_DIR:-}" ]]; then
    candidates=("$MOX_LIBEXEC_DIR/music_ui_server.py" "${candidates[@]}")
  fi
  for c in "${candidates[@]}"; do
    [[ -f "$c" ]] && { server_path="$c"; break; }
  done
  [[ -z "$server_path" ]] && _die "music_ui_server.py not found — place it next to this script"

  # Check if server is already running
  if [[ -f "$UXI_PID_FILE" ]]; then
    local old_pid; old_pid=$(cat "$UXI_PID_FILE" 2>/dev/null)
    if [[ -n "$old_pid" ]] && kill -0 "$old_pid" 2>/dev/null; then
      _info "uxi server already running (pid $old_pid) on port $UXI_PORT"
      _open_browser "http://127.0.0.1:${UXI_PORT}"
      return
    fi
    rm -f "$UXI_PID_FILE"
  fi

  # Check port availability — retry up to 7750
  local port_ok=0
  while [[ $UXI_PORT -le 7750 ]]; do
    if ! (command -v lsof >/dev/null 2>&1 && lsof -i :"$UXI_PORT" >/dev/null 2>&1); then
      port_ok=1
      break
    fi
    [[ $UXI_PORT -lt 7750 ]] && _warn "port $UXI_PORT in use — trying $((UXI_PORT + 1))"
    UXI_PORT=$((UXI_PORT + 1))
  done
  [[ $port_ok -eq 0 ]] && { _err "no free port in range 7700–7750"; return 1; }

  # Require python3
  local py3; py3=$(command -v python3 2>/dev/null)
  [[ -z "$py3" ]] && _die "python3 required for uxi server — install python3"

  # Start bridge server in background
  _info "starting uxi bridge server on port $UXI_PORT…"
  UXI_AUTH="$UXI_AUTH" "$py3" "$server_path" "$UXI_PORT" > "$DATA_DIR/uxi_server.log" 2>&1 &
  local srv_pid=$!
  echo "$srv_pid" > "$UXI_PID_FILE"
  disown "$srv_pid" 2>/dev/null

  # Wait briefly for server to start
  local tries=0
  while (( tries < 15 )); do
    if "$CURL" -sf --max-time 1 "http://127.0.0.1:${UXI_PORT}/api/state" >/dev/null 2>&1; then
      break
    fi
    sleep 0.2
    tries=$((tries + 1))
  done

  if ! kill -0 "$srv_pid" 2>/dev/null; then
    _err "uxi server failed to start — check $DATA_DIR/uxi_server.log"
    rm -f "$UXI_PID_FILE"
    return 1
  fi

  _ok "uxi server running → http://127.0.0.1:${UXI_PORT}  (pid $srv_pid)"
  [[ "$UXI_AUTH" == "1" ]] && _info "PIN is printed in: $DATA_DIR/uxi_server.log"
  _open_browser "http://127.0.0.1:${UXI_PORT}"
}

# ── _open_browser ───────────────────────────────────────────────
_open_browser() {
  local url="$1"
  case "$OS" in
    mac) open "$url" ;;
    linux)
      if command -v xdg-open >/dev/null 2>&1; then
        xdg-open "$url"
      elif command -v sensible-browser >/dev/null 2>&1; then
        sensible-browser "$url"
      else
        _info "open in browser: $url"
      fi
      ;;
    *) _info "open in browser: $url" ;;
  esac
}

# ── do_uxi_stop ─────────────────────────────────────────────────
do_uxi_stop() {
  local killed=0
  
  # First, try to stop via PID file
  if [[ -f "$UXI_PID_FILE" ]]; then
    local pid; pid=$(cat "$UXI_PID_FILE" 2>/dev/null)
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null && killed=$((killed + 1))
    fi
    rm -f "$UXI_PID_FILE"
  fi
  
  # Kill all Python processes on ports 7700-7799 (mox uxi ports)
  if [[ "$OS" == "mac" ]]; then
    # macOS: use lsof to find all processes on 770* ports at once
    while IFS= read -r pid; do
      [[ -z "$pid" ]] && continue
      # Check if it's a Python process or has music_ui_server in command line
      local proc_info
      proc_info=$(ps -p "$pid" -o comm=,args= 2>/dev/null)
      if [[ -n "$proc_info" ]] && echo "$proc_info" | grep -q -iE '(python|music_ui_server)'; then
        kill -9 "$pid" 2>/dev/null && killed=$((killed + 1))
      fi
    done < <(lsof -ti :7700-7799 2>/dev/null)
  else
    # Linux: use ss or netstat
    if command -v ss >/dev/null 2>&1; then
      # Use ss (modern Linux)
      while IFS= read -r pid; do
        [[ -z "$pid" ]] && continue
        local proc_info
        proc_info=$(ps -p "$pid" -o comm=,args= 2>/dev/null)
        if [[ -n "$proc_info" ]] && echo "$proc_info" | grep -q -iE '(python|music_ui_server)'; then
          kill -9 "$pid" 2>/dev/null && killed=$((killed + 1))
        fi
      done < <(ss -tlnp 2>/dev/null | awk '/:(770[0-9]{2})\s/ {print $6}' | grep -oE 'pid=[0-9]+' | cut -d= -f2 | sort -u)
    else
      # Fallback: find all python processes with port 770* in command line
      while IFS= read -r pid; do
        [[ -z "$pid" ]] && continue
        kill -9 "$pid" 2>/dev/null && killed=$((killed + 1))
      done < <(ps aux | grep -E '(python|music_ui_server).*770[0-9]{2}' | grep -v grep | awk '{print $2}')
    fi
  fi
  
  # Report results
  if [[ $killed -eq 0 ]]; then
    _info "no uxi servers running on ports 7700-7799"
  else
    _ok "stopped $killed uxi server(s) on ports 7700-7799"
  fi
}

# ── _txt_state_write ────────────────────────────────────────────
_txt_state_write() {
  local file="$1" idx="$2"
  printf '%s\t%s\n' "$file" "$idx" > "$TXT_STATE_FILE"
}

# ── _txt_state_read ─────────────────────────────────────────────
_txt_state_read() {
  TXT_ACTIVE_FILE=""
  TXT_ACTIVE_IDX=0
  [ -f "$TXT_STATE_FILE" ] || return
  TXT_ACTIVE_FILE=$(awk -F'\t' '{print $1}' "$TXT_STATE_FILE")
  TXT_ACTIVE_IDX=$(awk -F'\t' '{print $2}' "$TXT_STATE_FILE")
  [ -f "$TXT_ACTIVE_FILE" ] || { TXT_ACTIVE_FILE=""; TXT_ACTIVE_IDX=0; }
}

# ── _txt_read_lines ─────────────────────────────────────────────
_txt_read_lines() {
  local f="$1"
  TXT_LINES=()
  while IFS= read -r line; do
    line="${line#"${line%%[! ]*}"}"
    line="${line%"${line##*[! ]}"}"
    [[ -z "$line" || "$line" == \#* ]] && continue
    TXT_LINES+=("$line")
  done < "$f"
}

# ── _txt_resolve ────────────────────────────────────────────────
_txt_resolve() {
  local arg="$1"
  [ -f "$arg" ] && { echo "$arg"; return; }
  [ -f "$TXTS_DIR/${arg}.txt" ] && { echo "$TXTS_DIR/${arg}.txt"; return; }
  [ -f "$TXTS_DIR/${arg}" ] && { echo "$TXTS_DIR/${arg}"; return; }
  echo ""
}

# ── _txt_search_and_play_line ───────────────────────────────────
_txt_search_and_play_line() {
  local query="$1"
  local key="$CACHE_DIR/$(_cache_key "$query").cache"
  local results url

  local _txt_n="${SEARCH_RESULTS:-5}"
  (( _txt_n > 5 )) && _txt_n=5

  if [ -f "$key" ] && [ "$(_cache_age "$key")" -lt "$CACHE_TTL" ]; then
    results=$(cat "$key")
  else
    # v5-Z: use _do_search which has proper PIPESTATUS-equivalent error handling
    results=$(_do_search "$query" "$_txt_n") || return 1
    local valid_count; valid_count=$(echo "$results" | grep -cE 'https?://' 2>/dev/null)
    valid_count=$(printf '%s' "${valid_count:-0}" | tr -cd '0-9'); valid_count="${valid_count:-0}"
    [[ -n "$results" ]] && [[ "$valid_count" -ge 1 ]] 2>/dev/null && echo "$results" > "$key"
  fi

  [ -z "$results" ] && return 1
  url=$(echo "$results" | head -1 | awk -F ' \| ' '{print $NF}')
  echo "$url"
}

# ── _txt_kill_bg_job ────────────────────────────────────────────
_txt_kill_bg_job() {
  local bg_pid_file="$DATA_DIR/txt_bg_pid"
  if [ -f "$bg_pid_file" ]; then
    local old_pid; old_pid=$(cat "$bg_pid_file" 2>/dev/null)
    if [ -n "$old_pid" ]; then
      kill -TERM -- "-$old_pid" 2>/dev/null || kill -TERM "$old_pid" 2>/dev/null
      sleep 0.2
      kill -0 "$old_pid" 2>/dev/null && kill -KILL "$old_pid" 2>/dev/null
    fi
    rm -f "$bg_pid_file"
  fi
  local cur_gen=0
  [ -f "$TXT_BG_GEN_FILE" ] && cur_gen=$(cat "$TXT_BG_GEN_FILE" 2>/dev/null)
  cur_gen=$(printf '%s' "${cur_gen:-0}" | tr -cd '0-9'); cur_gen="${cur_gen:-0}"
  echo $(( cur_gen + 1 )) > "$TXT_BG_GEN_FILE"
}

# ── _sleep_timer_cancel ─────────────────────────────────────────
_sleep_timer_cancel() {
  local timer_file="$DATA_DIR/sleep_timer_pid"
  if [[ -f "$timer_file" ]]; then
    local tpid; tpid=$(cat "$timer_file" 2>/dev/null)
    [[ -n "$tpid" ]] && kill "$tpid" 2>/dev/null
    rm -f "$timer_file"
  fi
}

# ── _af_set ─────────────────────────────────────────────────────
_af_set() {
  local filter="$1"
  local json; json=$("$JQ" -cn --arg af "$filter" '{"command":["set_property","af",$af]}')
  _silent_retry "$json"
}

# ── _af_get_raw ─────────────────────────────────────────────────
_af_get_raw() {
  local raw; raw=$(_cmd '{"command":["get_property","af"]}' 2>/dev/null)
  echo "$raw" | "$JQ" -r '.data // ""' 2>/dev/null
}

# ── do_export ───────────────────────────────────────────────────
do_export() {
  local target="${1:-likes}"
  local file
  case "$target" in
    likes)   file="$LIKES_FILE" ;;
    history) file="$HISTORY_FILE" ;;
    *) _err "usage: mox export [likes|history]"; return 1 ;;
  esac
  [ -s "$file" ] || { _warn "no data to export in: $target"; return; }
  echo "date,title,url"
  awk -F'\t' '{
    # Escape double-quotes
    gsub(/"/, "\"\"", $1); gsub(/"/, "\"\"", $2); gsub(/"/, "\"\"", $3)
    # v5-H: CSV injection guard — prefix dangerous leading chars with apostrophe (OWASP)
    if ($2 ~ /^[=+\-@]/) $2 = "\047" $2
    if ($3 ~ /^[=+\-@]/) $3 = "\047" $3
    printf "\"%s\",\"%s\",\"%s\"\n", $1, $2, $3
  }' "$file"
}

# ── do_index ────────────────────────────────────────────────────
do_index() {
  if [[ -z "${FFPROBE:-}" || ! -x "${FFPROBE:-}" ]]; then
    _warn "ffprobe not found — install ffmpeg for local library indexing"
    _info "macOS: brew install ffmpeg | Linux: apt install ffmpeg"
    return 1
  fi
  [[ -d "$LOCAL_MUSIC_DIR" ]] || { _err "LOCAL_MUSIC_DIR not found: $LOCAL_MUSIC_DIR"; return 1; }

  _info "indexing $LOCAL_MUSIC_DIR ..."
  local tmpf; tmpf=$(mktemp "$DATA_DIR/index.XXXXXX")
  local count=0

  # Find all audio files
  find "$LOCAL_MUSIC_DIR" -type f \( \
    -iname "*.mp3" -o -iname "*.flac" -o -iname "*.m4a" -o \
    -iname "*.ogg" -o -iname "*.opus" -o -iname "*.wav" -o \
    -iname "*.aac" -o -iname "*.wma" \
  \) | while IFS= read -r f; do
    local title artist album duration
    title=$("$FFPROBE" -v quiet -print_format json -show_entries \
      format_tags=title,artist,album format=duration \
      "$f" 2>/dev/null | "$JQ" -r '
        (.format.tags.title // (.format.tags.TITLE // "")) as $t |
        (.format.tags.artist // (.format.tags.ARTIST // "")) as $a |
        (.format.tags.album // (.format.tags.ALBUM // "")) as $al |
        (.format.duration // "0") as $d |
        "\($t)\t\($a)\t\($al)\t\($d)"
      ' 2>/dev/null) || true

    # Fallback to filename
    if [[ -z "$title" || "$title" == $'\t\t\t'* ]]; then
      title="$(basename "$f" | sed 's/\.[^.]*$//')"$'\t''Unknown'$'\t''Unknown'$'\t0'
    fi

    printf '%s\t%s\n' "$f" "$title" >> "$tmpf"
    count=$(( count + 1 ))
    (( count % 50 == 0 )) && printf '\r\e[2K  → indexed %d files...' "$count" >&2
  done

  printf '\r\e[2K' >&2
  mv "$tmpf" "$LOCAL_INDEX"
  count=$(wc -l < "$LOCAL_INDEX" | tr -d ' ')
  _ok "indexed ${count} tracks → $LOCAL_INDEX"
  _info "use: mox local \"song name\" to search your library"
}

# ── do_reload_config ────────────────────────────────────────────
do_reload_config() {
  [ -f "$CONFIG_FILE" ] || { _warn "no config file at: $CONFIG_FILE"; return; }
  _load_config
  _validate_config
  _ok "config reloaded from: $CONFIG_FILE"
  _info "note: daemon audio settings (device, volume) require mox stop && mox start to apply"
}

# ── do_share ────────────────────────────────────────────────────
do_share() {
  local name="${1:-queue-$(date +%Y%m%d-%H%M%S)}"
  name=$(printf '%s' "$name" | tr -cd '[:alnum:]_-')
  [[ -z "$name" ]] && name="queue-$(date +%Y%m%d-%H%M%S)"
  local out="$SHARE_DIR/${name}.m3u"

  if [ -S "$SOCKET" ]; then
    _cmd '{"command":["get_property","playlist"]}' \
      | "$JQ" -r '.data[]?.filename // empty' 2>/dev/null > "$out"
  elif [[ -f "$QUEUE_SNAPSHOT" ]]; then
    cp "$QUEUE_SNAPSHOT" "$out"
  else
    _err "no running queue or saved queue snapshot to share"
    return 1
  fi

  if [[ ! -s "$out" ]]; then
    rm -f "$out"
    _err "queue is empty"
    return 1
  fi
  _ok "shareable playlist written: $out"
  echo "  import on another mox install with:"
  echo "    mox import \"$out\""
}

# ── do_scan ─────────────────────────────────────────────────────
do_scan() {
  local mode="${1:-}"
  [[ -f "$LOCAL_INDEX" ]] || { _err "no local index — run: mox index first"; return 1; }
  case "$mode" in
    --duplicates|duplicates)
      awk -F'\t' '{key=tolower($2); paths[key]=paths[key] "\n  " $1; count[key]++} END{for(k in count) if(count[k]>1) print k paths[k] "\n"}' "$LOCAL_INDEX"
      ;;
    --unplayed|unplayed)
      awk -F'\t' 'NR==FNR{seen[tolower($3)]=1; next} !seen[tolower($2)]{print $2 "\t" $1}' "$HISTORY_FILE" "$LOCAL_INDEX" | head -100
      ;;
    --playlist|playlist)
      local label="${2:-local-mix}"
      local safe_label; safe_label=$(printf '%s' "$label" | tr -cd '[:alnum:]_-')
      [[ -z "$safe_label" ]] && safe_label="local-mix"
      local out="$PLAYLIST_DIR/${safe_label}.m3u"
      awk -F'\t' '{print $1}' "$LOCAL_INDEX" | head -100 > "$out"
      _ok "generated playlist: $safe_label ($(wc -l < "$out" | tr -d ' ') tracks)"
      ;;
    *)
      echo "usage: mox scan --duplicates | --unplayed | --playlist <name>"
      ;;
  esac
}

# ── do_doctor ───────────────────────────────────────────────────
do_doctor() {
  _check_deps
  # Also initialize optional deps for doctor output
  _ensure_bin CURL curl
  _ensure_bin CHAFA chafa
  _ensure_bin FFPROBE ffprobe

  echo ""
  echo "  ${C}mox doctor — system diagnostics (v7.2.2)${X}"
  echo "  $(date)"
  echo ""
  echo "  ${W}Dependencies:${X}"
  for bin_var in YTDLP MPV FZF SOCAT JQ CURL CHAFA FFPROBE; do
    local bin_path="${(P)bin_var}"
    if [[ -n "$bin_path" && -x "$bin_path" ]]; then
      local ver=""
      case "$bin_var" in
        YTDLP)   ver=$("$bin_path" --version 2>/dev/null | head -1) ;;
        MPV)     ver=$("$bin_path" --version 2>/dev/null | head -1 | awk '{print $1,$2,$3}') ;;
        FZF)     ver=$("$bin_path" --version 2>/dev/null | head -1) ;;
        SOCAT)   ver=$("$bin_path" -V 2>&1 | head -1 | awk '{print $1,$2}') ;;
        JQ)      ver=$("$bin_path" --version 2>/dev/null | head -1) ;;
        CURL)    ver=$("$bin_path" --version 2>/dev/null | head -1) ;;
        CHAFA)   ver=$("$bin_path" --version 2>/dev/null | head -1) ;;
        FFPROBE) ver=$("$bin_path" -version 2>/dev/null | head -1) ;;
      esac
      [[ ${#ver} -gt 46 ]] && ver="${ver[1,43]}..."
      printf "  ${G}✔${X}  %-8s  %s\n" "$bin_var" "${ver:-unknown version}"
    else
      local optional=""
      [[ "$bin_var" == "CURL" || "$bin_var" == "CHAFA" || "$bin_var" == "FFPROBE" ]] && optional=" (optional)"
      printf "  ${Y}–${X}  %-8s  ${Y}not found${X}%s\n" "$bin_var" "$optional"
    fi
  done
  echo ""

  # API keys status
  echo "  ${W}API Keys:${X}"
  printf "  YOUTUBE_API_KEY:   %s\n" "$([[ -n "$YOUTUBE_API_KEY" ]] && echo "✔ set (fast API search enabled)" || echo "not set")"
  printf "  INVIDIOUS_HOST:    %s\n" "$([[ -n "$INVIDIOUS_HOST" ]] && echo "✔ set (Invidious search enabled)" || echo "not set")"
  printf "  LASTFM_API_KEY:    %s\n" "$([[ -n "$LASTFM_API_KEY" ]] && echo "✔ set (real similar tracks enabled)" || echo "not set")"
  printf "  SCROBBLE_URL:      %s\n" "$([[ -n "$SCROBBLE_URL" ]] && echo "✔ set" || echo "not set")"
  [[ -z "$YOUTUBE_API_KEY$INVIDIOUS_HOST" ]] && \
    printf "  ${Y}→ tip: set YOUTUBE_API_KEY or INVIDIOUS_HOST in config for instant search${X}\n"
  echo ""

  echo "  ${W}Daemon:${X}"
  if [ ! -S "$SOCKET" ]; then
    printf "  ${R}✖${X}  socket: not present  (%s)\n" "$SOCKET"
  else
    printf "  ${G}✔${X}  socket: exists  (%s)\n" "$SOCKET"
    if echo '{"command":["get_version"]}' \
        | "$SOCAT" -t 2 - "$SOCKET" >/dev/null 2>&1; then
      printf "  ${G}✔${X}  IPC: responsive\n"
      local title; title=$(_get media-title 2>/dev/null)
      if [[ -n "$title" ]]; then
        local paused; paused=$(_get pause 2>/dev/null)
        local vol; vol=$(_get volume 2>/dev/null | awk '{printf "%.0f",$1}')
        printf "  ${G}✔${X}  now playing: %s  (paused=%s  vol=%s%%)\n" "$title" "$paused" "$vol"
      else
        printf "  ${C}→${X}  idle (no track loaded)\n"
      fi
    else
      printf "  ${R}✖${X}  IPC: unresponsive — run: mox stop && mox start\n"
    fi
  fi
  echo ""

  echo "  ${W}Lock files:${X}"
  if [ -d "$LOCK_FILE_D" ]; then
    local lock_pid; lock_pid=$(cat "$LOCK_FILE" 2>/dev/null || echo "")
    if [[ -n "$lock_pid" ]] && kill -0 "$lock_pid" 2>/dev/null; then
      printf "  ${Y}⚠${X}  start.lock held by PID %s (live)\n" "$lock_pid"
    else
      printf "  ${R}✖${X}  start.lock STALE (PID %s dead) — run: mox stop\n" "${lock_pid:-unknown}"
    fi
  else
    printf "  ${G}✔${X}  no stale locks\n"
  fi
  echo ""

  echo "  ${W}Data files:${X}"
  local history_lines=0 likes_lines=0 bm_lines=0
  [ -f "$HISTORY_FILE" ] && history_lines=$(wc -l < "$HISTORY_FILE" | tr -d ' ')
  [ -f "$LIKES_FILE"   ] && likes_lines=$(wc -l < "$LIKES_FILE"   | tr -d ' ')
  [ -f "$BOOKMARKS_FILE" ] && bm_lines=$(wc -l < "$BOOKMARKS_FILE" | tr -d ' ')
  (( history_lines == 0 && likes_lines == 0 && bm_lines == 0 )) && \
    printf "  ${G}✔${X}  ready (history, likes, and bookmarks will fill as you listen)\n"
  (( history_lines > 0 )) && printf "  history:   %s entries\n" "$history_lines"
  (( likes_lines > 0 )) && printf "  likes:     %s entries\n" "$likes_lines"
  (( bm_lines > 0 )) && printf "  bookmarks: %s entries\n" "$bm_lines"
  if [ -f "$LOCAL_INDEX" ]; then
    printf "  local lib: %s tracks indexed\n" "$(wc -l < "$LOCAL_INDEX" | tr -d ' ')"
  fi
  echo ""

  echo "  ${W}Cache:${X}"
  local cache_total=0 cache_expired=0
  local cache_files=("$CACHE_DIR"/*.cache(N))
  for f in "${cache_files[@]}"; do
    [ -f "$f" ] || continue
    cache_total=$(( cache_total + 1 ))
    [ "$(_cache_age "$f")" -ge "$CACHE_TTL" ] && cache_expired=$(( cache_expired + 1 ))
  done
  printf "  %s total  |  %s fresh  |  %s expired  |  TTL: %ss\n" \
    "$cache_total" "$(( cache_total - cache_expired ))" "$cache_expired" "$CACHE_TTL"
  echo ""
}

# ── do_update ───────────────────────────────────────────────────
do_update() {
  _info "updating yt-dlp..."
  local old_ver; old_ver=$("$YTDLP" --version 2>/dev/null | head -1)
  local rc=0
  if [[ "$OS" == "mac" ]]; then
    if command -v brew >/dev/null 2>&1; then brew upgrade yt-dlp 2>&1 || rc=$?
    else "$YTDLP" -U 2>&1 || rc=$?; fi
  else
    if command -v pip3 >/dev/null 2>&1; then pip3 install -U yt-dlp 2>&1 || rc=$?
    elif command -v pip >/dev/null 2>&1; then pip install -U yt-dlp 2>&1 || rc=$?
    else "$YTDLP" -U 2>&1 || rc=$?; fi
  fi
  [[ $rc -ne 0 ]] && _warn "update may have failed (exit $rc)"
  local new_ver; new_ver=$("$YTDLP" --version 2>/dev/null | head -1)
  if [[ "$old_ver" != "$new_ver" ]]; then _ok "yt-dlp updated: ${old_ver} → ${new_ver}"
  else _ok "yt-dlp already up-to-date: ${new_ver}"; fi
  rm -f "$CACHE_DIR/.ytdlp_version_check"
}

# ── do_log ──────────────────────────────────────────────────────
do_log() {
  if [[ ! -s "$MPV_LOG" ]]; then _info "mpv log is empty: $MPV_LOG"; return; fi
  echo ""; echo "  ${C}mpv log:${X}  $MPV_LOG"; echo ""
  tail -50 "$MPV_LOG"; echo ""
}

# ── do_log_clear ────────────────────────────────────────────────
do_log_clear() { > "$MPV_LOG"; _ok "mpv log cleared"; }


# ── do_cache_clear ──────────────────────────────────────────────
do_cache_clear() {
  local -a files
  files=("$CACHE_DIR"/*.cache(N))
  local count=${#files[@]}
  (( count > 0 )) && rm -f "${files[@]}"
  _ok "cleared ${count} cached search(es)"
}

# ── do_cache_stats ──────────────────────────────────────────────
do_cache_stats() {
  local total=0 expired=0 fresh=0
  local -a files
  files=("$CACHE_DIR"/*.cache(N))
  local now; now=$(date +%s)
  for f in "${files[@]}"; do
    total=$(( total + 1 ))
    if [ "$(( now - $(_mtime "$f") ))" -ge "$CACHE_TTL" ]; then expired=$(( expired + 1 ))
    else fresh=$(( fresh + 1 )); fi
  done
  echo ""; echo "  ${C}cache stats:${X}"
  echo "  total:   ${total}"; echo "  fresh:   ${G}${fresh}${X}  (TTL: ${CACHE_TTL}s)"
  echo "  expired: ${Y}${expired}${X}"; echo "  dir:     $CACHE_DIR"; echo ""
}

# ── do_cache_prune ──────────────────────────────────────────────
do_cache_prune() {
  local count=0
  local -a files
  files=("$CACHE_DIR"/*.cache(N))
  local now; now=$(date +%s)
  for f in "${files[@]}"; do
    if [ "$(( now - $(_mtime "$f") ))" -ge "$CACHE_TTL" ]; then rm -f "$f"; count=$(( count + 1 )); fi
  done
  _ok "pruned ${count} expired cache entrie(s)"
}

# ── _load_plugins ───────────────────────────────────────────────
_load_plugins() {
  [[ -d "$PLUGINS_DIR" ]] || return
  # Set nullglob to avoid warnings when no .zsh files exist
  setopt nullglob 2>/dev/null || shopt -s nullglob 2>/dev/null
  for plugin in "$PLUGINS_DIR"/*.zsh; do
    [ -f "$plugin" ] || continue
    local exports
    exports=$(grep -E '^[[:space:]]*(function[[:space:]]+)?[A-Za-z_][A-Za-z0-9_]*[[:space:]]*(\(\))?[[:space:]]*\{' "$plugin" 2>/dev/null \
      | sed -E 's/^[[:space:]]*function[[:space:]]+//; s/[[:space:]]*\(\).*//; s/[[:space:]]*\{.*//')
    if echo "$exports" | grep -Ev '^(do_|_plugin_)' >/dev/null 2>&1; then
      _warn "plugin skipped (only do_* exports allowed): $(basename "$plugin")"
      continue
    fi
    if echo "$exports" | grep -E '^(do_play|do_stop|do_start|do_help|do_update)$' >/dev/null 2>&1; then
      _warn "plugin skipped (core command override blocked): $(basename "$plugin")"
      continue
    fi
    source "$plugin" 2>/dev/null && _info "plugin loaded: $(basename "$plugin")" || \
      _warn "plugin error: $(basename "$plugin")"
  done
  # Reset glob behavior
  unsetopt nullglob 2>/dev/null || shopt -u nullglob 2>/dev/null
}
_load_plugins

# ── Phase 2.1: Custom equalizer bands ───────────────────────────
do_eq_custom() {
  # Dispatcher passes the full argv vector: "eq custom <freq gain...>".
  # Keep these shifts paired with the case arm so plugins should call do_eq instead.
  shift  # consume "eq"
  shift  # consume "custom"
  if [[ $# -lt 2 ]] || (( $# % 2 != 0 )); then
    _err "usage: mox eq custom <freq1> <gain1> [freq2 gain2 ...]  e.g. mox eq custom 60 +8 200 -3 8000 +5"
    return 1
  fi
  _need
  local -a bands
  bands=()
  while [[ $# -ge 2 ]]; do
    local freq="$1" gain="$2"
    shift 2
    [[ "$freq" =~ ^[0-9]+$ ]] || { _err "invalid frequency: $freq"; return 1; }
    [[ "$gain" =~ ^[+-]?[0-9]+(\.[0-9]+)?$ ]] || { _err "invalid gain: $gain"; return 1; }
    bands+=("equalizer=f=${freq}:t=h:w=200:g=${gain}")
  done
  local af="lavfi=[${(j:,:)bands}]"
  _af_set "$af"
  _ok "🎚  custom equalizer: ${#bands[@]} band(s)"
}

# ── Phase 2.2: Crossfade between tracks ─────────────────────────
do_crossfade() {
  local secs="${1:-}"
  if [[ -z "$secs" ]]; then
    _info "crossfade: ${CROSSFADE_SECS:-0}s  (set in config: CROSSFADE_SECS)"
    return
  fi
  [[ "$secs" =~ ^[0-9]+(\.[0-9]+)?$ ]] || { _err "usage: mox crossfade <seconds>"; return 1; }
  # Persist to config file
  if grep -q '^CROSSFADE_SECS=' "$CONFIG_FILE" 2>/dev/null; then
    sed -i.bak "s/^CROSSFADE_SECS=.*/CROSSFADE_SECS=$secs/" "$CONFIG_FILE" 2>/dev/null || \
      sed -i '' "s/^CROSSFADE_SECS=.*/CROSSFADE_SECS=$secs/" "$CONFIG_FILE" 2>/dev/null
  else
    echo "CROSSFADE_SECS=$secs" >> "$CONFIG_FILE"
  fi
  CROSSFADE_SECS="$secs"
  _ok "crossfade set to ${secs}s  (requires mox stop && mox start to apply)"
}

# ── Phase 2.3: Remove duplicate URLs from queue ─────────────────
do_queue_dedup() {
  _need
  local raw pl_count
  raw=$(_cmd '{"command":["get_property","playlist"]}')
  pl_count=$(echo "$raw" | "$JQ" '.data|length' 2>/dev/null)
  pl_count=$(printf '%s' "${pl_count:-0}" | tr -cd '0-9'); pl_count="${pl_count:-0}"
  [[ "$pl_count" -eq 0 ]] && { _warn "queue empty"; return; }
  local dup_indices
  dup_indices=$(echo "$raw" | "$JQ" -r '.data[].filename // ""' 2>/dev/null \
    | awk 'BEGIN { idx = 0 } { if ($0 != "" && seen[$0]++) print idx; idx++ }' \
    | sort -rn)
  local removed=0 idx
  for idx in ${(f)dup_indices}; do
    [[ -z "$idx" ]] && continue
    _silent "{\"command\":[\"playlist-remove\",${idx}]}"
    removed=$(( removed + 1 ))
  done
  [[ $removed -eq 0 ]] && _ok "no duplicates found" || _ok "removed ${removed} duplicate(s)"
}

# ── Phase 2.4: Pin tracks by name ───────────────────────────────
do_pin() {
  local name="${1:-}"
  if [[ -z "$name" ]]; then
    _err "usage: mox pin <name>  — pin current track, or play pinned track if name exists"
    return 1
  fi
  name=$(printf '%s' "$name" | tr ' ' '_' | tr -cd '[:alnum:]_-')
  [[ -z "$name" ]] && { _err "invalid pin name"; return 1; }
  # Check if pin exists — play it
  if awk -F'\t' -v n="$name" '$1==n {exit 0} END{exit 1}' "$PINS_FILE" 2>/dev/null; then
    local url title
    url=$(awk -F'\t' -v n="$name" '$1==n {print $2; exit}' "$PINS_FILE")
    title=$(awk -F'\t' -v n="$name" '$1==n {print $3; exit}' "$PINS_FILE")
    [[ -z "$url" ]] && { _err "could not read pin: $name"; return 1; }
    _start
    _silent '{"command":["playlist-clear"]}'
    _ipc_loadfile "$url" "replace"
    _ok "▶  ${title:-$name}"
    return
  fi
  # Pin current track
  _need
  local cur_url cur_title
  cur_url=$(_get path)
  cur_title=$(_get media-title)
  [[ -z "$cur_url" ]] && { _err 4 "nothing playing — play something first to pin"; return 1; }
  cur_url=$(_clean_url "$cur_url")
  # Remove existing pin with same name
  local tmpf; tmpf=$(mktemp "$PINS_FILE.XXXXXX")
  awk -F'\t' -v n="$name" '$1!=n' "$PINS_FILE" 2>/dev/null > "$tmpf" || true
  printf '%s\t%s\t%s\n' "$name" "$cur_url" "${cur_title:-unknown}" >> "$tmpf"
  mv "$tmpf" "$PINS_FILE"
  _ok "📌 pinned: ${name} → ${cur_title:-unknown}"
}

do_pins() {
  [[ ! -s "$PINS_FILE" ]] && { _info "no pins yet — use: mox pin <name> while playing"; return; }
  echo ""
  echo "  ${C}📌 pins${X}"
  echo ""
  awk -F'\t' '{printf "  %-20s  %s\n", $1, $3}' "$PINS_FILE" | sed 's/^/  /'
  echo ""
}

# ── Phase 2.5: Auto-save queue ──────────────────────────────────
do_queue_save_auto() {
  if [[ -f "$QUEUE_SAVE_AUTO_FILE" ]]; then
    rm -f "$QUEUE_SAVE_AUTO_FILE"
    _ok "auto-save queue: OFF"
  else
    touch "$QUEUE_SAVE_AUTO_FILE"
    _ok "auto-save queue: ON  (saves to $AUTOSAVE_QUEUE_FILE)"
  fi
}

# ── Phase 2.6: Search without playing ───────────────────────────
do_search_only() {
  local show_urls=0
  local -a qparts
  qparts=()
  for part in "$@"; do
    case "$part" in
      --urls) show_urls=1 ;;
      *) qparts+=("$part") ;;
    esac
  done
  local query="${(j: :)qparts}"
  [[ -z "$query" ]] && { _err "usage: mox search <query>"; return 1; }
  local results
  results=$(_do_search "$query") || { _err 5 "search failed"; return 1; }
  [[ -z "$results" ]] && { _warn "no results for: $query"; return; }
  echo ""
  echo "  ${C}search: ${query}${X}"
  echo ""
  if [[ $show_urls -eq 1 ]]; then
    echo "$results" | awk -F ' \| ' '{printf "  %-46s %8s  %s\n", substr($1,1,46), $2, $3}' | head -30
  else
    echo "$results" | awk -F ' \| ' '{printf "  %2d. %-58s %8s\n", NR, substr($1,1,58), $2}' | head -30
    echo ""
    echo "  ${C}tip:${X} add --urls to show source links"
  fi
  echo ""
}

# ── Phase 2.7: Internet radio ────────────────────────────────────
do_radio() {
  _check_deps
  local genre="${1:-}"
  [[ ! -f "$STATIONS_FILE" ]] && { _err "create $STATIONS_FILE (genre\tname\turl per line)"; return 1; }
  [[ ! -s "$STATIONS_FILE" ]] && { _err "stations file empty"; return 1; }
  local stations_content
  stations_content=$(grep -v '^#' "$STATIONS_FILE" 2>/dev/null | grep -v '^[[:space:]]*$')
  [[ -z "$stations_content" ]] && { _err "no stations (add entries to $STATIONS_FILE)"; return 1; }
  local chosen
  if [[ -n "$genre" ]]; then
    chosen=$(echo "$stations_content" | grep -i "^${genre}"$'\t' 2>/dev/null | head -1)
    [[ -z "$chosen" ]] && chosen=$(echo "$stations_content" | "$FZF" --height 40% --reverse --prompt "🎵 radio > " \
      -q "$genre" 2>/dev/null)
  else
    # If no TTY (like in tests), just show the station list
    if [[ ! -t 0 ]] || [[ -n "${MOX_TEST_MODE:-}" ]]; then
      echo "$stations_content" | awk -F'\t' '{printf "%-12s %s\n", $1, $2}'
      return 0
    fi
    chosen=$(echo "$stations_content" | "$FZF" --height 40% --reverse --prompt "🎵 radio > " \
      --header "ENTER play · ESC cancel" \
      --with-nth=1,2 --delimiter=$'\t' 2>/dev/null)
  fi
  [[ -z "$chosen" ]] && { _warn "cancelled"; return; }
  local url; url=$(echo "$chosen" | awk -F'\t' '{print $3}')
  [[ -z "$url" ]] && { _err "invalid station line"; return 1; }
  local name; name=$(echo "$chosen" | awk -F'\t' '{print $2}')

  # In test mode, just show what would be played without starting daemon
  if [[ -n "${MOX_TEST_MODE:-}" ]]; then
    _ok "📻 ▶  ${name:-unknown}"
    return 0
  fi

  _start
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$url" "replace"
  _ok "📻 ▶  ${name:-unknown}"
}

# ── Phase 2.9: Chapter navigation ──────────────────────────────
do_chapter() {
  _need
  _check_deps
  local path; path=$(_get path)
  [[ -z "$path" ]] && { _err 4 "nothing playing"; return 1; }
  [[ "$path" != *youtube* && "$path" != *youtu.be* ]] && { _warn "chapters only for YouTube videos"; return; }
  local chapters
  chapters=$("$YTDLP" --dump-json --no-download "$path" 2>/dev/null | \
    "$JQ" -r '.chapters[]? | "\(.start_time // 0)\t\(.title // "untitled")"' 2>/dev/null)
  [[ -z "$chapters" ]] && { _warn "no chapters in this video"; return; }
  local chosen
  chosen=$(echo "$chapters" | "$FZF" --height 50% --reverse \
    --prompt "⏱ chapter > " --header "ENTER jump · ESC cancel" \
    --with-nth=2 --delimiter=$'\t')
  [[ -z "$chosen" ]] && { _warn "cancelled"; return; }
  local secs; secs=$(echo "$chosen" | awk -F'\t' '{print $1}')
  [[ -z "$secs" ]] && return
  _silent "{\"command\":[\"seek\",\"$secs\",\"absolute\"]}"
  _ok "jumped to chapter: $(echo "$chosen" | awk -F'\t' '{print $2}')"
}

# ── Phase 2.10: Listening statistics ───────────────────────────
do_stats() {
  [[ ! -s "$HISTORY_FILE" ]] && { _warn "no history yet"; return; }
  echo ""
  echo "  ${C}listening stats${X}"
  echo ""
  local total unique most top
  total=$(wc -l < "$HISTORY_FILE" | tr -d ' ')
  unique=$(awk -F'\t' '!seen[$3]++ {c++} END{print c+0}' "$HISTORY_FILE")
  most=$(awk -F'\t' '{count[$3]++} END{for(u in count) if(count[u]>max){max=count[u];best=u} print best}' "$HISTORY_FILE")
  local most_count
  most_count=$(awk -F'\t' -v u="$most" '$3==u {c++} END{print c+0}' "$HISTORY_FILE")
  local most_title
  most_title=$(awk -F'\t' -v u="$most" '$3==u {print $2; exit}' "$HISTORY_FILE")
  echo "  total plays:  ${total}"
  echo "  unique:       ${unique}"
  echo "  most played:  ${most_title:-$most}  (${most_count}x)"
  echo ""
  echo "  ${W}top 10:${X}"
  awk -F'\t' '{count[$3]++; title[$3]=$2} END{for(u in count) print count[u]"\t"title[u]"\t"u}' "$HISTORY_FILE" | \
    sort -rn | head -10 | while IFS=$'\t' read -r c t u; do echo "  ${c}x  ${t}"; done
  echo ""
}

# ── Phase 2.12: Edit config in $EDITOR ──────────────────────────
do_config_edit() {
  [[ -z "${EDITOR:-}" ]] && EDITOR="${VISUAL:-vi}"
  [[ -z "$EDITOR" ]] && { _err "EDITOR not set"; return 1; }
  "$EDITOR" "$CONFIG_FILE"
  _ok "edited: $CONFIG_FILE  (run: mox reload-config to apply)"
}

# ── Phase 2.14: Desktop notification toggle ──────────────────────
do_notify_toggle() {
  if [[ "$NOTIFY_ENABLED" == "1" ]]; then
    # Persist to config
    if grep -q '^NOTIFY_ENABLED=' "$CONFIG_FILE" 2>/dev/null; then
      sed -i.bak 's/^NOTIFY_ENABLED=.*/NOTIFY_ENABLED=0/' "$CONFIG_FILE" 2>/dev/null || \
        sed -i '' 's/^NOTIFY_ENABLED=.*/NOTIFY_ENABLED=0/' "$CONFIG_FILE" 2>/dev/null
    fi
    NOTIFY_ENABLED=0
    _ok "notifications: OFF"
  else
    if grep -q '^NOTIFY_ENABLED=' "$CONFIG_FILE" 2>/dev/null; then
      sed -i.bak 's/^NOTIFY_ENABLED=.*/NOTIFY_ENABLED=1/' "$CONFIG_FILE" 2>/dev/null || \
        sed -i '' 's/^NOTIFY_ENABLED=.*/NOTIFY_ENABLED=1/' "$CONFIG_FILE" 2>/dev/null
    else
      echo "NOTIFY_ENABLED=1" >> "$CONFIG_FILE"
    fi
    NOTIFY_ENABLED=1
    _ok "notifications: ON"
  fi
}

# ── Phase 2.15: History with play counts ─────────────────────────
do_history_stats() {
  _check_deps
  [[ ! -s "$HISTORY_FILE" ]] && { _warn "no history yet"; return; }
  local with_counts
  with_counts=$(awk -F'\t' '{count[$3]++; title[$3]=$2; date[$3]=$1} END{for(u in count) print count[u]"\t"date[u]"\t"title[u]"\t"u}' "$HISTORY_FILE" | sort -rn)
  if [[ ! -t 0 ]] || [[ -n "${MOX_TEST_MODE:-}" ]]; then
    echo ""
    echo "  ${C}history statistics${X}"
    echo ""
    echo "$with_counts" | head -20 | awk -F'\t' '{printf "  %sx  %s  (%s)\n", $1, $3, $2}'
    echo ""
    return 0
  fi
  local line url
  line=$(echo "$with_counts" | "$FZF" --height 60% --reverse \
    --prompt "🕑 history (count) > " \
    --header "ENTER replay · ESC cancel" \
    --with-nth=1,2,3 --delimiter=$'\t' \
    --preview 'echo {} | awk -F"\t" "{printf \"Plays: %s\nDate:  %s\nTitle: %s\nURL:   %s\n\",\$1,\$2,\$3,\$4}"' \
    --preview-window=down:4:wrap)
  [[ -z "$line" ]] && { _warn "cancelled"; return; }
  url=$(echo "$line" | awk -F'\t' '{print $4}')
  [[ -z "$url" ]] && { _err "could not extract URL"; return 1; }
  _start
  _silent '{"command":["playlist-clear"]}'
  _ipc_loadfile "$url" "replace"
  local title; title=$(echo "$line" | awk -F'\t' '{print $3}')
  _ok "▶  ${title:-playing}"
}

# ── Phase 5.3: Shell completions ────────────────────────────────
do_completions() {
  cat <<'COMPLETIONS'
# mox — zsh completion
_mox_completions() {
  local -a cmds
  cmds=(pause next prev stop start shuffle repeat repeat-one clear now bar lyrics art ui uxi uxi-stop scrub queue qmove qrm status hp speakers devices playlists save load pldel import dl dl-list txt txts txtnext txtprev txtnow txtpick txtedit txt-export vol seek speed like unlike likes likes-play love similar smart history history-clear replay eq eq\ custom norm sleep export update doctor queue-restore log log-clear cache-clear cache-prune cache-stats autodj bookmark bookmarks bookmark-load index local scan share schedule reload-config crossfade queue-dedup pin pins queue-save-auto search radio chapter stats config-edit notify-toggle auto-restart-toggle history-stats completions help version)
  _describe 'mox' cmds
}
compdef _mox_completions mox
COMPLETIONS
}

# ── help ──────────────────────────────────────────────────────
do_help() {
  cat <<EOF

  ${C}mox — terminal music CLI${X}   (v7.2.2)
  data: ~/music_system/   config: $CONFIG_FILE
  log:  $MPV_LOG

  ${W}SPEED UP SEARCH${X}
    Set in $CONFIG_FILE:
      YOUTUBE_API_KEY=...   → instant search via YouTube Data API (milliseconds)
      INVIDIOUS_HOST=...    → privacy-friendly Invidious API (fast, no key needed)
      (default: yt-dlp scrape, 2–5s)

  ${W}PLAY${X}
    mox "query"              search YouTube & play (fzf picker)
    mox ~/path/to/file.mp3   play a local file directly
    mox "query" -a           add to queue (dedup-guarded)
    mox "query" -a -f        force-add (bypass dedup)
    mox "query" -an          add as next track (play after current)
    mox "query" -hp          play via headphones
    mox "query" -sp          play via speakers

  ${W}TRANSPORT${X}
    pause / pp             toggle pause
    next  / mn             next track
    prev  / mb             previous track
    seek +30               seek forward 30s (shows mini progress bar)
    seek -15               seek back 15s
    seek 1:30              jump to 1m30s
    seek 90                jump to 90s
    speed 1.5              set playback speed (0.25–4.0)
    speed + / - / r        step speed / reset to 1x
    stop                   kill daemon
    start                  start daemon

  ${W}VOLUME & OUTPUT${X}
    vol / vol 80 / vol + / vol -   show/set/step volume (0-150)
    hp / headphones        switch to headphones
    sp / speakers          switch to speakers
    devices                list audio devices

  ${W}AUDIO FILTERS${X}
    eq [flat|bass|treble|vocal|loud]   equalizer preset
    eq custom <freq> <gain> [...]     custom EQ bands (e.g. eq custom 60 +8 200 -3 8000 +5)
    norm                   toggle loudness normalisation
    crossfade <secs>      set crossfade duration (CROSSFADE_SECS in config)

  ${W}INFO & UI${X}
    now                    current track + position
    bar / progress         live progress bar (p/n/b/seek/vol/r/l=lyrics/q)
    lyrics                 real-time synced lyrics (lrclib.net, no key needed)
    art                    terminal album art (requires chafa)
    ui                     unified TUI dashboard (requires tmux)
    uxi                    launch synced web UI dashboard (auto-starts bridge server)
    uxi-stop               stop the uxi bridge server
    scrub / slider         interactive seek slider
    queue                  show queue
    status                 daemon status + all state

  ${W}QUEUE MANAGEMENT${X}
    shuffle                shuffle queue
    repeat / rp            toggle repeat-playlist
    repeat-one / ro        toggle repeat-one
    clear                  clear queue
    qmove <from> <to>      move track (1-based)
    qrm <pos>              remove track (1-based)
    queue-restore / qr     restore queue from auto-snapshot
    queue-dedup            remove duplicate URLs from queue
    queue-save-auto        toggle auto-save queue to autosave_queue.m3u

  ${W}BOOKMARKS (v5)${X}
    bookmark [name]        save current track+position as named bookmark
    bookmarks              list all bookmarks
    bookmark-load / bl     fzf-pick and restore a bookmark

  ${W}AUTO-DJ (v5)${X}
    autodj                 toggle Auto-DJ (auto-refills queue from Last.fm)
                           set LASTFM_API_KEY for real recommendations

  ${W}LIKES${X}
    like / unlike / likes  like current track / remove / list
    likes-play / lp        fzf-pick & play a liked track
    love                   play random liked track (reservoir sampling)

  ${W}HISTORY${X}
    history                fuzzy-search & replay history (dedup on last 50)
    history-stats          history picker with play counts
    history-clear          wipe history
    replay / rl            replay the last played track
    similar                add similar track (Last.fm or YouTube)
    smart                  add up to 3 related tracks to the queue
    stats                  listening stats (total, unique, most played, top 10)

  ${W}TXT PLAYLISTS${X}
    txts                   list all txt playlists
    txt [name] [--resume]  load txt playlist (v5: parallel resolution, resume)
    txtnext / tn           next song in txt playlist
    txtprev / tp           previous song
    txtnow                 show active txt + context
    txtpick / tj           fzf-jump to any song in txt
    txtedit [name]         edit/create txt file in \$EDITOR
    txt-export             resolve active txt → saved m3u

  ${W}QUEUE PLAYLISTS${X}
    save <n>               save current queue as playlist
    load <n>               load playlist (O(1) dedup)
    playlists / pls        list saved playlists
    pldel <n>              delete playlist

  ${W}LOCAL LIBRARY (v5)${X}
    index                  scan \$LOCAL_MUSIC_DIR with ffprobe, build index
    local [query]          fzf-search & play from local library
    scan --duplicates      find duplicate indexed titles
    scan --unplayed        show indexed tracks not yet in history
    scan --playlist <name> create playlist from local index
    share [name]           write current queue as shareable m3u
    schedule "HH:MM" "q"   schedule playback via launchd/at

  ${W}DOWNLOAD & IMPORT${X}
    dl "query"             download as MP3 (progress visible)
    dl-list                list downloaded files
    import "url"           import YouTube playlist

  ${W}SLEEP TIMER${X}
    sleep <minutes> / sleep cancel   sleep timer

  ${W}EXPORT${X}
    export [likes|history]   print as CSV (CSV injection safe)

  ${W}PINS${X}
    pin <name>             pin current track, or play pinned track if name exists
    pins                   list all pins

  ${W}SEARCH & RADIO${X}
    search <query>         search without playing (table display)
    radio [genre]          internet radio from \$MUSIC_ROOT/stations.tsv

  ${W}VIDEO${X}
    chapter                show YouTube chapters, jump to chapter (fzf)

  ${W}CONFIG${X}
    config-edit            edit config in \$EDITOR
    reload-config          hot-reload config without restarting daemon
    notify-toggle          toggle desktop notifications on track change
    auto-restart-toggle    toggle auto-restart when daemon becomes unresponsive

  ${W}SHELL${X}
    completions            output zsh completion script

  ${W}VERSION & INFO${X}
    version / --version    show version information
    help                   show this help message

  ${W}UPDATES & DIAGNOSTICS${X}
    update                 update yt-dlp
    doctor                 full diagnostics: deps, API keys, IPC, locks, cache
    log / log-clear        mpv error log
    cache-clear/prune/stats  cache management

  ${W}SPONSORBLOCK${X}
    Drop the mpv-sponsorblock lua script into ~/.config/mpv/scripts/ to
    automatically skip non-music sections in YouTube videos.
    Get it: https://github.com/po5/mpv_sponsorblock

  ${W}PLUGINS${X}
    Drop .zsh files into: $PLUGINS_DIR
    They are sourced at startup. Define do_mycommand() functions.

EOF
}

# ── main dispatch ─────────────────────────────────────────────
if [[ "${MOX_LIB_ONLY:-}" != "1" ]]; then
if [ $# -eq 0 ]; then
  if [ ! -S "$SOCKET" ]; then
    echo ""
    echo "  ${BOLD}mox${X} — terminal music CLI"
    echo "  run: ${G}mox help${X} for all commands"
    echo ""
    echo "  Quick start:"
    echo "    ${G}mox \"lofi hip hop\"${X}    search & play"
    echo "    ${G}mox uxi${X}                 open web UI"
    echo ""
  else
    do_status
  fi
  exit 0
fi

case "$1" in
  --version|-V|version) do_version;                   exit 0 ;;
  pause|pp)            do_pause;                   exit 0 ;;
  next|mn)             do_next;                    exit 0 ;;
  prev|mb)             do_prev;                    exit 0 ;;
  stop)                do_stop;                    exit 0 ;;
  start)               do_start;                   exit 0 ;;
  shuffle)             do_shuffle;                 exit 0 ;;
  repeat|rp)           do_repeat;                  exit 0 ;;
  repeat-one|ro)       do_repeat_one;              exit 0 ;;
  clear)               do_clear;                   exit 0 ;;
  now)                 do_now;                     exit 0 ;;
  bar|progress)        do_bar;                     exit 0 ;;
  lyrics)              do_lyrics;                  exit 0 ;;
  art)                 do_art;                     exit 0 ;;
  ui)                  do_ui;                      exit 0 ;;
  uxi)                 do_uxi;                     exit 0 ;;
  uxi-stop)             do_uxi_stop;                 exit 0 ;;
  scrub|slider)        do_scrub;                   exit 0 ;;
  queue)               do_queue;                   exit 0 ;;
  qmove)               do_queue_move "${2:-}" "${3:-}";    exit 0 ;;
  qrm)                 do_queue_remove "${2:-}";       exit 0 ;;
  status)              do_status;                  exit 0 ;;
  hp|headphones)       do_hp;                      exit 0 ;;
  sp|speakers)         do_sp;                      exit 0 ;;
  devices)             do_devices;                 exit 0 ;;
  playlists|pls)       do_playlists;               exit 0 ;;
  save)                do_save "${2:-}";           exit 0 ;;
  load)                do_load "${2:-}";           exit 0 ;;
  pldel)               do_playlist_del "${2:-}";   exit 0 ;;
  import)              do_import "${2:-}";         exit 0 ;;
  dl)                  do_dl "${2:-}";             exit 0 ;;
  dl-list)             do_dl_list;                 exit 0 ;;
  txt)                 do_txt "${2:-}" "${3:-}";   exit 0 ;;
  txts)                do_txts;                    exit 0 ;;
  txtnext|tn)          do_txtnext;                 exit 0 ;;
  txtprev|tp)          do_txtprev;                 exit 0 ;;
  txtnow)              do_txtnow;                  exit 0 ;;
  txtpick|tj)          do_txtpick;                 exit 0 ;;
  txtedit|te)          do_txtedit "${2:-}";        exit 0 ;;
  txt-export)          do_txt_export;              exit 0 ;;
  vol|volume)          do_vol "${2:-}";            exit 0 ;;
  seek)                do_seek "${2:-}";           exit 0 ;;
  speed)               do_speed "${2:-}";          exit 0 ;;
  like)                do_like;                    exit 0 ;;
  unlike)              do_unlike;                  exit 0 ;;
  likes)               do_likes;                   exit 0 ;;
  likes-play|lp)       do_likes_play;              exit 0 ;;
  love)                do_love;                    exit 0 ;;
  similar)             do_similar;                 exit 0 ;;
  smart)               do_smart;                   exit 0 ;;
  history|hist)        do_history;                 exit 0 ;;
  history-clear)       do_history_clear;           exit 0 ;;
  replay|rl)           do_replay;                  exit 0 ;;
  eq)                  if [[ "${2:-}" == "custom" ]]; then do_eq_custom "$@"; else do_eq "${2:-}"; fi; exit 0 ;;
  crossfade)            do_crossfade "${2:-}";     exit 0 ;;
  queue-dedup)          do_queue_dedup;           exit 0 ;;
  pin)                 do_pin "${2:-}";            exit 0 ;;
  pins)                do_pins;                   exit 0 ;;
  queue-save-auto)      do_queue_save_auto;       exit 0 ;;
  search)              shift; do_search_only "$@"; exit 0 ;;
  radio)               do_radio "${2:-}";         exit 0 ;;
  chapter)              do_chapter;               exit 0 ;;
  stats)               do_stats;                  exit 0 ;;
  config-edit)         do_config_edit;           exit 0 ;;
  notify-toggle)        do_notify_toggle;          exit 0 ;;
  auto-restart-toggle)  do_auto_restart_toggle;     exit 0 ;;
  history-stats)       do_history_stats;          exit 0 ;;
  completions)         do_completions;            exit 0 ;;
  norm)                do_norm;                    exit 0 ;;
  sleep)               do_sleep "${2:-}";          exit 0 ;;
  export)              do_export "${2:-}";         exit 0 ;;
  update)              do_update;                  exit 0 ;;
  doctor)              do_doctor;                  exit 0 ;;
  queue-restore|qr)    do_queue_restore;           exit 0 ;;
  log)                 do_log;                     exit 0 ;;
  log-clear)           do_log_clear;               exit 0 ;;
  cache-clear)         do_cache_clear;             exit 0 ;;
  cache-prune)         do_cache_prune;             exit 0 ;;
  cache-stats)         do_cache_stats;             exit 0 ;;
  autodj)              do_autodj;                  exit 0 ;;
  bookmark)            do_bookmark "${2:-}";       exit 0 ;;
  bookmarks)           do_bookmarks;               exit 0 ;;
  bookmark-load|bl)    do_bookmark_load;           exit 0 ;;
  index)               do_index;                   exit 0 ;;
  local)               do_local "${2:-}";          exit 0 ;;
  scan)                do_scan "${2:-}" "${3:-}";  exit 0 ;;
  share)               do_share "${2:-}";          exit 0 ;;
  schedule)            do_schedule "${2:-}" "${3:-}"; exit 0 ;;
  reload-config)       do_reload_config;           exit 0 ;;
  cast)                do_cast;                    exit 0 ;;
  help|-h|--help)      do_help;                    exit 0 ;;
esac

# ── Free-form query with optional flags ───────────────────────
typeset -a QUERY_ARGS
QUERY_ARGS=()
FLAG_ADD=0
FLAG_FORCE=0
FLAG_NEXT=0
FLAG_HP=0
FLAG_SP=0

for arg in "$@"; do
  case "$arg" in
    -a|--add)          FLAG_ADD=1 ;;
    -f|--force)        FLAG_FORCE=1 ;;
    -an|--add-next)    FLAG_ADD=1; FLAG_NEXT=1 ;;
    -hp|--headphones)  FLAG_HP=1 ;;
    -sp|--speakers)    FLAG_SP=1 ;;
    -*)                _die "unknown flag: $arg  (run: mox help)" ;;
    *)                 QUERY_ARGS+=("$arg") ;;
  esac
done

[ ${#QUERY_ARGS[@]} -eq 0 ] && _die "no query — usage: mox \"song name\"  or  mox help"

QUERY="${(j: :)QUERY_ARGS}"

if [ $FLAG_ADD -eq 1 ]; then
  if [ $FLAG_NEXT -eq 1 ]; then
    do_add_next "$QUERY"
  elif [ $FLAG_FORCE -eq 1 ]; then
    do_add_force "$QUERY"
  else
    do_add "$QUERY"
  fi
else
  do_play "$QUERY"
fi

[ $FLAG_HP -eq 1 ] && sleep 0.4 && do_hp
[ $FLAG_SP -eq 1 ] && sleep 0.4 && do_sp
fi
